#ifndef D_A_NPC_KF1_H
#define D_A_NPC_KF1_H

#include "f_op/f_op_actor.h"
#include "d/d_npc.h"
#include "m_Do/m_Do_ext.h"

class J3DNode;
class J3DModel;

class daNpc_Kf1_c : public fopNpc_npc_c {
public:
    typedef int (daNpc_Kf1_c::*ProcFunc)(void*);
    struct anm_prm_c {
        /* 0x00 */ s8 mAnmNum;
        /* 0x01 */ s8 mBtpNum;
        /* 0x02 */ s16 field_0x02;
        /* 0x04 */ f32 mMorf;
        /* 0x08 */ f32 mSpeed;
        /* 0x0C */ int mLoopMode;
    };

    void _nodeCB_Head(J3DNode*, J3DModel*);
    void _nodeCB_Neck(J3DNode*, J3DModel*);
    void _nodeCB_BackBone(J3DNode*, J3DModel*);
    BOOL init_KF1_0();
    BOOL createInit();
    void play_animation();
    void setMtx(bool);
    int bckResID(int);
    int btpResID(int);
    bool setBtp(s8, bool);
    bool init_texPttrnAnm(s8, bool);
    void play_btp_anm();
    void setAnm_anm(anm_prm_c*);
    void setAnm_NUM(int, int);
    void setAnm();
    void chngAnmTag();
    void ctrlAnmTag();
    void chngAnmAtr(u8);
    void ctrlAnmAtr();
    void setAnm_ATR();
    void anmAtr(u16);
    u16 next_msgStatus(u32*);
    u32 getMsg_KF1_0();
    u32 getMsg();
    void eventOrder();
    void checkOrder();
    BOOL chk_talk();
    fopAc_ac_c* searchByID(fpc_ProcID, int*);
    BOOL srch_Tsubo();
    void create_rupee(cXyz, int);
    void ready_kutaniCamera(int, int);
    void lookBack();
    BOOL chkAttention();
    void setAttention(bool);
    BOOL decideType(int);
    void cut_init_ANGRY_START(int);
    BOOL cut_move_ANGRY_START();
    void cut_init_BENSYOU_START(int);
    BOOL cut_move_BENSYOU_START();
    void cut_init_TSUBO_CNT(int);
    BOOL cut_move_TSUBO_CNT();
    void cut_init_BENSYOU(int);
    BOOL cut_move_BENSYOU();
    void cut_init_GET_OUT(int);
    BOOL cut_move_GET_OUT();
    void cut_init_DSP_RUPEE_CNT(int);
    BOOL cut_move_DSP_RUPEE_CNT();
    void cut_init_PLYER_TRN(int);
    BOOL cut_move_PLYER_TRN();
    void cut_init_RUPEE_CNT_END(int);
    BOOL cut_move_RUPEE_CNT_END();
    void cut_init_START_AGE(int);
    BOOL cut_move_START_AGE();
    void cut_init_PLYER_MOV(int);
    BOOL cut_move_PLYER_MOV();
    void cut_init_RUPEE_SET(int);
    BOOL cut_move_RUPEE_SET();
    void cut_init_TSUBO_ATN(int);
    BOOL cut_move_TSUBO_ATN();
    void cut_init_TLK_MSG(int);
    void cut_init_CONTNUE_TLK(int);
    BOOL cut_move_TLK_MSG();
    void privateCut(int);
    void endEvent();
    int isEventEntry();
    void event_proc(int);
    BOOL set_action(ProcFunc, void*);
    void setStt(s8);
    void set_pthPoint(u8);
    s16 chk_tsubo();
    BOOL orderTsuboEvent();
    BOOL wait_1();
    BOOL walk_1();
    BOOL talk_1();
    BOOL wait_action1(void*);
    BOOL demo();
    void shadowDraw();
    BOOL _draw();
    BOOL _execute();
    BOOL _delete();
    cPhs_State _create();
    BOOL bodyCreateHeap();
    BOOL itemCreateHeap();
    BOOL CreateHeap();

public:
    /* 0x6C4 */ request_of_phase_process_class mPhs;
    /* 0x6CC */ s8 mHeadJntNo;
    /* 0x6CD */ s8 mBackboneJntNo;
    /* 0x6CE */ s8 mNeckJntNo;
    /* 0x6CF */ u8 field_0x6cf;
    /* 0x6D0 */ J3DModel* mpItemModel;
    /* 0x6D4 */ char mArcName[4];
    /* 0x6D8 */ u32 mShadowID;
    /* 0x6DC */ mDoExt_btpAnm mBtpAnm;
    /* 0x6F0 */ u8 mBtpFrame;
    /* 0x6F1 */ u8 field_0x6f1;
    /* 0x6F2 */ s16 mBtpTimer;
    /* 0x6F4 */ ProcFunc mProcFunc;
    /* 0x700 */ fpc_ProcID m700;
    /* 0x704 */ fpc_ProcID m704;
    /* 0x708 */ dNpc_PathRun_c mPath;
    /* 0x710 */ cXyz mHomePos;
    /* 0x71C */ csXyz mHomeAngle;
    /* 0x722 */ csXyz m722;
    /* 0x728 */ u8 field_0x728[8];
    /* 0x730 */ cXyz mEyePos;
    /* 0x73C */ cXyz mTargetPos;
    /* 0x748 */ u8 field_0x748[0xC];
    /* 0x754 */ cXyz mHeadPos;
    /* 0x760 */ u8 field_0x760[0xC];
    /* 0x76C */ f32 mPrevMorfFrame;
    /* 0x770 */ u8 field_0x770[4];
    /* 0x774 */ s16 m774;
    /* 0x776 */ s16 m776;
    /* 0x778 */ s16 m778;
    /* 0x77A */ u8 field_0x77a[2];
    /* 0x77C */ u32 m77C;
    /* 0x780 */ s16 mEvtIdx[3];
    /* 0x786 */ s16 mCurEvtIdx;
    /* 0x788 */ u8 field_0x788[4];
    /* 0x78C */ s16 mCutTimer;
    /* 0x78E */ s16 m78E;
    /* 0x790 */ s16 m790;
    /* 0x792 */ s16 m792;
    /* 0x794 */ s16 m794;
    /* 0x796 */ u8 field_0x796[4];
    /* 0x79A */ s16 m79A;
    /* 0x79C */ u8 mAnmResult;
    /* 0x79D */ u8 m79D;
    /* 0x79E */ u8 m79E;
    /* 0x79F */ u8 m79F;
    /* 0x7A0 */ u8 m7A0;
    /* 0x7A1 */ u8 mTalkStt;
    /* 0x7A2 */ u8 field_0x7a2;
    /* 0x7A3 */ u8 mGroundChk;
    /* 0x7A4 */ u8 mWallChk;
    /* 0x7A5 */ u8 m7A5;
    /* 0x7A6 */ u8 mPhaseFlag;
    /* 0x7A7 */ u8 m7A7;
    /* 0x7A8 */ u8 mStartAge;
    /* 0x7A9 */ u8 m7A9;
    /* 0x7AA */ u8 mInitFlag;
    /* 0x7AB */ u8 mAttention;
    /* 0x7AC */ u8 mTalkOrder;
    /* 0x7AD */ u8 mLookFlag;
    /* 0x7AE */ u8 mDemoFlag;
    /* 0x7AF */ u8 field_0x7af;
    /* 0x7B0 */ fpc_ProcID mItemProcId[3];
    /* 0x7BC */ fpc_ProcID mTsuboProcId[8];
    /* 0x7DC */ fpc_ProcID mKutaniProcId[3];
    /* 0x7E8 */ fpc_ProcID m7E8;
    /* 0x7EC */ s16 mTsuboCnt;
    /* 0x7EE */ s16 mTsuboIdx;
    /* 0x7F0 */ u16 mRupeeCnt;
    /* 0x7F2 */ u8 mCutIdx;
    /* 0x7F3 */ u8 mAtr;
    /* 0x7F4 */ u8 mTag;
    /* 0x7F5 */ s8 mBtpNo;
    /* 0x7F6 */ s8 mAnmNo;
    /* 0x7F7 */ s8 mOrder;
    /* 0x7F8 */ u8 mStatus;
    /* 0x7F9 */ s8 mPrevStatus;
    /* 0x7FA */ u8 mLookMode;
    /* 0x7FB */ s8 mType;
    /* 0x7FC */ u8 mType2;
    /* 0x7FD */ u8 mPhase;
    /* 0x7FE */ u8 m7FE;
    /* 0x7FF */ u8 field_0x7ff;
};  // Size: 0x800

#endif /* D_A_NPC_KF1_H */
