//
// Generated by dtk
// Translation Unit: d_a_swpropeller.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_swpropeller.h"
#include "d/d_a_obj.h"
#include "d/d_com_inf_game.h"
#include "d/d_drawlist.h"
#include "d/d_kankyo.h"
#include "m_Do/m_Do_ext.h"
#include "m_Do/m_Do_mtx.h"
#include "JSystem/J3DGraphAnimator/J3DJoint.h"
#include "JSystem/J3DGraphAnimator/J3DModel.h"
#include "JSystem/J3DGraphAnimator/J3DModelData.h"
#include "JSystem/J3DGraphBase/J3DSys.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "JSystem/JUtility/JUTNameTab.h"
#include "JAZelAudio/JAIZelBasic.h"
#include "SSystem/SComponent/c_lib.h"
#include "string.h"

const char* daSwProp_c::m_arcname[2] = {"Hpbot1", "Vpbot_00"};
const s16 daSwProp_c::m_bdlidx[2] = {3, 3};
const u32 daSwProp_c::m_heapsize[2] = {0x880, 0x8C0};

static dCcD_SrcCyl l_cyl_src = {
    // dCcD_SrcGObjInf
    {
        /* Flags             */ 0,
        /* SrcObjAt  Type    */ 0,
        /* SrcObjAt  Atp     */ 0,
        /* SrcObjAt  SPrm    */ 0,
        /* SrcObjTg  Type    */ AT_TYPE_ALL & ~AT_TYPE_BOOMERANG & ~AT_TYPE_FAN_SWING,
        /* SrcObjTg  SPrm    */ cCcD_TgSPrm_Set_e | cCcD_TgSPrm_IsOther_e,
        /* SrcObjCo  SPrm    */ cCcD_CoSPrm_Set_e | cCcD_CoSPrm_IsOther_e | cCcD_CoSPrm_VsGrpAll_e,
        /* SrcGObjAt Se      */ 0,
        /* SrcGObjAt HitMark */ dCcG_AtHitMark_None_e,
        /* SrcGObjAt Spl     */ dCcG_At_Spl_UNK0,
        /* SrcGObjAt Mtrl    */ 0,
        /* SrcGObjAt SPrm    */ dCcG_AtSPrm_NoConHit_e,
        /* SrcGObjTg Se      */ 0,
        /* SrcGObjTg HitMark */ 0,
        /* SrcGObjTg Spl     */ dCcG_Tg_Spl_UNK0,
        /* SrcGObjTg Mtrl    */ 0,
        /* SrcGObjTg SPrm    */ dCcG_TgSPrm_Shield_e | dCcG_TgSPrm_NoHitMark_e,
        /* SrcGObjCo SPrm    */ 0,
    },
    // cM3dGCylS
    {{
        /* Center */ {0.0f, 0.0f, 0.0f},
        /* Radius */ 100.0f,
        /* Height */ 80.0f,
    }},
};

/* 0x00000078-0x000000B8       .text _delete__10daSwProp_cFv */
bool daSwProp_c::_delete() {
    dComIfG_resDelete(&mPhs, m_arcname[m64D]);
    return true;
}

/* 0x000000B8-0x000000D8       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c* i_this) {
    return static_cast<daSwProp_c*>(i_this)->CreateHeap();
}

/* 0x000000D8-0x000001B8       .text CreateHeap__10daSwProp_cFv */
BOOL daSwProp_c::CreateHeap() {
    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectRes(m_arcname[m64D], m_bdlidx[m64D]);
    JUT_ASSERT(0x101, modelData != 0);

    mpModel = mDoExt_J3DModel__create(modelData, 0x80000, 0x11000022);
    if (mpModel == NULL) {
        return false;
    }

    mpModel->setUserArea((u32)this);
    return true;
}

static BOOL nodeCallBack(J3DNode*, int);

/* 0x000001B8-0x00000350       .text CreateInit__10daSwProp_cFv */
void daSwProp_c::CreateInit() {
    fopAcM_SetMtx(this, mpModel->getBaseTRMtx());
    fopAcM_setCullSizeBox(this, -150.0f, -100.0f, -150.0f, 150.0f, 150.0f, 150.0f);
    cullSizeFar = 1.0f;

    mAcchCir.SetWall(30.0f, 30.0f);
    mAcch.Set(&current.pos, &old.pos, this, 1, &mAcchCir, &speed, NULL, NULL);
    mAcch.SetWallNone();
    mAcch.SetWaterNone();
    mAcch.SetRoofNone();

    mStts.Init(0xff, 0xff, this);
    mCyl.Set(l_cyl_src);
    mCyl.SetStts(&mStts);

    m648 = fopAcM_GetParam(this) & 0xFF;
    set_mtx();

    JUTNameTab* jointName = mpModel->getModelData()->getJointName();
    for (u16 i = 0; i < mpModel->getModelData()->getJointNum(); i++) {
        if (strcmp("kaiten", jointName->getName(i)) == 0) {
            mpModel->getModelData()->getJointNodePointer(i)->setCallBack(&nodeCallBack);
            break;
        }
    }

    mpModel->calc();
}

/* 0x00000350-0x00000404       .text nodeCallBack__FP7J3DNodei */
static BOOL nodeCallBack(J3DNode* i_node, int i_timing) {
    if (i_timing == J3DNodeCBCalcTiming_In) {
        u32 jntNo = ((J3DJoint*)i_node)->getJntNo();
        J3DModel* model = j3dSys.getModel();
        daSwProp_c* i_this = (daSwProp_c*)model->getUserArea();
        if (i_this != NULL) {
            i_this->mRotY += i_this->mRotYVel;
            mDoMtx_stack_c::copy(model->getAnmMtx(jntNo));
            mDoMtx_stack_c::YrotM(i_this->mRotY);
            model->setAnmMtx(jntNo, mDoMtx_stack_c::get());
            mDoMtx_copy(mDoMtx_stack_c::get(), J3DSys::mCurrentMtx);
        }
    }
    return TRUE;
}

/* 0x00000404-0x00000590       .text _create__10daSwProp_cFv */
cPhs_State daSwProp_c::_create() {
    fopAcM_ct(this, daSwProp_c);

    m64D = fopAcM_GetParamBit(fopAcM_GetParam(this), 8, 4);

    cPhs_State ret = dComIfG_resLoad(&mPhs, m_arcname[m64D]);
    if (ret == cPhs_COMPLEATE_e) {
        if (!fopAcM_entrySolidHeap(this, CheckCreateHeap, m_heapsize[m64D])) {
            return cPhs_ERROR_e;
        }
        CreateInit();
    }
    return ret;
}

/* 0x000007B8-0x00000838       .text set_mtx__10daSwProp_cFv */
void daSwProp_c::set_mtx() {
    /* Nonmatching */
    mpModel->setBaseScale(scale);
    mDoMtx_stack_c::transS(current.pos);
    mDoMtx_stack_c::YrotM(current.angle.y);
    mDoMtx_copy(mDoMtx_stack_c::get(), mpModel->getBaseTRMtx());
}

/* 0x00000838-0x00000B60       .text _execute__10daSwProp_cFv */
bool daSwProp_c::_execute() {
    /* Nonmatching */
    mAcch.CrrPos(*dComIfG_Bgsp());

    u8 hit = 0;
    if (mCyl.ChkTgHit()) {
        cCcD_Obj* hitObj = mCyl.GetTgHitObj();
        if (hitObj != NULL) {
            u32 atType = hitObj->GetAtType();
            if (atType & AT_TYPE_WIND) {
                hit = 1;
                m64E = 0;
                JAIZelBasic::zel_basic->seStart(JA_SE_OBJ_PROP_SW_ON, &eyePos, 0,
                                                dComIfGp_getReverb(current.roomNo), 1.0f, 1.0f, -1.0f, -1.0f, 0);
            } else if (atType & 0xFF1DFEFF) {
                mRotYVel = 0x300;
                m644 = (s16)(-0.45f * mRotYVel);
                m64E = 1;

                if ((hitObj->GetAtType() & AT_TYPE_SWORD) || (hitObj->GetAtType() & AT_TYPE_SKULL_HAMMER) ||
                    (hitObj->GetAtType() & AT_TYPE_PGANON_SWORD) || (hitObj->GetAtType() & AT_TYPE_MACHETE)) {
                    if (m64D == 1) {
                        daObj::HitSeStart(&current.pos, current.roomNo, &mCyl, 0xB);
                    } else if (m64D == 0) {
                        daObj::HitSeStart(&current.pos, current.roomNo, &mCyl, 0x11);
                    }
                }
            }
        }
    }

    if (hit) {
        mRotYVel = 0x1000;
        m644 = 0;
    } else if (m64C) {
        dComIfGs_revSwitch(m648, home.roomNo);
    }

    s16 diff = cLib_addCalcAngleS(&mRotYVel, m644, m64E ? 10 : 30, 100, 10);
    if (m64E && diff == 0) {
        m644 = (s16)(-0.6f * m644);
        if (abs(m644) < 0x20) {
            m644 = 0;
            m64E = 0;
        }
    }

    if (m64D == 1) {
        JAIZelBasic::zel_basic->seStart(JA_SE_OBJ_KM_WINDMILL, &current.pos,
                                        (u32)(100.0f * mRotYVel / 4096.0f), 0, 1.0f, 1.0f, -1.0f, -1.0f, 0);
    }

    m64C = hit;
    set_mtx();

    cXyz center(current.pos.x, current.pos.y + 50.0f, current.pos.z);
    mCyl.SetC(center);
    dComIfG_Ccsp()->Set(&mCyl);
    return true;
}

/* 0x00000B60-0x00000C00       .text _draw__10daSwProp_cFv */
bool daSwProp_c::_draw() {
    /* Nonmatching */
    g_env_light.settingTevStruct(0, &current.pos, &tevStr);
    g_env_light.setLightTevColorType(mpModel, &tevStr);
    mDoExt_modelUpdateDL(mpModel);

    if (mAcch.GetGroundH() != -1000000000.0f) {
        dComIfGd_setSimpleShadow2(&current.pos, mAcch.GetGroundH(), 65.0f, mAcch.m_gnd, 0, 1.0f,
                                  dDlst_shadowControl_c::getSimpleTex());
    }
    return true;
}

/* 0x00000C00-0x00000C20       .text daSwProp_Create__FPv */
static cPhs_State daSwProp_Create(void* i_this) {
    return ((daSwProp_c*)i_this)->_create();
}

/* 0x00000C20-0x00000C44       .text daSwProp_Delete__FPv */
static BOOL daSwProp_Delete(void* i_this) {
    return ((daSwProp_c*)i_this)->_delete();
}

/* 0x00000C44-0x00000C68       .text daSwProp_Draw__FPv */
static BOOL daSwProp_Draw(void* i_this) {
    return ((daSwProp_c*)i_this)->_draw();
}

/* 0x00000C68-0x00000C8C       .text daSwProp_Execute__FPv */
static BOOL daSwProp_Execute(void* i_this) {
    return ((daSwProp_c*)i_this)->_execute();
}

/* 0x00000C8C-0x00000C94       .text daSwProp_IsDelete__FPv */
static BOOL daSwProp_IsDelete(void*) {
    return TRUE;
}

static actor_method_class daSwPropMethodTable = {
    (process_method_func)daSwProp_Create,
    (process_method_func)daSwProp_Delete,
    (process_method_func)daSwProp_Execute,
    (process_method_func)daSwProp_IsDelete,
    (process_method_func)daSwProp_Draw,
};

actor_process_profile_definition g_profile_SW_PROPELLER = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_SW_PROPELLER_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daSwProp_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_SW_PROPELLER_e,
    /* Actor SubMtd */ &daSwPropMethodTable,
    /* Status       */ fopAcStts_CULL_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
