//
// Generated by dtk
// Translation Unit: d_a_grid.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/actor/d_a_grid.h"
#include "d/d_camera.h"
#include "f_op/f_op_camera.h"
#include "JSystem/J3DGraphBase/J3DPacket.h"

class daShip_c;
daShip_c* l_ship;

struct l_pos_t {
    /* 0x00 */ f32 m00;
    /* 0x04 */ f32 mX;
    /* 0x08 */ f32 mZ;
};

static l_pos_t l_pos[0x55] = {
    { 0.0f, 5.0f, 0.0f },
    { 0.0f, 5.0f, -48.33332061767578f },
    { 0.0f, 5.0f, -96.66665649414062f },
    { 0.0f, 5.0f, -145.0f },
    { 0.0f, 5.0f, -193.3333282470703f },
    { 0.0f, 5.0f, -241.66665649414062f },
    { 0.0f, 5.0f, -290.0f },
    { 0.0f, 35.0f, 0.0f },
    { 0.0f, 35.55553436279297f, -46.13637161254883f },
    { 0.0f, 36.111106872558594f, -92.2727279663086f },
    { 0.0f, 36.66666030883789f, -138.4091033935547f },
    { 0.0f, 37.22221374511719f, -184.5454559326172f },
    { 0.0f, 37.777767181396484f, -230.68182373046875f },
    { 0.0f, 38.33332061767578f, -276.81817626953125f },
    { 0.0f, 65.0f, 0.0f },
    { 0.0f, 66.1111068725586f, -43.93940353393555f },
    { 0.0f, 67.22221374511719f, -87.87879180908203f },
    { 0.0f, 68.33332061767578f, -131.81817626953125f },
    { 0.0f, 69.44442749023438f, -175.75758361816406f },
    { 0.0f, 70.55553436279297f, -219.6969757080078f },
    { 0.0f, 71.66665649414062f, -263.6363525390625f },
    { 0.0f, 95.0f, 0.0f },
    { 0.0f, 96.66665649414062f, -41.742435455322266f },
    { 0.0f, 98.33332061767578f, -83.48485565185547f },
    { 0.0f, 100.0f, -125.22727966308594f },
    { 0.0f, 101.66665649414062f, -166.96969604492188f },
    { 0.0f, 103.33332061767578f, -208.71212768554688f },
    { 0.0f, 105.0f, -250.45452880859375f },
    { 0.0f, 125.0f, 0.0f },
    { 0.0f, 127.22221374511719f, -39.54545211791992f },
    { 0.0f, 129.44444274902344f, -79.0909194946289f },
    { 0.0f, 131.6666717529297f, -118.63636779785156f },
    { 0.0f, 133.88888549804688f, -158.1818084716797f },
    { 0.0f, 136.11111450195312f, -197.72726440429688f },
    { 0.0f, 138.33334350585938f, -237.27272033691406f },
    { 0.0f, 155.0f, 0.0f },
    { 0.0f, 157.7777862548828f, -37.34848403930664f },
    { 0.0f, 160.55557250976562f, -74.69696807861328f },
    { 0.0f, 163.33335876464844f, -112.04544830322266f },
    { 0.0f, 166.11111450195312f, -149.39393615722656f },
    { 0.0f, 168.88888549804688f, -186.74241638183594f },
    { 0.0f, 171.6666717529297f, -224.0908966064453f },
    { 0.0f, 185.0f, 0.0f },
    { 0.0f, 188.3333282470703f, -35.15151596069336f },
    { 0.0f, 191.66664123535156f, -70.30303192138672f },
    { 0.0f, 195.0f, -105.45455169677734f },
    { 0.0f, 198.3333282470703f, -140.60606384277344f },
    { 0.0f, 201.66664123535156f, -175.757568359375f },
    { 0.0f, 205.0f, -210.90908813476562f },
    { 0.0f, 215.0f, 0.0f },
    { 0.0f, 218.88885498046875f, -32.95454788208008f },
    { 0.0f, 222.77774047851562f, -65.90909576416016f },
    { 0.0f, 226.66664123535156f, -98.86363220214844f },
    { 0.0f, 230.55552673339844f, -131.81817626953125f },
    { 0.0f, 234.44442749023438f, -164.77273559570312f },
    { 0.0f, 238.3333282470703f, -197.72726440429688f },
    { 0.0f, 245.0f, 0.0f },
    { 0.0f, 249.44442749023438f, -30.757579803466797f },
    { 0.0f, 253.88885498046875f, -61.515159606933594f },
    { 0.0f, 258.33331298828125f, -92.2727279663086f },
    { 0.0f, 262.77777099609375f, -123.03030395507812f },
    { 0.0f, 267.22222900390625f, -153.7878875732422f },
    { 0.0f, 271.6666259765625f, -184.5454559326172f },
    { 0.0f, 275.0f, 0.0f },
    { 0.0f, 279.27081298828125f, -23.06818389892578f },
    { 0.0f, 282.6041259765625f, -46.13637161254883f },
    { 0.0f, 285.9375f, -69.20454406738281f },
    { 0.0f, 289.2708740234375f, -92.2727279663086f },
    { 0.0f, 292.6041259765625f, -115.34091186523438f },
    { 0.0f, 295.9375f, -138.40908813476562f },
    { 0.0f, 306.25f, 0.0f },
    { 0.0f, 309.09722900390625f, -15.378789901733398f },
    { 0.0f, 311.3194274902344f, -30.757579803466797f },
    { 0.0f, 313.5416259765625f, -46.1363639831543f },
    { 0.0f, 315.7638854980469f, -61.51515197753906f },
    { 0.0f, 317.9861145019531f, -76.8939437866211f },
    { 0.0f, 320.20831298828125f, -92.2727279663086f },
    { 0.0f, 337.5f, 0.0f },
    { 0.0f, 338.9236145019531f, -7.689395904541016f },
    { 0.0f, 340.03472900390625f, -15.378789901733398f },
    { 0.0f, 341.14581298828125f, -23.068180084228516f },
    { 0.0f, 342.2569274902344f, -30.75757598876953f },
    { 0.0f, 343.3680725097656f, -38.44697189331055f },
    { 0.0f, 344.4791259765625f, -46.1363639831543f },
    { 0.0f, 368.75f, 0.0f },
};

static daHo_HIO_c l_HIO;

/* 800EB4D0-800EB520       .text __dt__10daHo_HIO_cFv */
daHo_HIO_c::~daHo_HIO_c() {
    mChildId = -1;
}

/* 800EB520-800EB5D8       .text __dt__13daHo_packet_cFv */
daHo_packet_c::~daHo_packet_c() {}

/* 800E8CC0-800E8D48       .text setBackNrm__13daHo_packet_cFv */
void daHo_packet_c::setBackNrm() {
    cXyz* nrm = mNrm2[mCount];
    cXyz* pos = mPos[mCount];
    for (s32 i = 0; i < 0x55; i++) {
        pos->set(0.0f, 0.0f, 0.0f);
        PSVECSubtract(pos, nrm, pos);
        nrm++;
        pos++;
    }
}

/* 800E8D48-800E8D74       .text setNrmMtx__13daHo_packet_cFR4cXyz */
void daHo_packet_c::setNrmMtx(cXyz&) {
    mDoMtx_YrotS(*calc_mtx, m189C);
}

/* 800E8D74-800E92AC       .text setNrmVtx__13daHo_packet_cFP4cXyzii */
void daHo_packet_c::setNrmVtx(cXyz*, int, int) {
    /* Nonmatching */
}

/* 800E92AC-800E93B8       .text setTopNrmVtx__13daHo_packet_cFP4cXyz */
void daHo_packet_c::setTopNrmVtx(cXyz*) {
    /* Nonmatching */
}

/* 800E93B8-800E9BE8       .text draw__13daHo_packet_cFv */
void daHo_packet_c::draw() {
    /* Nonmatching */
}

/* 800E9BE8-800E9C0C       .text daGrid_Draw__FP8daGrid_c */
static BOOL daGrid_Draw(daGrid_c* i_this) {
    return ((daGrid_c*)i_this)->_draw();
}

/* 800E9C0C-800EA928       .text ho_move__FP8daGrid_c */
void ho_move(daGrid_c*) {
    /* Nonmatching */
}

/* 800EA928-800EA94C       .text daGrid_Execute__FP8daGrid_c */
static BOOL daGrid_Execute(daGrid_c* i_this) {
    return ((daGrid_c*)i_this)->_execute();
}

/* 800EA94C-800EA954       .text daGrid_IsDelete__FP8daGrid_c */
static BOOL daGrid_IsDelete(daGrid_c*) {
    return TRUE;
}

/* 800EA954-800EA978       .text daGrid_Delete__FP8daGrid_c */
static BOOL daGrid_Delete(daGrid_c* i_this) {
    return ((daGrid_c*)i_this)->_delete();
}

/* 800EA978-800EA998       .text daGrid_Create__FP10fopAc_ac_c */
static cPhs_State daGrid_Create(fopAc_ac_c* i_this) {
    return ((daGrid_c*)i_this)->_create();
}

/* 800EA998-800EAEAC       .text _create__8daGrid_cFv */
cPhs_State daGrid_c::_create() {
    /* Nonmatching */
    fopAcM_SetupActor(this, daGrid_c);

    mParam = fopAcM_GetParam(this);

    cPhs_State st = dComIfG_resLoad(&mPhase1, &"Ship\0Cloth\0船の帆"[5]);
    if (st != cPhs_COMPLEATE_e) {
        return st;
    }
    st = dComIfG_resLoad(&mPhase2, &"Ship\0Cloth\0船の帆"[0]);
    if (st != cPhs_COMPLEATE_e) {
        return st;
    }

    if (l_HIO.mChildId < 0) {
        l_HIO.mChildId = mDoHIO_createChild(&"Ship\0Cloth\0船の帆"[0xB], (JORReflexible*)&l_HIO);
    }

    for (s32 i = 0; i < 0x55; i++) {
        f32 f27;
        if (i >= 0 && i <= 6) {
            f27 = 40.0f;
        } else if (i >= 7 && i <= 0xD) {
            f27 = 70.0f;
        } else if ((i >= 0x31 && i <= 0x37) || (i >= 0x2A && i <= 0x30)) {
            f27 = 85.0f;
        } else {
            f27 = 80.0f;
        }

        s32 r29 = 6;
        f32 f4 = std::fabsf(l_pos[0].mZ - l_pos[i].mZ);
        f32 z = l_pos[i].mZ;
        f32 f2 = std::fabsf(l_pos[6].mZ - z);
        f32 f0 = 1.05f * (1.5707964f / (std::fabsf(l_pos[0].mZ - l_pos[6].mZ) * 0.5f));
        if (f4 > f2) {
            f4 = f2;
        }
        f32 f27s = f27 * (f32)sin(f4 * f0);

        for (s32 j = 0; j < 7; j++) {
            if (i == j || i == j + 7 || i == j + 0xE || i == j + 0x15 || i == j + 0x1C ||
                i == j + 0x23 || i == j + 0x2A || i == j + 0x31 || i == j + 0x38 ||
                i == j + 0x3F || i == j + 0x46 || i == j + 0x4D) {
                r29 = j + 0x38;
            }
        }

        f32 x1 = l_pos[i].mX;
        f32 x2 = l_pos[r29].mX;
        f32 f0_2, f4_2, f1_2, f26;
        if (x1 < x2) {
            f0_2 = std::fabsf(l_pos[0].mX - x1);
            f4_2 = std::fabsf(x2 - x1);
            f1_2 = 1.05f * (1.5707964f / (std::fabsf(x2 - l_pos[0].mX) * 0.5f));
            if (r29 == 0x38) {
                f26 = 35.0f;
            } else if (r29 == 0x39) {
                f26 = 70.0f;
            } else {
                f26 = 80.0f;
            }
        } else {
            f0_2 = std::fabsf(x2 - x1);
            f4_2 = std::fabsf(l_pos[0x54].mX - x1);
            f1_2 = 1.15f * (1.5707964f / (std::fabsf(x2 - l_pos[0x54].mX) * 0.5f));
            f26 = 20.0f;
        }
        if (f0_2 > f4_2) {
            f0_2 = f4_2;
        }
        f32 f0_3 = f26 * (f32)sin(f0_2 * f1_2);
        f32 f4_3 = f27s * f27s + f0_3 * f0_3;
        if (f4_3 > 0.0f) {
            volatile f32 spC;
            double guess = __frsqrte(f4_3);
            guess = 0.5 * guess * (3.0 - guess * guess * f4_3);
            guess = 0.5 * guess * (3.0 - guess * guess * f4_3);
            guess = 0.5 * guess * (3.0 - guess * guess * f4_3);
            spC = (f32)(f4_3 * guess);
            f4_3 = spC;
        }
        mWind[i] = f4_3;
    }

    s16 name = 0xA7;
    l_ship = (daShip_c*)fopAcIt_Judge(fpcSch_JudgeForPName, &name);
    ho_move(this);
    return cPhs_COMPLEATE_e;
}

/* 800EAEAC-800EAF28       .text _delete__8daGrid_cFv */
bool daGrid_c::_delete() {
    dComIfG_resDelete(&mPhase1, &"Ship\0Cloth\0船の帆"[5]);
    dComIfG_resDelete(&mPhase2, &"Ship\0Cloth\0船の帆"[0]);
    if (l_HIO.mChildId >= 0) {
        mDoHIO_deleteChild(l_HIO.mChildId);
        l_HIO.mChildId = -1;
    }
    return true;
}

/* 800EAF28-800EB0EC       .text _execute__8daGrid_cFv */
bool daGrid_c::_execute() {
    /* Nonmatching */
    u8 alpha = mPacket.mAlpha;

    s32 target;
    if (g_dComIfG_gameInfo.play.mEvtCtrl.mMode == 0) {
        cXyz eye = dComIfGp_getCamera(0)->mCamera.Eye();
        f32 dist = PSVECSquareMag(&(current.pos - eye));
        dist = std::sqrtf(dist);
        s32 result;
        if (dist > l_HIO.m34) {
            result = l_HIO.m30;
        } else {
            f32 t = dist / l_HIO.m34;
            result = (s32)((f32)l_HIO.m30 * t + (f32)l_HIO.m31 * (1.0f - t));
        }
        target = result;
    } else {
        target = l_HIO.m30;
    }

    u8 t8 = target & 0xFF;
    if (t8 > alpha + 5) {
        mPacket.mAlpha = alpha + 5;
    } else if (t8 < alpha - 5) {
        mPacket.mAlpha = alpha - 5;
    } else {
        mPacket.mAlpha = t8;
    }

    if (scale.y < 0.06f) {
        return true;
    }
    ho_move(this);
    return true;
}

/* 800EB0EC-800EB328       .text _draw__8daGrid_cFv */
bool daGrid_c::_draw() {
    /* Nonmatching */
}

static actor_method_class l_daGrid_Method = {
    (process_method_func)daGrid_Create,
    (process_method_func)daGrid_Delete,
    (process_method_func)daGrid_Execute,
    (process_method_func)daGrid_IsDelete,
    (process_method_func)daGrid_Draw,
};

actor_process_profile_definition g_profile_GRID = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_GRID_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daGrid_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_GRID_e,
    /* Actor SubMtd */ &l_daGrid_Method,
    /* Status       */ fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_0_e,
};
