//
// Generated by dtk
// Translation Unit: d_a_sitem.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_sitem.h"
#include "d/d_cc_d.h"
#include "d/d_s_play.h"

static f32 size_d[10] = { 10.0f, 10.0f, 9.5f, 9.0f, 8.5f, 8.0f, 7.5f, 7.0f, 6.5f, 6.5f };
static f32 g_d[10] = { 50.0f, 50.0f, 35.0f, 25.0f, 15.0f, 9.0f, 6.0f, 6.0f, 6.0f, 6.0f };
static u16 bmd_data[3] = { 4, 5, 6 };

/* 000000EC-000001FC       .text hand_draw__FP11sitem_class */
void hand_draw(sitem_class* i_this) {
    J3DModel* model = i_this->mpModel;
    if (i_this->m2C0 < 6) {
        g_env_light.setLightTevColorType(model, &i_this->tevStr);
        mDoExt_modelUpdateDL(model);
    }
    i_this->mLineMat1.update(0xA, (GXColor){0xFF, 0xFF, 0xFF, 0xFF}, &i_this->tevStr);
    dComIfGd_set3DlineMat(&i_this->mLineMat1);
    if (i_this->mHandPos.z > 0.1f) {
        i_this->mLineMat2.update(5, (GXColor){0xFF, 0xFF, 0xFF, 0xFF}, &i_this->tevStr);
        dComIfGd_set3DlineMat(&i_this->mLineMat2);
    }
}

/* 000001FC-00000248       .text daSitem_Draw__FP11sitem_class */
static BOOL daSitem_Draw(sitem_class* i_this) {
    g_env_light.settingTevStruct(TEV_TYPE_ACTOR, &i_this->eyePos, &i_this->tevStr);
    hand_draw(i_this);
    return TRUE;
}

/* 00000248-0000034C       .text hand_mtx_set__FP11sitem_class */
void hand_mtx_set(sitem_class* i_this) {
    MtxTrans(i_this->m2E0.x, i_this->m2E0.y, i_this->m2E0.z, 0);
    mDoMtx_XrotM(*calc_mtx, i_this->m2EC.x);
    mDoMtx_YrotM(*calc_mtx, i_this->m2EC.y);
    mDoMtx_XrotM(*calc_mtx, (s16)(REG12_S(1) + 0x4000));
    cXyz pos(0.0f, -60.0f + REG12_F(4), 0.0f);
    MtxPosition(&pos, &i_this->mB00);
    MtxTrans(0.0f, -50.0f + REG12_F(3), 0.0f, 1);
    PSMTXCopy(*calc_mtx, i_this->mpModel->getBaseTRMtx());
}

/* 00000388-00000410       .text control3__FP11sitem_class */
void control3(sitem_class* i_this) {
    sitem_s* item = i_this->mSitem1;
    for (int i = 0; i < 10; i++) {
        f32 scale = 0.8f + 0.1f * cM_ssin(i_this->m2BC * 0x1F4 + i * 0x64);
        item->m18 = scale * size_d[i];
        item++;
    }
}

/* 00000410-00000748       .text control1__FP11sitem_class */
void control1(sitem_class* i_this) {
    i_this->mSitem1[0].mPos = i_this->current.pos;
    mDoMtx_YrotS(*calc_mtx, i_this->current.angle.z);
    mDoMtx_XrotM(*calc_mtx, i_this->current.angle.x);
    cXyz sp3C(0.0f, 0.0f, i_this->m2FC);
    cXyz sp24;
    MtxPosition(&sp3C, &sp24);
    sp3C.z = i_this->m2F4;
    f32 f27 = i_this->mHandPos.x;

    sitem_s* cur = &i_this->mSitem1[1];
    for (int i = 1; i < 9; i++) {
        cXyz sp30;
        sp30.x = f27 * cM_ssin(i_this->m2BC * (REG0_S(5) + 0x44C) + i * (REG0_S(6) + 0xFA0));
        sp30.y = g_d[i];
        sp30.z = f27 * cM_scos(i_this->m2BC * (REG0_S(7) + 0x320) + i * (REG0_S(8) + 0xFA0));
        cXyz sp18;
        MtxPosition(&sp30, &sp18);
        f32 f29 = sp18.x * 1.0f + ((cur->mPos.x - (cur - 1)->mPos.x) + sp24.x * 1.0f);
        f32 f28 = sp18.y * 1.0f + ((cur->mPos.y - (cur - 1)->mPos.y) + sp24.y * 1.0f);
        f32 f26 = sp18.z * 1.0f + ((cur->mPos.z - (cur - 1)->mPos.z) + sp24.z * 1.0f);
        s16 yrot = cM_atan2s(f29, f26);
        f32 dist = std::sqrtf(f29 * f29 + f26 * f26);
        s16 xrot = (s16)-cM_atan2s(f28, dist);
        MtxPush();
        mDoMtx_YrotS(*calc_mtx, yrot);
        mDoMtx_XrotM(*calc_mtx, xrot);
        MtxPosition(&sp3C, &sp30);
        MtxPull();
        cXyz spC = (cur - 1)->mPos + sp30;
        cur->mPos = spC;
        cur++;
    }
}

/* 00000748-000009E8       .text control2__FP11sitem_class */
void control2(sitem_class* i_this) {
    cXyz sp34(0.0f, 0.0f, i_this->m2F4);
    i_this->mSitem1[9].mPos = i_this->mHomePos;

    sitem_s* cur = &i_this->mSitem1[8];
    for (int i = 8; i >= 1; i--) {
        f32 x = cur->mPos.x - (cur - 1)->mPos.x;
        f32 y = cur->mPos.y - (cur - 1)->mPos.y;
        f32 z = cur->mPos.z - (cur - 1)->mPos.z;
        s16 yrot = cM_atan2s(x, z);
        f32 dist = std::sqrtf(x * x + z * z);
        s16 xrot = (s16)-cM_atan2s(y, dist);
        mDoMtx_YrotS(*calc_mtx, yrot);
        mDoMtx_XrotM(*calc_mtx, xrot);
        sp34.z = i_this->m2F4;
        cXyz sp28;
        MtxPosition(&sp34, &sp28);
        cXyz sp1C = (cur - 1)->mPos + sp28;
        cur->mPos = sp1C;
        cur--;
    }

    i_this->m2E0 = i_this->mSitem1[9].mPos;
    cXyz sp10 = i_this->mSitem1[8].mPos - i_this->mSitem1[9].mPos;
    i_this->m2EC.x = (s16)-cM_atan2s(sp10.y, sp10.z);
    f32 dist = std::sqrtf(sp10.y * sp10.y + sp10.z * sp10.z);
    i_this->m2EC.y = cM_atan2s(sp10.x, dist);
    hand_mtx_set(i_this);
}

/* 000009E8-00000E2C       .text cut_control1__FP11sitem_class */
void cut_control1(sitem_class* i_this) {
    i_this->mSitem2[0].mPos = i_this->current.pos;
    mDoMtx_YrotS(*calc_mtx, i_this->current.angle.z);
    mDoMtx_XrotM(*calc_mtx, i_this->current.angle.x);
    cXyz sp50(0.0f, 0.0f, i_this->mHandPos.z);
    f32 f28 = 50.0f + REG0_F(18);

    sitem_s* cur = &i_this->mSitem2[1];
    for (int i = 1; i < 5; i++) {
        cXyz sp44;
        sp44.x = f28 * cM_ssin(i_this->m2BC * (REG0_S(5) + 0x1004) + i * (REG0_S(6) + 0x2710));
        sp44.y = 50.0f + REG0_F(17);
        sp44.z = f28 * cM_scos(i_this->m2BC * (REG0_S(7) + 0x1130) + i * (REG0_S(8) + 0x2710));
        cXyz sp38;
        MtxPosition(&sp44, &sp38);
        f32 x = sp38.x + (cur->mPos.x - (cur - 1)->mPos.x);
        f32 y = sp38.y + (cur->mPos.y - (cur - 1)->mPos.y);
        f32 z = sp38.z + (cur->mPos.z - (cur - 1)->mPos.z);
        s16 yrot = cM_atan2s(x, z);
        f32 dist = std::sqrtf(x * x + z * z);
        s16 xrot = (s16)-cM_atan2s(y, dist);
        MtxPush();
        mDoMtx_YrotS(*calc_mtx, yrot);
        mDoMtx_XrotM(*calc_mtx, xrot);
        MtxPosition(&sp50, &sp44);
        MtxPull();
        cXyz sp2C = (cur - 1)->mPos + sp44;
        cur->mPos = sp2C;
        cur++;
    }

    if (i_this->mFollow[0].getEmitter() == NULL && i_this->mD4C != 0) {
        i_this->mFollow[0].end();
        dComIfGp_particle_set(0x8184, &i_this->mSitem2[4].mPos, &i_this->mCSxyz[0], NULL, 0xFF, &i_this->mFollow[0],
                              fopAcM_GetRoomNo(i_this));
        i_this->m2C6 = 0x3C;
        return;
    }

    cXyz sp20 = i_this->mSitem2[4].mPos - i_this->mSitem2[3].mPos;
    i_this->mCSxyz[0].y = cM_atan2s(sp20.x, sp20.z);
    f32 dist = std::sqrtf(sp20.x * sp20.x + sp20.z * sp20.z);
    i_this->mCSxyz[0].x = (s16)-cM_atan2s(sp20.y, dist);
    if (i_this->m2C6 == 1 && i_this->mFollow[0].getEmitter() != NULL) {
        i_this->mFollow[0].end();
    }
}

/* 00000E2C-00001058       .text my_break__FP11sitem_class */
void my_break(sitem_class* i_this) {
    i_this->m2C2[0] = 0x32;
    i_this->m2C0 = 6;
    csXyz angle(0, i_this->current.angle.y, 0);
    fopAcM_createItemFromTable(&i_this->mHomePos, i_this->m2BB, i_this->m2BA & 0x7F,
                               i_this->home.roomNo, 0, &angle, 1, NULL);

    if (i_this->mType <= 1) {
        dComIfGp_particle_set(0x8168, &i_this->mHomePos, NULL, NULL, 0xFF, NULL, -1);
        dComIfGp_particle_set(0x8167, &i_this->mHomePos, NULL, NULL, 0xFF, NULL, -1,
                              &i_this->tevStr.mColorK0, &i_this->tevStr.mColorK0);
        if (i_this->mType == 1) {
            dComIfGp_particle_set(0x8169, &i_this->mHomePos, NULL, NULL, 0xFF, NULL, -1,
                                  &i_this->tevStr.mColorK0, &i_this->tevStr.mColorK0);
        }
    }
    if (i_this->mType == 2) {
        dComIfGp_particle_set(0x816A, &i_this->mHomePos, NULL, NULL, 0xFF, NULL, -1,
                              &i_this->tevStr.mColorK0, &i_this->tevStr.mColorK0);
    }

    JAIZelBasic::zel_basic->seStart(JA_SE_OBJ_BREAK_CHAIR, &i_this->eyePos, 0,
                                    dComIfGp_getReverb(i_this->current.roomNo), 1.0f, 1.0f, -1.0f, -1.0f, 0);
    fopAcM_create(0x1D9, 4, &i_this->mHomePos, -1, NULL, NULL, -1, NULL);
}

/* 00001094-000015C0       .text cut_control2__FP11sitem_class */
void cut_control2(sitem_class* i_this) {
    cXyz sp60(0.0f, 0.0f, i_this->m2F4);
    i_this->mSitem1[9].mPos = i_this->mHomePos;

    sitem_s* cur = &i_this->mSitem1[8];
    f32 f27 = i_this->mHandPos.x;
    for (int i = 8; i >= 0; i--) {
        f32 sin1 = f27 * cM_ssin(i_this->m2BC * (REG0_S(5) + 0x9C4) + i * (REG0_S(6) + 0xBB8));
        f32 sin2 = f27 * cM_ssin(i_this->m2BC * (REG0_S(5) + 0xB86) + i * (REG0_S(6) + 0xFA0));
        f32 cos1 = f27 * cM_scos(i_this->m2BC * (REG0_S(7) + 0xAF0) + i * (REG0_S(8) + 0xDAC));
        f32 x = sin1 + (cur->mPos.x - (cur - 1)->mPos.x);
        f32 y = (cur->mPos.y - 10.0f) + sin2;
        f32 limit = 5.0f + i_this->mHandPos.y;
        if (y < limit) {
            y = limit;
        }
        f32 y2 = y - (cur - 1)->mPos.y;
        f32 z = cos1 + (cur->mPos.z - (cur - 1)->mPos.z);
        s16 yrot = cM_atan2s(x, z);
        f32 dist = std::sqrtf(x * x + z * z);
        s16 xrot = (s16)-cM_atan2s(y2, dist);
        mDoMtx_YrotS(*calc_mtx, yrot);
        mDoMtx_XrotM(*calc_mtx, xrot);
        sp60.z = i_this->m2F4;
        cXyz sp54;
        MtxPosition(&sp60, &sp54);
        cXyz sp3C = (cur - 1)->mPos + sp54;
        cur->mPos = sp3C;
        cur--;
    }

    i_this->m2E0 = i_this->mSitem1[9].mPos;
    cXyz sp30 = i_this->mSitem1[8].mPos - i_this->mSitem1[9].mPos;
    i_this->m2EC.x = (s16)-cM_atan2s(sp30.y, sp30.z);
    f32 dist = std::sqrtf(sp30.y * sp30.y + sp30.z * sp30.z);
    i_this->m2EC.y = cM_atan2s(sp30.x, dist);
    hand_mtx_set(i_this);

    if (i_this->mFollow[1].getEmitter() == NULL && i_this->mD4C != 0) {
        i_this->mFollow[1].end();
        dComIfGp_particle_set(0x8184, &i_this->mSitem1[0].mPos, &i_this->mCSxyz[1], NULL, 0xFF,
                              &i_this->mFollow[1], fopAcM_GetRoomNo(i_this));
        return;
    }

    cXyz sp24 = i_this->mSitem1[0].mPos - i_this->mHomePos;
    i_this->mCSxyz[1].y = cM_atan2s(sp24.x, sp24.z);
    f32 dist2 = std::sqrtf(sp24.x * sp24.x + sp24.z * sp24.z);
    i_this->mCSxyz[1].x = (s16)-cM_atan2s(sp24.y, dist2);
    if (i_this->m2C6 == 1 && i_this->mFollow[1].getEmitter() != NULL) {
        i_this->mFollow[1].end();
        i_this->mD4C = 0;
    }
}

/* 000015C0-00002304       .text hand_move__FP11sitem_class */
void hand_move(sitem_class*) {
    /* Nonmatching */
}

/* 00002684-000026F4       .text daSitem_Execute__FP11sitem_class */
static BOOL daSitem_Execute(sitem_class* i_this) {
    i_this->m2BC += 1;
    for (int i = 0; i < 2; i++) {
        if (i_this->m2C2[i] != 0) {
            i_this->m2C2[i]--;
        }
    }
    if (i_this->m2C6 != 0) {
        i_this->m2C6--;
    }
    hand_move(i_this);
    return TRUE;
}

/* 000026F4-000026FC       .text daSitem_IsDelete__FP11sitem_class */
static BOOL daSitem_IsDelete(sitem_class*) {
    return TRUE;
}

/* 000026FC-00002760       .text daSitem_Delete__FP11sitem_class */
static BOOL daSitem_Delete(sitem_class* i_this) {
    dComIfG_resDelete(&i_this->mPhs, "Sitem");
    i_this->mFollow[0].end();
    i_this->mFollow[1].end();
    return TRUE;
}

/* 00002760-00002824       .text useHeapInit__FP11sitem_class */
static BOOL useHeapInit(sitem_class* i_this) {
    i_this->mpModel = mDoExt_J3DModel__create(
        (J3DModelData*)dComIfG_getObjectRes("Sitem", bmd_data[i_this->mType]), 0, 0x11020203);
    if (i_this->mpModel == NULL) {
        return FALSE;
    }
    if (i_this->mLineMat1.init(1, 0xA, 1) == 0) {
        return FALSE;
    }
    return i_this->mLineMat2.init(1, 5, 1) != 0;
}

/* 00002824-00002844       .text daSitem_solidHeapCB__FP10fopAc_ac_c */
static BOOL daSitem_solidHeapCB(fopAc_ac_c* a_this) {
    return useHeapInit((sitem_class*)a_this);
}

/* 00002844-00002C04       .text daSitem_Create__FP10fopAc_ac_c */
static cPhs_State daSitem_Create(fopAc_ac_c*) {
    /* Nonmatching */
    static dCcD_SrcSph tg_sph_src = {
        // dCcD_SrcGObjInf
        {
            /* Flags             */ 0,
            /* SrcObjAt  Type    */ AT_TYPE_UNK800,
            /* SrcObjAt  Atp     */ 0,
            /* SrcObjAt  SPrm    */ cCcD_AtSPrm_Set_e | cCcD_AtSPrm_VsPlayer_e,
            /* SrcObjTg  Type    */ AT_TYPE_ALL & ~AT_TYPE_BOOMERANG & ~AT_TYPE_WATER & ~AT_TYPE_UNK20000 & ~AT_TYPE_WIND & ~AT_TYPE_UNK400000 & ~AT_TYPE_LIGHT,
            /* SrcObjTg  SPrm    */ cCcD_TgSPrm_Set_e | cCcD_TgSPrm_IsEnemy_e,
            /* SrcObjCo  SPrm    */ cCcD_CoSPrm_Set_e | cCcD_CoSPrm_IsPlayer_e | cCcD_CoSPrm_VsGrpAll_e,
            /* SrcGObjAt Se      */ 0,
            /* SrcGObjAt HitMark */ dCcG_AtHitMark_None_e,
            /* SrcGObjAt Spl     */ dCcG_At_Spl_UNK0,
            /* SrcGObjAt Mtrl    */ 0,
            /* SrcGObjAt SPrm    */ 0,
            /* SrcGObjTg Se      */ 0,
            /* SrcGObjTg HitMark */ 0,
            /* SrcGObjTg Spl     */ dCcG_Tg_Spl_UNK0,
            /* SrcGObjTg Mtrl    */ 0,
            /* SrcGObjTg SPrm    */ dCcG_TgSPrm_NoConHit_e,
            /* SrcGObjCo SPrm    */ 0,
        },
        // cM3dGSphS
        {{
            /* Center */ {0.0f, 0.0f, 0.0f},
            /* Radius */ 20.0f,
        }},
    };
    static dCcD_SrcSph bm_sph_src = {
        // dCcD_SrcGObjInf
        {
            /* Flags             */ 0,
            /* SrcObjAt  Type    */ 0,
            /* SrcObjAt  Atp     */ 0,
            /* SrcObjAt  SPrm    */ 0,
            /* SrcObjTg  Type    */ AT_TYPE_BOOMERANG | AT_TYPE_WIND,
            /* SrcObjTg  SPrm    */ cCcD_TgSPrm_Set_e | cCcD_TgSPrm_IsEnemy_e,
            /* SrcObjCo  SPrm    */ 0,
            /* SrcGObjAt Se      */ 0,
            /* SrcGObjAt HitMark */ dCcG_AtHitMark_None_e,
            /* SrcGObjAt Spl     */ dCcG_At_Spl_UNK0,
            /* SrcGObjAt Mtrl    */ 0,
            /* SrcGObjAt SPrm    */ 0,
            /* SrcGObjTg Se      */ 0,
            /* SrcGObjTg HitMark */ 0,
            /* SrcGObjTg Spl     */ dCcG_Tg_Spl_UNK0,
            /* SrcGObjTg Mtrl    */ 0,
            /* SrcGObjTg SPrm    */ dCcG_TgSPrm_NoConHit_e,
            /* SrcGObjCo SPrm    */ 0,
        },
        // cM3dGSphS
        {{
            /* Center */ {0.0f, 0.0f, 0.0f},
            /* Radius */ 80.0f,
        }},
    };
}

static actor_method_class l_daSitem_Method = {
    (process_method_func)daSitem_Create,
    (process_method_func)daSitem_Delete,
    (process_method_func)daSitem_Execute,
    (process_method_func)daSitem_IsDelete,
    (process_method_func)daSitem_Draw,
};

actor_process_profile_definition g_profile_SITEM = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_SITEM_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(sitem_class),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_SITEM_e,
    /* Actor SubMtd */ &l_daSitem_Method,
    /* Status       */ fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ENEMY_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
