//
// Generated by dtk
// Translation Unit: d_a_grid.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/actor/d_a_grid.h"
#include "d/actor/d_a_ship.h"
#include "d/d_camera.h"
#include "d/d_kankyo_wether.h"
#include "d/d_s_play.h"
#include "f_op/f_op_camera.h"
#include "m_Do/m_Do_graphic.h"
#include "JSystem/J3DGraphBase/J3DPacket.h"

daShip_c* l_ship;

struct l_pos_t {
    /* 0x00 */ f32 m00;
    /* 0x04 */ f32 mX;
    /* 0x08 */ f32 mZ;
};

static l_pos_t l_pos[0x55] = {
    { 0.0f, 5.0f, 0.0f },
    { 0.0f, 5.0f, -48.33332061767578f },
    { 0.0f, 5.0f, -96.66665649414062f },
    { 0.0f, 5.0f, -145.0f },
    { 0.0f, 5.0f, -193.3333282470703f },
    { 0.0f, 5.0f, -241.66665649414062f },
    { 0.0f, 5.0f, -290.0f },
    { 0.0f, 35.0f, 0.0f },
    { 0.0f, 35.55553436279297f, -46.13637161254883f },
    { 0.0f, 36.111106872558594f, -92.2727279663086f },
    { 0.0f, 36.66666030883789f, -138.4091033935547f },
    { 0.0f, 37.22221374511719f, -184.5454559326172f },
    { 0.0f, 37.777767181396484f, -230.68182373046875f },
    { 0.0f, 38.33332061767578f, -276.81817626953125f },
    { 0.0f, 65.0f, 0.0f },
    { 0.0f, 66.1111068725586f, -43.93940353393555f },
    { 0.0f, 67.22221374511719f, -87.87879180908203f },
    { 0.0f, 68.33332061767578f, -131.81817626953125f },
    { 0.0f, 69.44442749023438f, -175.75758361816406f },
    { 0.0f, 70.55553436279297f, -219.6969757080078f },
    { 0.0f, 71.66665649414062f, -263.6363525390625f },
    { 0.0f, 95.0f, 0.0f },
    { 0.0f, 96.66665649414062f, -41.742435455322266f },
    { 0.0f, 98.33332061767578f, -83.48485565185547f },
    { 0.0f, 100.0f, -125.22727966308594f },
    { 0.0f, 101.66665649414062f, -166.96969604492188f },
    { 0.0f, 103.33332061767578f, -208.71212768554688f },
    { 0.0f, 105.0f, -250.45452880859375f },
    { 0.0f, 125.0f, 0.0f },
    { 0.0f, 127.22221374511719f, -39.54545211791992f },
    { 0.0f, 129.44444274902344f, -79.0909194946289f },
    { 0.0f, 131.6666717529297f, -118.63636779785156f },
    { 0.0f, 133.88888549804688f, -158.1818084716797f },
    { 0.0f, 136.11111450195312f, -197.72726440429688f },
    { 0.0f, 138.33334350585938f, -237.27272033691406f },
    { 0.0f, 155.0f, 0.0f },
    { 0.0f, 157.7777862548828f, -37.34848403930664f },
    { 0.0f, 160.55557250976562f, -74.69696807861328f },
    { 0.0f, 163.33335876464844f, -112.04544830322266f },
    { 0.0f, 166.11111450195312f, -149.39393615722656f },
    { 0.0f, 168.88888549804688f, -186.74241638183594f },
    { 0.0f, 171.6666717529297f, -224.0908966064453f },
    { 0.0f, 185.0f, 0.0f },
    { 0.0f, 188.3333282470703f, -35.15151596069336f },
    { 0.0f, 191.66664123535156f, -70.30303192138672f },
    { 0.0f, 195.0f, -105.45455169677734f },
    { 0.0f, 198.3333282470703f, -140.60606384277344f },
    { 0.0f, 201.66664123535156f, -175.757568359375f },
    { 0.0f, 205.0f, -210.90908813476562f },
    { 0.0f, 215.0f, 0.0f },
    { 0.0f, 218.88885498046875f, -32.95454788208008f },
    { 0.0f, 222.77774047851562f, -65.90909576416016f },
    { 0.0f, 226.66664123535156f, -98.86363220214844f },
    { 0.0f, 230.55552673339844f, -131.81817626953125f },
    { 0.0f, 234.44442749023438f, -164.77273559570312f },
    { 0.0f, 238.3333282470703f, -197.72726440429688f },
    { 0.0f, 245.0f, 0.0f },
    { 0.0f, 249.44442749023438f, -30.757579803466797f },
    { 0.0f, 253.88885498046875f, -61.515159606933594f },
    { 0.0f, 258.33331298828125f, -92.2727279663086f },
    { 0.0f, 262.77777099609375f, -123.03030395507812f },
    { 0.0f, 267.22222900390625f, -153.7878875732422f },
    { 0.0f, 271.6666259765625f, -184.5454559326172f },
    { 0.0f, 275.0f, 0.0f },
    { 0.0f, 279.27081298828125f, -23.06818389892578f },
    { 0.0f, 282.6041259765625f, -46.13637161254883f },
    { 0.0f, 285.9375f, -69.20454406738281f },
    { 0.0f, 289.2708740234375f, -92.2727279663086f },
    { 0.0f, 292.6041259765625f, -115.34091186523438f },
    { 0.0f, 295.9375f, -138.40908813476562f },
    { 0.0f, 306.25f, 0.0f },
    { 0.0f, 309.09722900390625f, -15.378789901733398f },
    { 0.0f, 311.3194274902344f, -30.757579803466797f },
    { 0.0f, 313.5416259765625f, -46.1363639831543f },
    { 0.0f, 315.7638854980469f, -61.51515197753906f },
    { 0.0f, 317.9861145019531f, -76.8939437866211f },
    { 0.0f, 320.20831298828125f, -92.2727279663086f },
    { 0.0f, 337.5f, 0.0f },
    { 0.0f, 338.9236145019531f, -7.689395904541016f },
    { 0.0f, 340.03472900390625f, -15.378789901733398f },
    { 0.0f, 341.14581298828125f, -23.068180084228516f },
    { 0.0f, 342.2569274902344f, -30.75757598876953f },
    { 0.0f, 343.3680725097656f, -38.44697189331055f },
    { 0.0f, 344.4791259765625f, -46.1363639831543f },
    { 0.0f, 368.75f, 0.0f },
};

static daHo_HIO_c l_HIO;

// .data:0x414
static f32 l_texCoord[0xAA] __attribute__((aligned(4))) = {
    0.6416900157928467f, 0.5486739873886108f, 0.723721981048584f, 0.4509499967098236f,
    0.7684659957885742f, 0.5411570072174072f, 0.8579540252685547f, 0.7215690016746521f,
    0.9026989936828613f, 0.8117750287055969f, 0.7535510063171387f, 0.8147820234298706f,
    0.13831700384616852f, 0.07650099694728851f, 0.007813000120222569f, 0.007813000120222569f,
    0.16441799700260162f, 0.07349400222301483f, 0.9474430084228516f, 0.901980996131897f,
    0.9921870231628418f, 0.9921870231628418f, 0.828125f, 0.9921870231628418f,
    0.716264009475708f, 0.726078987121582f, 0.8132100105285645f, 0.6313629746437073f,
    0.604403018951416f, 0.45997101068496704f, 0.6789770126342773f, 0.36074399948120117f,
    0.08611500263214111f, 0.08251500129699707f, 0.06001399829983711f, 0.08552200347185135f,
    0.24644899368286133f, 0.48703300952911377f, 0.3433949947357178f, 0.392316997051239f,
    0.3657670021057129f, 0.47801199555397034f, 0.26136401295661926f, 0.5712249875068665f,
    0.388139009475708f, 0.5637080073356628f, 0.29119300842285156f, 0.7396100163459778f,
    0.41051098704338074f, 0.649403989315033f, 0.43288400769233704f, 0.7350999712944031f,
    0.45525598526000977f, 0.820796012878418f, 0.3061079978942871f, 0.8238019943237305f,
    0.4776279926300049f, 0.9064909815788269f, 0.5f, 0.9921870231628418f,
    0.3359380066394806f, 0.9921870231628418f, 0.033913999795913696f, 0.08852799981832504f,
    0.007813000120222569f, 0.09238100051879883f, 0.007813000120222569f, 0.5050740242004395f,
    0.11967399716377258f, 0.4133650064468384f, 0.12713100016117096f, 0.4960539937019348f,
    0.007813000120222569f, 0.5862600207328796f, 0.13458800315856934f, 0.5787420272827148f,
    0.007813000120222569f, 0.7486310005187988f, 0.1420460045337677f, 0.6614310145378113f,
    0.14950299263000488f, 0.7441200017929077f, 0.15695999562740326f, 0.8268089890480042f,
    0.007813000120222569f, 0.8298159837722778f, 0.16441799700260162f, 0.9094979763031006f,
    0.171875f, 0.9921870231628418f, 0.007813000120222569f, 0.9921870231628418f,
    0.11221600323915482f, 0.07950799912214279f, 0.45525598526000977f, 0.38179200887680054f,
    0.48508501052856445f, 0.4689919948577881f, 0.5149149894714355f, 0.5561910271644592f,
    0.5447440147399902f, 0.6433899998664856f, 0.5745739936828613f, 0.730588972568512f,
    0.604403018951416f, 0.8177890181541443f, 0.6342329978942871f, 0.9049879908561707f,
    0.6640620231628418f, 0.9921870231628418f, 0.007813000120222569f, 0.42388901114463806f,
    0.11221600323915482f, 0.33067598938941956f, 0.23153400421142578f, 0.4028399884700775f,
    0.32102298736572266f, 0.3066209852695465f, 0.42542600631713867f, 0.2945930063724518f,
    0.5671160221099854f, 0.37126800417900085f, 0.6342329978942871f, 0.27053800225257874f,
    0.007813000120222569f, 0.6674450039863586f, 0.2762790024280548f, 0.6554179787635803f,
    0.6789770126342773f, 0.6373760104179382f, 0.007813000120222569f, 0.911001980304718f,
    0.32102298736572266f, 0.9079949855804443f, 0.7908380031585693f, 0.9034850001335144f,
    0.21661899983882904f, 0.31864801049232483f, 0.5298299789428711f, 0.28256601095199585f,
    0.08611500263214111f, 0.2499600052833557f, 0.007813000120222569f, 0.2615169882774353f,
    0.06001399829983711f, 0.16924400627613068f, 0.16441799700260162f, 0.24093900620937347f,
    0.11221600323915482f, 0.16323000192642212f, 0.24271999299526215f, 0.23191900551319122f,
    0.16441799700260162f, 0.15721699595451355f, 0.32102298736572266f, 0.22289800643920898f,
    0.21661899983882904f, 0.1512030065059662f, 0.39932501316070557f, 0.21387700736522675f,
    0.26882100105285645f, 0.14518900215625763f, 0.32102298736572266f, 0.13917499780654907f,
    0.4776279926300049f, 0.2048570066690445f, 0.007813000120222569f, 0.17694899439811707f,
    0.007813000120222569f, 0.3427030146121979f,
};

// .data:0x6C0 (global in retail)
u8 l_DL[0x233] __attribute__((aligned(32))) = {
    0x98, 0x00, 0x22, 0x06, 0x06, 0x0A, 0x05, 0x05, 0x0B, 0x0D, 0x0D, 0x09, 0x0C, 0x0C, 0x43, 0x14,
    0x14, 0x04, 0x13, 0x13, 0x05, 0x1B, 0x1B, 0x03, 0x1A, 0x1A, 0x0C, 0x22, 0x22, 0x0D, 0x21, 0x21,
    0x40, 0x29, 0x29, 0x02, 0x28, 0x28, 0x00, 0x30, 0x30, 0x01, 0x2F, 0x2F, 0x0E, 0x37, 0x37, 0x0F,
    0x36, 0x36, 0x3C, 0x3E, 0x3E, 0x3D, 0x3D, 0x3D, 0x45, 0x45, 0x45, 0x52, 0x44, 0x44, 0x4F, 0x4C,
    0x4C, 0x51, 0x4B, 0x4B, 0x50, 0x53, 0x53, 0x08, 0x52, 0x52, 0x06, 0x54, 0x54, 0x07, 0x51, 0x51,
    0x2E, 0x50, 0x50, 0x10, 0x49, 0x49, 0x4C, 0x48, 0x48, 0x4A, 0x41, 0x41, 0x49, 0x40, 0x40, 0x46,
    0x39, 0x39, 0x38, 0x38, 0x38, 0x54, 0x31, 0x31, 0x37, 0x98, 0x00, 0x18, 0x05, 0x05, 0x0B, 0x04,
    0x04, 0x36, 0x0C, 0x0C, 0x43, 0x0B, 0x0B, 0x35, 0x13, 0x13, 0x05, 0x12, 0x12, 0x34, 0x1A, 0x1A,
    0x0C, 0x19, 0x19, 0x33, 0x21, 0x21, 0x40, 0x20, 0x20, 0x32, 0x28, 0x28, 0x00, 0x27, 0x27, 0x31,
    0x2F, 0x2F, 0x0E, 0x2E, 0x2E, 0x30, 0x36, 0x36, 0x3C, 0x35, 0x35, 0x2F, 0x3D, 0x3D, 0x45, 0x3C,
    0x3C, 0x3B, 0x44, 0x44, 0x4F, 0x43, 0x43, 0x4D, 0x4B, 0x4B, 0x50, 0x4A, 0x4A, 0x4E, 0x52, 0x52,
    0x06, 0x51, 0x51, 0x2E, 0x98, 0x00, 0x0F, 0x04, 0x04, 0x36, 0x03, 0x03, 0x1D, 0x0B, 0x0B, 0x35,
    0x0A, 0x0A, 0x1C, 0x12, 0x12, 0x34, 0x11, 0x11, 0x1A, 0x19, 0x19, 0x33, 0x18, 0x18, 0x19, 0x20,
    0x20, 0x32, 0x1F, 0x1F, 0x18, 0x27, 0x27, 0x31, 0x26, 0x26, 0x16, 0x2E, 0x2E, 0x30, 0x2D, 0x2D,
    0x14, 0x35, 0x35, 0x2F, 0x98, 0x00, 0x0D, 0x03, 0x03, 0x1D, 0x02, 0x02, 0x1E, 0x0A, 0x0A, 0x1C,
    0x09, 0x09, 0x42, 0x11, 0x11, 0x1A, 0x10, 0x10, 0x1B, 0x18, 0x18, 0x19, 0x17, 0x17, 0x17, 0x1F,
    0x1F, 0x18, 0x1E, 0x1E, 0x3F, 0x26, 0x26, 0x16, 0x25, 0x25, 0x15, 0x2D, 0x2D, 0x14, 0x98, 0x00,
    0x0B, 0x02, 0x02, 0x1E, 0x01, 0x01, 0x2C, 0x09, 0x09, 0x42, 0x08, 0x08, 0x2B, 0x10, 0x10, 0x1B,
    0x0F, 0x0F, 0x29, 0x17, 0x17, 0x17, 0x16, 0x16, 0x28, 0x1E, 0x1E, 0x3F, 0x1D, 0x1D, 0x27, 0x25,
    0x25, 0x15, 0x98, 0x00, 0x0A, 0x51, 0x51, 0x2E, 0x4A, 0x4A, 0x4E, 0x49, 0x49, 0x4C, 0x42, 0x42,
    0x4B, 0x41, 0x41, 0x49, 0x3A, 0x3A, 0x44, 0x39, 0x39, 0x38, 0x32, 0x32, 0x22, 0x31, 0x31, 0x37,
    0x2A, 0x2A, 0x21, 0x98, 0x00, 0x0A, 0x4A, 0x4A, 0x4E, 0x43, 0x43, 0x4D, 0x42, 0x42, 0x4B, 0x3B,
    0x3B, 0x3A, 0x3A, 0x3A, 0x44, 0x33, 0x33, 0x39, 0x32, 0x32, 0x22, 0x2B, 0x2B, 0x23, 0x2A, 0x2A,
    0x21, 0x23, 0x23, 0x24, 0x98, 0x00, 0x0A, 0x43, 0x43, 0x4D, 0x3C, 0x3C, 0x3B, 0x3B, 0x3B, 0x3A,
    0x34, 0x34, 0x13, 0x33, 0x33, 0x39, 0x2C, 0x2C, 0x12, 0x2B, 0x2B, 0x23, 0x24, 0x24, 0x25, 0x23,
    0x23, 0x24, 0x1C, 0x1C, 0x3E, 0x98, 0x00, 0x0A, 0x3C, 0x3C, 0x3B, 0x35, 0x35, 0x2F, 0x34, 0x34,
    0x13, 0x2D, 0x2D, 0x14, 0x2C, 0x2C, 0x12, 0x25, 0x25, 0x15, 0x24, 0x24, 0x25, 0x1D, 0x1D, 0x27,
    0x1C, 0x1C, 0x3E, 0x15, 0x15, 0x26, 0x98, 0x00, 0x09, 0x01, 0x01, 0x2C, 0x00, 0x00, 0x2D, 0x08,
    0x08, 0x2B, 0x07, 0x07, 0x41, 0x0F, 0x0F, 0x29, 0x0E, 0x0E, 0x2A, 0x16, 0x16, 0x28, 0x15, 0x15,
    0x26, 0x1D, 0x1D, 0x27, 0x98, 0x00, 0x08, 0x38, 0x38, 0x54, 0x3F, 0x3F, 0x47, 0x40, 0x40, 0x46,
    0x47, 0x47, 0x48, 0x48, 0x48, 0x4A, 0x4F, 0x4F, 0x11, 0x50, 0x50, 0x10, 0x54, 0x54, 0x07, 0x98,
    0x00, 0x06, 0x3F, 0x3F, 0x47, 0x46, 0x46, 0x53, 0x47, 0x47, 0x48, 0x4E, 0x4E, 0x1F, 0x4F, 0x4F,
    0x11, 0x54, 0x54, 0x07, 0x98, 0x00, 0x04, 0x46, 0x46, 0x53, 0x4D, 0x4D, 0x20, 0x4E, 0x4E, 0x1F,
    0x54, 0x54, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00,
};

// .data:0x900
static u8 l_matDL[0x34] __attribute__((aligned(32))) = {
    0x61, 0x43, 0x00, 0x00, 0x41, 0x61, 0x40, 0x00, 0x00, 0x17, 0x61, 0x41, 0x00, 0x04, 0xAD, 0x61,
    0xF3, 0x7F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};

static f32 z_rate_tbl[13] = {
    0.05f, 0.125f, 0.175f, 0.15f, 0.0625f, 0.15f, 0.2f, 0.15f, 0.075f, 0.175f, 0.175f, 0.1f, 0.0f,
};

static f32 z_rate_tbl2[13] = {
    1.0f, 0.425f, 0.45f, 0.4f, 0.2f, 0.4f, 0.45f, 0.4f, 0.2f, 0.5f, 0.75f, 1.0f, 1.0f,
};

static f32 x_rate_tbl[13] = {
    1.0f, 0.95f, 0.9f, 0.85f, 0.8f, 0.75f, 0.7f, 0.65f, 0.55f, 0.4f, 0.25f, 0.1f, 0.0f,
};

/* 800EB4D0-800EB520       .text __dt__10daHo_HIO_cFv */
daHo_HIO_c::~daHo_HIO_c() {
    mChildId = -1;
}

/* 800EB520-800EB5D8       .text __dt__13daHo_packet_cFv */
daHo_packet_c::~daHo_packet_c() {}

/* 800E8CC0-800E8D48       .text setBackNrm__13daHo_packet_cFv */
void daHo_packet_c::setBackNrm() {
    /* Nonmatching */
    cXyz* nrm = mNrm2[mCount];
    cXyz* pos = mPos[mCount];
    for (s32 i = 0; i < 0x55; i++) {
        pos->set(0.0f, 0.0f, 0.0f);
        PSVECSubtract(pos, nrm, pos);
        nrm++;
        pos++;
    }
}

/* 800E8D48-800E8D74       .text setNrmMtx__13daHo_packet_cFR4cXyz */
void daHo_packet_c::setNrmMtx(cXyz&) {
    mDoMtx_YrotS(*calc_mtx, m189C);
}

/* 800E8D74-800E92AC       .text setNrmVtx__13daHo_packet_cFP4cXyzii */
void daHo_packet_c::setNrmVtx(cXyz* out, int col, int row) {
    /* Nonmatching */
    cXyz* nrm = &mNrm[mCount][0];
    cXyz cur = nrm[row * 7 + col];
    cXyz v1;
    cXyz add;
    add.set(0.0f, 0.0f, 0.0f);
    if (col != 0) {
        v1 = nrm[row * 7 + col - 1] - cur;
        if (row != 0 && row != 9) {
            cXyz v2 = nrm[col + (row - 1) * 7] - cur;
            cXyz cross = v1.outprod(v2);
            cross = cross.normZC();
            add += cross;
        }
        if (row == 0xB) {
            cXyz v2 = nrm[0x54] - cur;
            cXyz cross = v1.outprod(v2);
            cross = cross.normZC();
            add += cross;
        } else if (row != 8) {
            cXyz v2 = nrm[col + (row + 1) * 7] - cur;
            cXyz cross = v1.outprod(v2);
            cross = cross.normZC();
            add += cross;
        }
    }
    if (col != 6) {
        v1 = nrm[col + row * 7 + 1] - cur;
        if (row != 0 && row != 9) {
            cXyz v2 = nrm[col + (row - 1) * 7] - cur;
            cXyz cross = v1.outprod(v2);
            cross = cross.normZC();
            add += cross;
        }
        if (row == 0xB) {
            cXyz v2 = nrm[0x54] - cur;
            cXyz cross = v1.outprod(v2);
            cross = cross.normZC();
            add += cross;
        } else if (row != 8) {
            cXyz v2 = nrm[col + (row + 1) * 7] - cur;
            cXyz cross = v1.outprod(v2);
            cross = cross.normZC();
            add += cross;
        }
    }
    if (row > 7) {
        add.y = 0.0f;
    }
    if (add.normalizeRS() == 0) {
        add.set(1.0f, 0.0f, 0.0f);
    }
    MtxPush();
    mDoMtx_YrotM(*calc_mtx, (s16)(900.0f * cM_ssin((s16)((col + row) * -0x320))));
    cXyz pos;
    MtxPosition(&add, &pos);
    *out = pos.normZC();
    MtxPull();
}

/* 800E92AC-800E93B8       .text setTopNrmVtx__13daHo_packet_cFP4cXyz */
void daHo_packet_c::setTopNrmVtx(cXyz* out) {
    /* Nonmatching */
    cXyz* nrm = mNrm[mCount];
    cXyz v1 = nrm[0x4D] - nrm[0x54];
    cXyz v2 = nrm[0x53] - nrm[0x54];
    cXyz cross = v1.outprod(v2);
    cross = cross.normZC();
    cXyz pos;
    MtxPosition(&cross, &pos);
    *out = pos.normZC();
}

/* 800E93B8-800E9BE8       .text draw__13daHo_packet_cFv */
void daHo_packet_c::draw() {
    /* Nonmatching */
    j3dSys.reinitGX();
    GXSetNumIndStages(0);
    dKy_GxFog_tevstr_set(mpTevStr);
    GXClearVtxDesc();
    GXSetVtxDesc(GX_VA_POS, GX_INDEX8);
    GXSetVtxDesc(GX_VA_NRM, GX_INDEX8);
    GXSetVtxDesc(GX_VA_TEX0, GX_INDEX8);
    GXSetVtxAttrFmt(GX_VTXFMT0, GX_VA_POS, GX_POS_XYZ, GX_F32, 0);
    GXSetVtxAttrFmt(GX_VTXFMT0, GX_VA_NRM, GX_NRM_XYZ, GX_F32, 0);
    GXSetVtxAttrFmt(GX_VTXFMT0, GX_VA_TEX0, GX_TEX_ST, GX_F32, 0);
    GXSetArray(GX_VA_POS, &mNrm[mCount][0], sizeof(cXyz));
    GXSetArray(GX_VA_NRM, &mNrm2[mCount][0], sizeof(cXyz));
    GXSetArray(GX_VA_TEX0, l_texCoord, sizeof(cXy));

    GXTlutObj tlutObj;
    GXTexObj texObj;
    ResTIMG* img = (ResTIMG*)dComIfG_getObjectRes(&"Ship\0Cloth\0船の帆"[0], 0x17);
    GXInitTlutObj(&tlutObj, (u8*)img + img->paletteOffset, GX_TL_RGB5A3, 0x100);
    GXInitTexObjCI(&texObj, (u8*)img + img->imageOffset, img->width, img->height, (GXCITexFmt)img->format,
                   (GXTexWrapMode)img->wrapS, (GXTexWrapMode)img->wrapT, (GXBool)((u32)(1 - img->mipmapCount) >> 0x1F), 0);
    GXInitTexObjLOD(&texObj, (GXTexFilter)img->minFilter, (GXTexFilter)img->magFilter,
                    img->minLOD * 0.125f, img->maxLOD * 0.125f, img->LODBias * 0.01f,
                    img->biasClamp, img->doEdgeLOD, (GXAnisotropy)img->maxAnisotropy);
    GXLoadTlut(&tlutObj, GX_TLUT0);
    GXLoadTexObj(&texObj, GX_TEXMAP0);

    img = (ResTIMG*)dComIfG_getObjectRes(&"Ship\0Cloth\0船の帆"[5], 3);
    GXInitTexObj(&texObj, (u8*)img + img->imageOffset, img->width, img->height, (GXTexFmt)img->format,
                 (GXTexWrapMode)img->wrapS, (GXTexWrapMode)img->wrapT, (GXBool)((u32)(1 - img->mipmapCount) >> 0x1F));
    GXInitTexObjLOD(&texObj, (GXTexFilter)img->minFilter, (GXTexFilter)img->magFilter,
                    img->minLOD * 0.125f, img->maxLOD * 0.125f, img->LODBias * 0.01f,
                    img->biasClamp, img->doEdgeLOD, (GXAnisotropy)img->maxAnisotropy);
    GXLoadTexObj(&texObj, GX_TEXMAP1);

    GXSetNumChans(1);
    u8 tevStages;
    u8 lightMask;
    if (mpTevStr->mColorK1.a != 0) {
        tevStages = 3;
        lightMask = 3;
    } else {
        tevStages = 2;
        lightMask = 1;
    }
    if (l_HIO.m05 != 0) {
        GXSetChanCtrl(GX_COLOR0, GX_TRUE, GX_SRC_REG, GX_SRC_REG, lightMask, GX_DF_CLAMP, GX_AF_NONE);
        GXSetNumTexGens(2);
        GXSetTexCoordGen2(GX_TEXCOORD0, GX_TG_MTX2x4, GX_TG_TEX0, GX_IDENTITY, GX_FALSE, GX_PTIDENTITY);
        GXSetTexCoordGen2(GX_TEXCOORD1, GX_TG_SRTG, GX_TG_COLOR0, GX_IDENTITY, GX_FALSE, GX_PTIDENTITY);
        GXSetNumTevStages(tevStages);
        GXSetTevSwapMode(GX_TEVSTAGE0, GX_TEV_SWAP0, GX_TEV_SWAP1);
        GXSetTevOrder(GX_TEVSTAGE0, GX_TEXCOORD1, GX_TEXMAP1, GX_COLOR0A0);
        GXSetTevColorIn(GX_TEVSTAGE0, GX_CC_C1, GX_CC_C0, GX_CC_TEXC, GX_CC_ZERO);
        GXSetTevColorOp(GX_TEVSTAGE0, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        GXSetTevAlphaIn(GX_TEVSTAGE0, GX_CA_A1, GX_CA_A1, GX_CA_A1, GX_CA_A1);
        GXSetTevAlphaOp(GX_TEVSTAGE0, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        GXSetTevSwapMode(GX_TEVSTAGE1, GX_TEV_SWAP0, GX_TEV_SWAP0);
        GXSetTevOrder(GX_TEVSTAGE1, GX_TEXCOORD0, GX_TEXMAP0, GX_COLOR_NULL);
        GXSetTevColorIn(GX_TEVSTAGE1, GX_CC_ZERO, GX_CC_TEXC, GX_CC_CPREV, GX_CC_ZERO);
        GXSetTevColorOp(GX_TEVSTAGE1, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        GXSetTevAlphaIn(GX_TEVSTAGE1, GX_CA_ZERO, GX_CA_A0, GX_CA_TEXA, GX_CA_ZERO);
        GXSetTevAlphaOp(GX_TEVSTAGE1, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        if (tevStages == 3) {
            GXSetTevSwapMode(GX_TEVSTAGE2, GX_TEV_SWAP0, GX_TEV_SWAP2);
            GXSetTevOrder(GX_TEVSTAGE2, GX_TEXCOORD1, GX_TEXMAP1, GX_COLOR_NULL);
            GXSetTevColorIn(GX_TEVSTAGE2, GX_CC_ZERO, GX_CC_C2, GX_CC_TEXC, GX_CC_CPREV);
            GXSetTevColorOp(GX_TEVSTAGE2, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
            GXSetTevAlphaIn(GX_TEVSTAGE2, GX_CA_ZERO, GX_CA_A0, GX_CA_TEXA, GX_CA_ZERO);
            GXSetTevAlphaOp(GX_TEVSTAGE2, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        }
    } else {
        GXSetChanCtrl(GX_COLOR0, GX_TRUE, GX_SRC_REG, GX_SRC_REG, lightMask, GX_DF_CLAMP, GX_AF_NONE);
        GXSetNumTexGens(1);
        GXSetTexCoordGen2(GX_TEXCOORD0, GX_TG_MTX2x4, GX_TG_TEX0, GX_IDENTITY, GX_FALSE, GX_PTIDENTITY);
        GXSetNumTevStages(tevStages);
        GXSetTevOrder(GX_TEVSTAGE0, GX_TEXCOORD_NULL, GX_TEXMAP_DISABLE, GX_COLOR0A0);
        GXSetTevSwapMode(GX_TEVSTAGE0, GX_TEV_SWAP1, GX_TEV_SWAP0);
        GXSetTevColorIn(GX_TEVSTAGE0, GX_CC_C1, GX_CC_C0, GX_CC_RASC, GX_CC_ZERO);
        GXSetTevColorOp(GX_TEVSTAGE0, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        GXSetTevAlphaIn(GX_TEVSTAGE0, GX_CA_A1, GX_CA_A1, GX_CA_A1, GX_CA_A1);
        GXSetTevAlphaOp(GX_TEVSTAGE0, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        GXSetTevSwapMode(GX_TEVSTAGE1, GX_TEV_SWAP0, GX_TEV_SWAP0);
        GXSetTevOrder(GX_TEVSTAGE1, GX_TEXCOORD0, GX_TEXMAP0, GX_COLOR_NULL);
        GXSetTevColorIn(GX_TEVSTAGE1, GX_CC_ZERO, GX_CC_CPREV, GX_CC_TEXC, GX_CC_ZERO);
        GXSetTevColorOp(GX_TEVSTAGE1, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        GXSetTevAlphaIn(GX_TEVSTAGE1, GX_CA_ZERO, GX_CA_ZERO, GX_CA_ZERO, GX_CA_TEXA);
        GXSetTevAlphaOp(GX_TEVSTAGE1, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        if (tevStages == 3) {
            GXSetTevSwapMode(GX_TEVSTAGE2, GX_TEV_SWAP2, GX_TEV_SWAP0);
            GXSetTevOrder(GX_TEVSTAGE2, GX_TEXCOORD_NULL, GX_TEXMAP_DISABLE, GX_COLOR_NULL);
            GXSetTevColorIn(GX_TEVSTAGE2, GX_CC_ZERO, GX_CC_C2, GX_CC_RASC, GX_CC_CPREV);
            GXSetTevColorOp(GX_TEVSTAGE2, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
            GXSetTevAlphaIn(GX_TEVSTAGE2, GX_CA_ZERO, GX_CA_ZERO, GX_CA_ZERO, GX_CA_TEXA);
            GXSetTevAlphaOp(GX_TEVSTAGE2, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
        }
    }

    mpTevStr->mColorC0.a = mAlpha;
    GXColorS10 tevColorS10 = mpTevStr->mColorC0;
    GXSetTevColorS10(GX_TEVREG0, tevColorS10);
    GXColor tevColorK0 = mpTevStr->mColorK0;
    GXSetTevColor(GX_TEVREG1, tevColorK0);
    GXColor tevColorK1 = mpTevStr->mColorK1;
    GXSetTevColor(GX_TEVREG2, tevColorK1);

    GXCallDisplayList(l_matDL, 0x20);
    GXLoadPosMtxImm(mMtx, 0);
    GXLoadNrmMtxImm(mMtx, 0);
    GXSetCullMode(GX_CULL_BACK);
    GXCallDisplayList(l_DL, 0x220);
    GXSetCullMode(GX_CULL_FRONT);
    GXSetArray(GX_VA_NRM, &mPos[mCount][0], sizeof(cXyz));
    GXCallDisplayList(l_DL, 0x220);
    J3DShape::resetVcdVatCache();
}

/* 800E9BE8-800E9C0C       .text daGrid_Draw__FP8daGrid_c */
static BOOL daGrid_Draw(daGrid_c* i_this) {
    return ((daGrid_c*)i_this)->_draw();
}

/* 800E9C0C-800EA928       .text ho_move__FP8daGrid_c */
void ho_move(daGrid_c* i_this) {
    /* Nonmatching */
    if (l_HIO.m38 == 0) {
        cXyz* windVec = dKyw_get_wind_vec();
        f32 windPow = dKyw_get_wind_pow();
        i_this->mPacket.mCount ^= 1;
        i_this->mB4C = 0x1D4C;
        i_this->mB4E = 0x1C20;
        s16 shipAngle = l_ship->mSailAngle;
        s16 angle = (s16)((s16)(i_this->current.angle.y + shipAngle) - cM_atan2s(windVec->x, windVec->z));
        s16 r3 = (s16)(angle + 0x8000);
        if (r3 > 0) {
            if (shipAngle > 0 && shipAngle < 0x4000) {
                r3 = 0;
            }
        } else if (shipAngle < 0 && shipAngle > -0x4000) {
            r3 = 0;
        }
        s16 target = (s16)(0.6f * r3);
        if (i_this->m2218 == 0) {
            cLib_addCalcAngleS2(&i_this->m2210, target, 4, 0x1000);
        } else {
            cLib_addCalcAngleS2(&i_this->m2210, (s16)((i_this->m2216 - l_ship->mSailAngle) + 0x8000), 2, 0x1400);
        }
        i_this->m2218 = 0;
        mDoMtx_YrotS(*calc_mtx, i_this->m2210);

        cXyz sp34;
        cXyz sp28;
        sp34.x = 0.0f;
        sp34.y = 0.0f;
        sp34.z = 0.064f;
        MtxPosition(&sp34, &sp28);
        f32 f29 = 0.02f + std::fabsf(sp28.z);
        sp34.x = 1.0f;
        sp34.z = 0.0f;
        MtxPosition(&sp34, &sp28);
        f32 f28 = std::fabsf(sp28.z) * (1.0f - i_this->m2200);
        f32 f27 = 1.0f + (0.01f + REG0_F(231)) * (f28 * cM_ssin((s16)i_this->mWindAngle));
        s32 r0 = (s32)(2500.0f + 9000.0f * (0.8f * windPow));
        s32 r3_2 = 0x2710;
        if (r0 <= 0x2710) {
            r3_2 = r0;
        }
        i_this->mWindAngle += r3_2;
        i_this->m2212 += (s32)(3000.0f * cM_scos((s16)angle));
        s32 r3_3 = -0x12C;
        if (i_this->m2212 > 0) {
            r3_3 = 0x12C;
        }
        i_this->m2212 += r3_3;
        f32 f26 = 0.5f * cM_ssin((s16)angle);

        sp34.x = 0.0f;
        sp34.z = 1.6f;
        cXyz* nrm = &i_this->mPacket.mNrm[i_this->mPacket.mCount][0];
        if (l_HIO.m08 == 0) {
            if (l_ship->mStateFlag & 0x200) {
                if (i_this->m2208 == 0.0f) {
                    if (i_this->m2200 <= 0.0001f + l_HIO.m0C) {
                        i_this->m2208 = 1.0f;
                        i_this->mB4A = 0xF;
                    }
                } else if (i_this->mB4A > 0) {
                    cLib_addCalc2(&i_this->m2204, 1.414f, 0.25f, l_HIO.m1C);
                    i_this->mB4A--;
                } else {
                    cLib_addCalc2(&i_this->m2204, 1.0f, 0.1f, 0.05f);
                }
            } else {
                if (i_this->m2200 > 0.7f) {
                    i_this->m2208 = 0.0f;
                    i_this->mB4A = 0;
                }
                cLib_addCalc2(&i_this->m2204, 1.0f - 0.65f * i_this->m2200, 0.1f, 0.05f);
            }
        } else {
            i_this->m2200 = l_HIO.m14;
        }

        s32 r22 = 0;
        s32 r23 = 0;
        s32 r24 = 0;
        s32 r19 = 0;
        s32 r18 = 0;
        f32 f16 = 0.25f + 0.75f * windPow;
        f32 f15 = 0.5f + 0.25f * windPow;
        f32 d58 = 10922.0f;
        f32 d60 = 0.05f;
        f32 d68 = 0.67f;
        f32 d70 = 0.3f;
        f32 d78 = 9.0f;
        f32 d80 = 6.0f;
        f32 d88 = 0.65f;
        f32 d90 = 13.75f;
        do {
            f32 f25 = 1.0f - i_this->m2200;
            f32 f24 = (f32)(3 - r24);
            f32 f23 = (f32)(r23 - 2);
            s32 r26 = r23 * 4;
            s16 r21 = (s16)((f32)d58 * x_rate_tbl[r23]);
            s32 r5 = i_this->mWindAngle;
            f32 f31 = f29 * cM_ssin((s16)(r5 + r22 * i_this->mB4C));
            f32 f30 = 0.5f * (f29 * cM_scos((s16)(r5 + r22 * i_this->mB4E)));
            MtxPosition(&sp34, &sp28);
            sp28.x *= f16 > 1.0f ? 1.0f : f16;
            sp28.z *= f15 > 1.0f ? 1.0f : f15;
            f32 f2 = i_this->m2204;
            f32 f31_2 = f31 + f2 * (f25 * (sp28.x * f27));
            f32 f30_2 = f30 + f2 * (f25 * (sp28.z * f28));
            f32 f0_3 = f31_2 * f31_2 + f30_2 * f30_2;
            if (f0_3 > 0.0f) {
                volatile f32 spC;
                double guess = __frsqrte(f0_3);
                guess = 0.5 * guess * (3.0 - guess * guess * f0_3);
                guess = 0.5 * guess * (3.0 - guess * guess * f0_3);
                guess = 0.5 * guess * (3.0 - guess * guess * f0_3);
                spC = (f32)(f0_3 * guess);
                f0_3 = spC;
            }
            f32 d60f03 = (f32)d60 * f0_3;
            f32 f0_2 = i_this->mWind[r22];
            f31_2 *= f0_2;
            d60f03 *= f0_2;
            f30_2 *= f0_2;
            f32 f0_4 = f23 < 0.0f ? f23 : 0.0f;
            f32 f1_5 = f0_4 * f0_4 * 0.25f;
            f32 f3 = 1.0f - ((0.67f + 0.3f * f1_5) * i_this->m2200);
            f32 f3_2, f4, f5;
            if (l_HIO.m39 != 0) {
                f3_2 = f3 * (f25 + (&l_HIO.m70)[r23] * i_this->m2200);
                f32 f6 = (&l_HIO.m3C)[r23];
                f4 = 120.0f * (f6 * i_this->m2200);
                f5 = i_this->m2200 * (5.0f * f6 * (f32)r24);
            } else {
                f3_2 = f3 * (f25 + i_this->m2200 * z_rate_tbl2[r23]);
                f32 f7 = z_rate_tbl[r23];
                f4 = 120.0f * (i_this->m2200 * f7);
                f5 = i_this->m2200 * ((f32)r24 * (5.0f * f7));
            }
            l_pos_t* l4 = &l_pos[r22];
            nrm->x = l4->mX;
            nrm->y = f3_2 * l4->m00 + (1.0f - f3_2) * l_pos[r23 * 7].mX;
            nrm->z = f3_2 * l4->mZ;
            s32 r0_2 = ((s32)(u16)(i_this->m2212 + r21 * r24) >> jmaSinShift) * 4;
            f32 f6_2 = 9.0f - f24 * f24;
            f32 f7_2 = i_this->m2200;
            f32 f4_2 = f4 * (((f6_2 * (f7_2 * cM_ssin((s16)(i_this->m2212 + r21 * r24)))) / 9.0f) - ((f26 * f6_2) / 9.0f)) * (1.0f - 0.5f * f1_5);
            f32 f5_2 = f5 * (((f32)r24 * (f7_2 * cM_scos((s16)(i_this->m2212 + r21 * r24)))) / (f32)d78) * (1.0f - 0.5f * f1_5);
            f32 f0_5 = f4_2 * f4_2 + f5_2 * f5_2;
            if (f0_5 > 0.0f) {
                volatile f32 sp8;
                double guess = __frsqrte(f0_5);
                guess = 0.5 * guess * (3.0 - guess * guess * f0_5);
                guess = 0.5 * guess * (3.0 - guess * guess * f0_5);
                guess = 0.5 * guess * (3.0 - guess * guess * f0_5);
                sp8 = (f32)(f0_5 * guess);
                f0_5 = sp8;
            }
            f32 f1_2 = 0.25f * -f0_5;
            if (r24 > 4) {
                f1_2 += 4.25f * ((f32)(r24 - 4) * std::fabsf(cM_ssin((s16)(i_this->m2212 + r24 * (r21 * 2)))));
            }
            f32 f1_3;
            if (l_HIO.m39 != 0) {
                f1_3 = f1_2 * (i_this->m2200 * (6.0f * (&l_HIO.m3C)[r23] * ((f32)r24 / 6.0f)));
            } else {
                f1_3 = f1_2 * (i_this->m2200 * (((f32)r24 / 6.0f) * (6.0f * z_rate_tbl[r23])));
            }
            f32 f0_6 = (f32)d80 + ((f32)d88 * f25);
            nrm->x += f4_2 + f0_6 * (f31_2 * i_this->m2204);
            nrm->y += f5_2 + (d60f03 * f0_6);
            nrm->z += f1_3 + ((f0_6 * (f30_2 * i_this->m2204)) - (f32)d90);
            s32 r0_3 = r23 + 1;
            if (r24 < 6) {
                r0_3 = r23;
            }
            r23 = r0_3;
            r24 = (r24 < 6) ? (r24 + 1) : 0;
            r22++;
            r19 += 0xC;
            r18 += 4;
            nrm++;
        } while (r22 < 0x55);

        cXyz* base = &i_this->mPacket.mNrm[i_this->mPacket.mCount][0];
        f32 f4_3 = std::fabsf(i_this->mPacket.mNrm[i_this->mPacket.mCount][0x3B].z);
        f32 f5_3 = 1.0f - (f4_3 * (0.0015f + REG0_F(224)));
        f32 f6_3 = 1.0f - (f4_3 * (0.00070000003f + REG0_F(225)));
        f32 f7_3 = 1.0f - (f4_3 * (0.00020000007f + REG0_F(226)));
        f32 f2_2 = 1.0f - (f4_3 * (0.0015f + REG0_F(227)));
        f32 f1_4 = 1.0f - (f4_3 * (0.0012f + REG0_F(228)));
        for (s32 i = 0; i < 0x55; i++) {
            if (i >= 0x38 && i <= 0x3E) {
                base->z *= f5_3;
            } else if (i >= 0x31 && i <= 0x37) {
                base->z *= f6_3;
            } else if (i >= 0x2A && i <= 0x30) {
                base->z *= f7_3;
            } else if (i >= 0x3F && i <= 0x45) {
                base->z *= f2_2;
            } else if (i >= 0x46 && i <= 0x4D) {
                base->z *= f1_4;
            }
            base++;
        }

        cXyz* nrm2 = &i_this->mPacket.mNrm2[i_this->mPacket.mCount][0];
        cXyz sp10 = i_this->tevStr.mLightPosWorld - i_this->current.pos;
        cXyz sp1C = sp10;
        i_this->mPacket.setNrmMtx(sp1C);
        for (s32 j = 0; j < 0xC; j++) {
            for (s32 k = 0; k < 7; k++) {
                i_this->mPacket.setNrmVtx(nrm2, k, j);
                nrm2++;
            }
        }
        i_this->mPacket.setTopNrmVtx(nrm2);
        i_this->mPacket.setBackNrm();
        DCStoreRangeNoSync(&i_this->mPacket.mNrm[i_this->mPacket.mCount][0], 0x3FC);
        DCStoreRangeNoSync(&i_this->mPacket.mNrm2[i_this->mPacket.mCount][0], 0x3FC);
        DCStoreRangeNoSync(&i_this->mPacket.mPos[i_this->mPacket.mCount][0], 0x3FC);
    }
}

/* 800EA928-800EA94C       .text daGrid_Execute__FP8daGrid_c */
static BOOL daGrid_Execute(daGrid_c* i_this) {
    return ((daGrid_c*)i_this)->_execute();
}

/* 800EA94C-800EA954       .text daGrid_IsDelete__FP8daGrid_c */
static BOOL daGrid_IsDelete(daGrid_c*) {
    return TRUE;
}

/* 800EA954-800EA978       .text daGrid_Delete__FP8daGrid_c */
static BOOL daGrid_Delete(daGrid_c* i_this) {
    return ((daGrid_c*)i_this)->_delete();
}

/* 800EA978-800EA998       .text daGrid_Create__FP10fopAc_ac_c */
static cPhs_State daGrid_Create(fopAc_ac_c* i_this) {
    return ((daGrid_c*)i_this)->_create();
}

/* 800EA998-800EAEAC       .text _create__8daGrid_cFv */
cPhs_State daGrid_c::_create() {
    /* Nonmatching */
    fopAcM_SetupActor(this, daGrid_c);

    mParam = fopAcM_GetParam(this);

    cPhs_State st = dComIfG_resLoad(&mPhase1, &"Ship\0Cloth\0船の帆"[5]);
    if (st != cPhs_COMPLEATE_e) {
        return st;
    }
    st = dComIfG_resLoad(&mPhase2, &"Ship\0Cloth\0船の帆"[0]);
    if (st != cPhs_COMPLEATE_e) {
        return st;
    }

    if (l_HIO.mChildId < 0) {
        l_HIO.mChildId = mDoHIO_createChild(&"Ship\0Cloth\0船の帆"[0xB], (JORReflexible*)&l_HIO);
    }

    for (s32 i = 0; i < 0x55; i++) {
        f32 f27;
        if (i >= 0 && i <= 6) {
            f27 = 40.0f;
        } else if (i >= 7 && i <= 0xD) {
            f27 = 70.0f;
        } else if ((i >= 0x31 && i <= 0x37) || (i >= 0x2A && i <= 0x30)) {
            f27 = 85.0f;
        } else {
            f27 = 80.0f;
        }

        s32 r29 = 6;
        f32 f4 = std::fabsf(l_pos[0].mZ - l_pos[i].mZ);
        f32 z = l_pos[i].mZ;
        f32 f2 = std::fabsf(l_pos[6].mZ - z);
        f32 f0 = 1.05f * (1.5707964f / (std::fabsf(l_pos[0].mZ - l_pos[6].mZ) * 0.5f));
        if (f4 > f2) {
            f4 = f2;
        }
        f32 f27s = f27 * (f32)sin(f4 * f0);

        for (s32 j = 0; j < 7; j++) {
            if (i == j || i == j + 7 || i == j + 0xE || i == j + 0x15 || i == j + 0x1C ||
                i == j + 0x23 || i == j + 0x2A || i == j + 0x31 || i == j + 0x38 ||
                i == j + 0x3F || i == j + 0x46 || i == j + 0x4D) {
                r29 = j + 0x38;
            }
        }

        f32 x1 = l_pos[i].mX;
        f32 x2 = l_pos[r29].mX;
        f32 f0_2, f4_2, f1_2, f26;
        if (x1 < x2) {
            f0_2 = std::fabsf(l_pos[0].mX - x1);
            f4_2 = std::fabsf(x2 - x1);
            f1_2 = 1.05f * (1.5707964f / (std::fabsf(x2 - l_pos[0].mX) * 0.5f));
            if (r29 == 0x38) {
                f26 = 35.0f;
            } else if (r29 == 0x39) {
                f26 = 70.0f;
            } else {
                f26 = 80.0f;
            }
        } else {
            f0_2 = std::fabsf(x2 - x1);
            f4_2 = std::fabsf(l_pos[0x54].mX - x1);
            f1_2 = 1.15f * (1.5707964f / (std::fabsf(x2 - l_pos[0x54].mX) * 0.5f));
            f26 = 20.0f;
        }
        if (f0_2 > f4_2) {
            f0_2 = f4_2;
        }
        f32 f0_3 = f26 * (f32)sin(f0_2 * f1_2);
        f32 f4_3 = f27s * f27s + f0_3 * f0_3;
        if (f4_3 > 0.0f) {
            volatile f32 spC;
            double guess = __frsqrte(f4_3);
            guess = 0.5 * guess * (3.0 - guess * guess * f4_3);
            guess = 0.5 * guess * (3.0 - guess * guess * f4_3);
            guess = 0.5 * guess * (3.0 - guess * guess * f4_3);
            spC = (f32)(f4_3 * guess);
            f4_3 = spC;
        }
        mWind[i] = f4_3;
    }

    s16 name = 0xA7;
    l_ship = (daShip_c*)fopAcIt_Judge(fpcSch_JudgeForPName, &name);
    ho_move(this);
    return cPhs_COMPLEATE_e;
}

/* 800EAEAC-800EAF28       .text _delete__8daGrid_cFv */
bool daGrid_c::_delete() {
    dComIfG_resDelete(&mPhase1, &"Ship\0Cloth\0船の帆"[5]);
    dComIfG_resDelete(&mPhase2, &"Ship\0Cloth\0船の帆"[0]);
    if (l_HIO.mChildId >= 0) {
        mDoHIO_deleteChild(l_HIO.mChildId);
        l_HIO.mChildId = -1;
    }
    return true;
}

/* 800EAF28-800EB0EC       .text _execute__8daGrid_cFv */
bool daGrid_c::_execute() {
    /* Nonmatching */
    u8 alpha = mPacket.mAlpha;

    s32 target;
    if (g_dComIfG_gameInfo.play.mEvtCtrl.mMode == 0) {
        cXyz eye = dComIfGp_getCamera(0)->mCamera.Eye();
        f32 dist = PSVECSquareMag(&(current.pos - eye));
        dist = std::sqrtf(dist);
        s32 result;
        if (dist > l_HIO.m34) {
            result = l_HIO.m30;
        } else {
            f32 t = dist / l_HIO.m34;
            result = (s32)((f32)l_HIO.m30 * t + (f32)l_HIO.m31 * (1.0f - t));
        }
        target = result;
    } else {
        target = l_HIO.m30;
    }

    u8 t8 = target & 0xFF;
    if (t8 > alpha + 5) {
        mPacket.mAlpha = alpha + 5;
    } else if (t8 < alpha - 5) {
        mPacket.mAlpha = alpha - 5;
    } else {
        mPacket.mAlpha = t8;
    }

    if (scale.y < 0.06f) {
        return true;
    }
    ho_move(this);
    return true;
}

/* 800EB0EC-800EB328       .text _draw__8daGrid_cFv */
bool daGrid_c::_draw() {
    /* Nonmatching */
    if (scale.y < 0.06f) {
        return true;
    }

    tevStr = l_ship->tevStr;

    MtxTrans(current.pos.x, current.pos.y, current.pos.z, FALSE);
    mDoMtx_YrotM(*calc_mtx, current.angle.y);
    mDoMtx_XrotM(*calc_mtx, current.angle.x);
    mDoMtx_ZrotM(*calc_mtx, current.angle.z);
    s16 sailAngle = l_ship->mSailAngle;
    mDoMtx_YrotM(*calc_mtx, sailAngle);
    MtxScale(1.0f, scale.y, 1.0f, TRUE);
    MtxScale(l_HIO.m24, l_HIO.m28, l_HIO.m2C, TRUE);

    PSMTXConcat(j3dSys.getViewMtx(), *calc_mtx, mPacket.mMtx);

    mPacket.mpTevStr = &tevStr;
    J3DDrawBuffer* drawBuffer =
        mDoGph_gInf_c::isMonotone() ? g_dComIfG_gameInfo.drawlist.getXluListP1() : g_dComIfG_gameInfo.drawlist.getXluList();
    drawBuffer->mpZMtx = *calc_mtx;
    drawBuffer->entryZSort(&mPacket);
    return true;
}

static actor_method_class l_daGrid_Method = {
    (process_method_func)daGrid_Create,
    (process_method_func)daGrid_Delete,
    (process_method_func)daGrid_Execute,
    (process_method_func)daGrid_IsDelete,
    (process_method_func)daGrid_Draw,
};

actor_process_profile_definition g_profile_GRID = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_GRID_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daGrid_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_GRID_e,
    /* Actor SubMtd */ &l_daGrid_Method,
    /* Status       */ fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_0_e,
};
