//
// Generated by dtk
// Translation Unit: d_a_kantera.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_kantera.h"
#include "res/Object/Kantera.h"
#include "d/d_kankyo.h"
#include "d/d_s_play.h"
#include "d/d_com_inf_game.h"
#include "f_op/f_op_actor_mng.h"
#include "m_Do/m_Do_lib.h"

/* 000000EC-000001E8       .text kantera_nodeCallBack__FP7J3DNodei */
static BOOL kantera_nodeCallBack(J3DNode* node, int calcTiming) {
    if (calcTiming == J3DNodeCBCalcTiming_In) {
        J3DJoint* joint = (J3DJoint*)node;
        s32 jntNo = joint->getJntNo();
        J3DModel* model = j3dSys.getModel();
        kantera_class* i_this = (kantera_class*)model->getUserArea();

        if ((i_this != NULL) && (jntNo == MK_KANTERA_JNT_TOTTE_e || (jntNo == MK_KANTERA_JNT_KANTERA_e))) {
            MTXCopy(model->getAnmMtx(jntNo), *calc_mtx);
            cMtx_XrotM(*calc_mtx, i_this->mJointBaseRot.x + i_this->mJointRot[jntNo].x);
            cMtx_ZrotM(*calc_mtx, i_this->mJointBaseRot.z + i_this->mJointRot[jntNo].z);
            model->setAnmMtx(jntNo, *calc_mtx);
            MTXCopy(*calc_mtx, J3DSys::mCurrentMtx);
        }
    }
    return TRUE;
}

/* 000001E8-000002C8       .text ga_draw__FP13kantera_class */
void ga_draw(kantera_class* i_this) {
    mo_ga_s* pGa = &i_this->mGa[0];

    for (s32 i = 0; i < ARRAY_SSIZE(i_this->mGa); i++, pGa++) {
        if (pGa->m2E != 0) {
            MtxTrans(pGa->mPos.x, pGa->mPos.y, pGa->mPos.z, 0);
            cMtx_YrotM(*calc_mtx, pGa->mRotY);
            cMtx_XrotM(*calc_mtx, pGa->mRotX);
            MtxScale(pGa->mScale, pGa->mScale * pGa->mScaleY, pGa->mScale, 1);
            MtxTrans(0.0f, -18.0f, 0.0f, 1);
            pGa->mpModel->setBaseTRMtx(*calc_mtx);
            mDoExt_modelUpdateDL(pGa->mpModel);
        }
    }
}

/* 000002C8-00000584       .text daKantera_Draw__FP13kantera_class */
static BOOL daKantera_Draw(kantera_class* i_this) {
    if (i_this->mState >= 10) {
        MtxTrans(i_this->actor.current.pos.x, i_this->actor.current.pos.y, i_this->actor.current.pos.z, 0);
        f32 fVar2 = i_this->mBonScale * (REG17_F(0) + 0.8f);
        cMtx_YrotM(*calc_mtx, i_this->mBonRot);
        MtxScale(fVar2, fVar2, fVar2, true);
        MTXCopy(*calc_mtx, i_this->mAlphaModelMtx);
        GXColor color;
        color.r = REG0_S(4) + 0xEB;
        color.g = REG0_S(5) + 0x7D;
        color.b = REG0_S(6);
        color.a = REG0_S(7);
        dComIfGd_setAlphaModelColor(color);
        dComIfGd_setAlphaModel(dDlst_alphaModel_c::TYPE_THREE_SPHERES, i_this->mAlphaModelMtx, i_this->mBonAlpha);
    } else {
        if (i_this->mSwitchNo != 0) {
            return TRUE;
        }

        g_env_light.settingTevStruct(TEV_TYPE_ACTOR, &i_this->actor.current.pos, &i_this->actor.tevStr);
        J3DModel* pModel2 = i_this->mpModel1;
        g_env_light.setLightTevColorType(pModel2, &i_this->actor.tevStr);
        i_this->mpBrkAnm1->entry(pModel2->getModelData());
        mDoExt_modelEntryDL(pModel2);

        MtxTrans(i_this->mBonPos.x, i_this->mBonPos.y, i_this->mBonPos.z, 0);
        f32 fVar2 = i_this->mBonScale * 4.06f * 0.25f;
        MtxScale(fVar2, fVar2, fVar2, true);
        cMtx_YrotM(*calc_mtx, i_this->mBonRot);
        cMtx_XrotM(*calc_mtx, i_this->mBonRot / 2);
        MTXCopy(*calc_mtx, i_this->mAlphaModelMtx);

        GXColor color;
        color.r = REG0_S(4) + 0xEB;
        color.g = REG0_S(5) + 0x7D;
        color.b = REG0_S(6);
        color.a = REG0_S(7);
        dComIfGd_setAlphaModelColor(color);
        dComIfGd_setAlphaModel(dDlst_alphaModel_c::TYPE_TWO_SPHERES, i_this->mAlphaModelMtx, i_this->mBonAlpha);
        f32 fVar3 = i_this->mModel2Scale * 0.35909086f;
        MtxScale(fVar3, fVar3, fVar3, true);
        pModel2 = i_this->mpModel2;
        pModel2->setBaseTRMtx(*calc_mtx);
        i_this->mpBrkAnm2->entry(pModel2->getModelData());
        mDoExt_modelUpdate(pModel2);
        ga_draw(i_this);
    }
    return TRUE;
}

/* 00000584-00000828       .text ga_move__FP13kantera_class */
void ga_move(kantera_class* i_this) {
    mo_ga_s* pmVar4 = &i_this->mGa[0];
    cXyz sp3C;
    cXyz sp30;
    cXyz sp24;

    sp24.x = (i_this->mBonPos.x - i_this->m2E4.x) * 0.3f;
    sp24.y = (i_this->mBonPos.y - i_this->m2E4.y) * 0.3f;
    sp24.z = (i_this->mBonPos.z - i_this->m2E4.z) * 0.3f;

    sp3C.x = 0.0f;
    sp3C.y = 0.0f;
    sp3C.z = 10.0f;

    for (s32 i = 0; i < ARRAY_SSIZE(i_this->mGa); i++, pmVar4++) {
        if (pmVar4->m2E != 0) {
            if (pmVar4->m2F != 0) {
                pmVar4->m2F--;
            } else {
                pmVar4->m2F = cM_rndF(5.0f);
                pmVar4->m10.x = i_this->mBonPos.x + cM_rndFX(150.0f);
                pmVar4->m10.y = i_this->mBonPos.y + cM_rndFX(30.0f);
                pmVar4->m10.z = i_this->mBonPos.z + cM_rndFX(150.0f);
            }

            cXyz sp18 = pmVar4->m10 - pmVar4->mPos;
            s16 iVar2 = cM_atan2s(sp18.x, sp18.z);
            cLib_addCalcAngleS2(&pmVar4->mRotY, iVar2, 2, 0x1000);
            s16 iVar3 = -cM_atan2s(sp18.y, std::sqrtf(SQUARE(sp18.x) + SQUARE(sp18.z)));
            cLib_addCalcAngleS2(&pmVar4->mRotX, iVar3, 2, 0x1000);
            cMtx_YrotS(*calc_mtx, pmVar4->mRotY);
            cMtx_XrotM(*calc_mtx, pmVar4->mRotX);
            MtxPosition(&sp3C, &sp30);
            pmVar4->mPos.x += sp30.x + sp24.x;
            pmVar4->mPos.y += sp30.y + sp24.y;
            pmVar4->mPos.z += sp30.z + sp24.z;
            pmVar4->mScaleY = cM_ssin(pmVar4->m2C);
            pmVar4->m2C = pmVar4->m2C + 0x3e00;
        }
    }
}

/* 00000864-00000B68       .text bon_move__FP13kantera_class */
void bon_move(kantera_class* i_this) {
    cXyz sp14;
    mDoLib_project(&i_this->mBonPos, &sp14);
    bool bVar2;

    if (sp14.x < 0.0f || sp14.x > 638.99f || sp14.y < 0.0f || sp14.y > 526.99f || sp14.z >= 0.0f) {
        bVar2 = true;
    } else {
        dComIfGd_peekZ(sp14.x, sp14.y, &i_this->mPeekZResult);
        f32 fVar5 = 0.5f - sp14.z * -1.0f;
        if (fVar5 < 0.0f) {
            fVar5 = 0.0f;
        }
        u32 iVar3 = fVar5 * ((REG0_F(1) + 33.553f) * 1e+06f);
        cXyz sp08;
        MTXMultVec(*(Mtx*)dComIfGd_getProjViewMtx(), &i_this->mBonPos, &sp08);

        s32 iVar4 = 0;
        if (sp08.z < -4.97f) {
            iVar4 = -0x46;
        } else if (sp08.z < -4.95f) {
            iVar4 = -0x3c;
        } else if (sp08.z < -4.925f) {
            iVar4 = -0x32;
        } else if (sp08.z < -4.9f) {
            iVar4 = -10;
        } else if (sp08.z < -4.88f) {
            iVar4 = -3;
        }

        if (iVar3 + (iVar4 + REG0_S(1)) * 100 > i_this->mPeekZResult) {
            bVar2 = true;
        } else {
            bVar2 = false;
        }
    }

    if (bVar2) {
        cLib_addCalc0(&i_this->mModel2Scale, 1.0f, 0.3333300054073334f);
    } else {
        cLib_addCalc2(&i_this->mModel2Scale, 1.0f, 1.0f, 0.3333f);
    }

    for (s32 i = 0; i < ARRAY_SSIZE(i_this->mAnimCounters); i++) {
        if (i_this->mAnimCounters[i] != 0) {
            i_this->mAnimCounters[i]--;
        }
    }

    if (i_this->mAnimCounters[0] == 0) {
        i_this->mAnimCounters[0] = cM_rndF(10.0f) + 2.0f;
        i_this->mBonAlphaTarget = cM_rndF(5.0f) + 4.0f;
    }

    if (i_this->mAnimCounters[1] == 0) {
        i_this->mAnimCounters[1] = cM_rndF(6.0f) + 3.0f;
        i_this->mBonScaleTarget = cM_rndF(0.075f) + 0.75f;
    }

    cLib_addCalc2(&i_this->mBonAlpha, i_this->mBonAlphaTarget, 1.0f, 0.35f);
    cLib_addCalc2(&i_this->mBonScale, i_this->mBonScaleTarget, 0.4f, 0.04f);

    i_this->mPlight.mPos = i_this->mBonPos;
    i_this->mPlight.mColor.r = 600;
    i_this->mPlight.mColor.g = 400;
    i_this->mPlight.mColor.b = 0x78;
    i_this->mPlight.mPower = 375.0f;
    i_this->mPlight.mFluctuation = 250.0f;
}

void kantera_move(kantera_class* i_this) {
    fopAc_ac_c* player = dComIfGp_getPlayer(0);
    fopAc_ac_c* target = fopAcM_SearchByID(i_this->mTargetActorID);
    cXyz* target_pos = (cXyz*)((u8*)target + 0x28EC);
    s8* target_unk = (s8*)((u8*)target + 0x2A09);

    i_this->mAnimCounter++;
    i_this->mBonRot += 0x100;

    switch (i_this->mState) {
    case 0x2:
        break;
    case 0x3:
        break;
    case 0x4:
        break;
    case 0x64:
        break;
    case 0:
        if (i_this->mParam0 == 0x23) {
            i_this->mState = 1;
        } else if (i_this->mParam0 == 0x01) {
            i_this->mState = 3;
        } else {
            i_this->mState = 0x64;
        }
        break;

    case 1:
        if (target != NULL) {
            i_this->actor.current.pos.x = target_pos->x;
            i_this->actor.current.pos.y = target_pos->y;
            i_this->actor.current.pos.z = target_pos->z;
            i_this->actor.current.angle.y = target->current.angle.y;
            mDoMtx_YrotS(*calc_mtx, -i_this->actor.current.angle.y);

            cXyz sp34;
            cXyz sp28;
            sp34.x = i_this->mBonPos.x - i_this->m2E4.x;
            sp34.y = 0.0f;
            sp34.z = i_this->mBonPos.z - i_this->m2E4.z;
            MtxPosition(&sp34, &sp28);

            s16 angleX = (s16)(100.0f * (1.2f * sp28.y));
            s16 angleZ = (s16)(100.0f * (-1.2f * sp28.x));
            if (angleX > 0x4000) {
                angleX = 0x4000;
            } else if (angleX < -0x4000) {
                angleX = -0x4000;
            }
            if (angleZ > 0x4000) {
                angleZ = 0x4000;
            } else if (angleZ < -0x4000) {
                angleZ = -0x4000;
            }

            if (angleX >= 0) {
                if ((s16)i_this->mJointBaseRotTarget.x <= angleX) {
                    i_this->mJointBaseRotTarget.x = angleX;
                }
            } else if ((s16)i_this->mJointBaseRotTarget.x >= angleX) {
                i_this->mJointBaseRotTarget.x = angleX;
            }
            if (angleZ >= 0) {
                if ((s16)i_this->mJointBaseRotTarget.z <= angleZ) {
                    i_this->mJointBaseRotTarget.z = angleZ;
                }
            } else if ((s16)i_this->mJointBaseRotTarget.z >= angleZ) {
                i_this->mJointBaseRotTarget.z = angleZ;
            }

            for (s32 i = 0; i < 2; i++) {
                i_this->mJointRot[i].x =
                    (s16)(3000.0f * cM_ssin((s16)(i_this->mAnimCounter * 0xBB8 + i * 0x36B0)));
                i_this->mJointRot[i].z =
                    (s16)(3000.0f * cM_scos((s16)(i_this->mAnimCounter * 0x9C4 + i * 0x3E80)));
            }

            if (*target_unk == 1 || *target_unk == 2) {
                i_this->mState = 5;
                if (*target_unk == 1) {
                    i_this->actor.speed.x = cM_rndFX(15.0f);
                    i_this->actor.speed.z = cM_rndFX(15.0f);
                    i_this->actor.speed.y = 30.0f + REG6_F(8);
                } else {
                    mDoMtx_YrotS(*calc_mtx,
                                 cM_atan2s(player->current.pos.x - i_this->actor.current.pos.x,
                                           player->current.pos.z - i_this->actor.current.pos.z));
                    cXyz sp34_2(0.0f, 0.0f, 20.0f + REG6_F(9));
                    MtxPosition(&sp34_2, &i_this->actor.speed);
                    i_this->actor.speed.y = 10.0f + REG6_F(8);
                }
            case 5:
                cLib_addCalc2(&i_this->mOffsY, 55.0f, 1.0f, 4.0f);
                i_this->actor.current.angle.y += 0x1F4;
                i_this->actor.current.angle.x += 0x514;
                i_this->actor.current.pos.x += i_this->actor.speed.x;
                i_this->actor.current.pos.y += i_this->actor.speed.y;
                i_this->actor.current.pos.z += i_this->actor.speed.z;
                i_this->actor.speed.y -= 2.0f + REG6_F(10);

                for (s32 i = 0; i < 2; i++) {
                    cLib_addCalcAngleS2(&i_this->mJointRot[i].x, 0, 2, 0x320);
                    cLib_addCalcAngleS2(&i_this->mJointRot[i].z, 0, 2, 0x320);
                }

                i_this->mAcch.CrrPos(*dComIfG_Bgsp());
                i_this->mSph.SetC(i_this->actor.current.pos);
                dComIfG_Ccsp()->Set(&i_this->mSph);

                if (i_this->mAcch.ChkGroundHit() || i_this->mAcch.ChkWallHit() || i_this->mSph.ChkAtHit()) {
                    dBgS_GndChk gnd_chk;
                    gnd_chk.m_pos.x = i_this->actor.current.pos.x;
                    gnd_chk.m_pos.y = i_this->actor.current.pos.y + 50.0f;
                    gnd_chk.m_pos.z = i_this->actor.current.pos.z;
                    f32 ground = dComIfG_Bgsp()->GroundCross(&gnd_chk);
                    f32 ground_check = 2.5f + ground;
                    if (ground_check != -G_CM3D_F_INF) {
                        i_this->actor.current.pos.y = 2.0f + ground_check;
                    }

                    static cXyz e_scale(1.0f, 1.0f, 1.0f);
                    g_dComIfG_gameInfo.play.getParticle()->setNormal(
                        dPa_name::ID_IT_JT_KTR_SMOKE, &i_this->actor.current.pos, NULL, &e_scale, 0xC8,
                        &i_this->mPtclCallBack0, -1, NULL, NULL, NULL);
                    g_dComIfG_gameInfo.play.getParticle()->setNormal(
                        dPa_name::ID_IT_JN_KTR_FIRE, &i_this->actor.current.pos, NULL, &e_scale, 0xC8,
                        &i_this->mPtclCallBack1, -1, NULL, NULL, NULL);

                    mDoAud_seStart(JA_SE_OBJ_KANTERA_BREAK, &i_this->actor.eyePos, 0,
                                   dComIfGp_getReverb(fopAcM_GetRoomNo(&i_this->actor)));
                    dKy_Sound_set(i_this->actor.current.pos, 0x96, fopAcM_GetID(i_this), 0xA);

                    i_this->mState = 10;
                    i_this->m35C = 0x82;
                }
            case 10:
                if (i_this->mPtclCallBack0.getEmitter() != NULL && i_this->mPtclCallBack1.getEmitter() != NULL) {
                    if (i_this->m35C > 0x28) {
                        i_this->mSph.SetR(30.0f * i_this->mParticleScale.x);
                        i_this->mSph.SetC(i_this->actor.current.pos);
                        dComIfG_Ccsp()->Set(&i_this->mSph);
                        cLib_addCalc2(&i_this->mParticleScale.x, 2.0f, 0.2f, 0.1f + REG0_F(0));
                        cLib_addCalc2(&i_this->mParticleScale.z, 2.0f, 0.2f, 0.1f + REG0_F(0));
                        i_this->mBonScale = i_this->mParticleScale.x;

                        JPABaseEmitter* emitter0 = i_this->mPtclCallBack0.getEmitter();
                        emitter0->mEmitterScale.x = i_this->mParticleScale.x;
                        emitter0->mEmitterScale.y = i_this->mParticleScale.y;
                        emitter0->mEmitterScale.z = i_this->mParticleScale.z;
                        JPABaseEmitter* emitter1 = i_this->mPtclCallBack1.getEmitter();
                        emitter1->mEmitterScale.x = i_this->mParticleScale.x;
                        emitter1->mEmitterScale.y = i_this->mParticleScale.y;
                        emitter1->mEmitterScale.z = i_this->mParticleScale.z;

                        i_this->mPlight.mPos = i_this->actor.current.pos;
                        i_this->mPlight.mColor.r = 0x258;
                        i_this->mPlight.mColor.g = 0x190;
                        i_this->mPlight.mColor.b = 0x78;
                        i_this->mPlight.mPower = 800.0f;
                        i_this->mPlight.mFluctuation = 250.0f;
                    } else if (i_this->m35C < 0x1E) {
                        cLib_addCalc0(&i_this->mBonScale, 1.0f, 0.1f);
                    }
                }

                if (target != NULL && *target_unk == 2) {
                    if (i_this->m35C > 0x6E) {
                        i_this->mSph.OnAtVsEnemyBit();
                    } else {
                        i_this->mSph.OffAtVsEnemyBit();
                    }
                }
            }
        }
        break;
    }

    if (i_this->mState < 10) {
        cLib_addCalcAngleS2(&i_this->mJointBaseRot.x, i_this->mJointBaseRotTarget.x, 2, 0x320);
        cLib_addCalcAngleS2(&i_this->mJointBaseRot.z, i_this->mJointBaseRotTarget.z, 2, 0x320);
        cLib_addCalcAngleS2(&i_this->mJointBaseRotTarget.x, 0, 1, 0x5DC);
        cLib_addCalcAngleS2(&i_this->mJointBaseRotTarget.z, 0, 1, 0x5DC);
        bon_move(i_this);
        ga_move(i_this);
    }
}

/* 000018BC-00001ABC       .text daKantera_Execute__FP13kantera_class */
static BOOL daKantera_Execute(kantera_class* i_this) {
    if (i_this->mSwitchNo != 0) {
        if (dComIfGs_isSwitch(i_this->mSwitchNo - 1, fopAcM_GetRoomNo(&i_this->actor))) {
            i_this->mSwitchNo = 0;
        } else {
            return TRUE;
        }
    }

    if (i_this->m35C != 0) {
        i_this->m35C--;
        if (i_this->m35C == 30) {
            i_this->mPtclCallBack0.remove();
            i_this->mPtclCallBack1.remove();
        }

        if (i_this->m35C == 0) {
            fopAcM_delete(&i_this->actor);
        }
    }

    kantera_move(i_this);

    if (i_this->mState < 10) {
        i_this->mpModel1->calc();
        MtxTrans(i_this->actor.current.pos.x, i_this->actor.current.pos.y, i_this->actor.current.pos.z, 0);
        cMtx_YrotM(*calc_mtx, i_this->actor.current.angle.y);
        cMtx_XrotM(*calc_mtx, i_this->actor.current.angle.x);
        MtxTrans(0.0f, i_this->mOffsY, 0.0f, 1);

        J3DModel* model = i_this->mpModel1;
        model->setBaseScale(i_this->actor.scale);
        model->setBaseTRMtx(*calc_mtx);

        i_this->actor.eyePos = i_this->actor.current.pos;

        MTXCopy(model->getAnmMtx(MK_KANTERA_JNT_KANTERA_e), *calc_mtx);

        i_this->m2E4 = i_this->mBonPos;

        cXyz sp08(0.0f, -40.0f, 0.0f);
        MtxPosition(&sp08, &i_this->mBonPos);

        i_this->mpBrkAnm1->play();
        i_this->mpBrkAnm2->play();
    }
    return TRUE;
}

/* 00001ABC-00001AC4       .text daKantera_IsDelete__FP13kantera_class */
static BOOL daKantera_IsDelete(kantera_class*) {
    return TRUE;
}

/* 00001AC4-00001B30       .text daKantera_Delete__FP13kantera_class */
static BOOL daKantera_Delete(kantera_class* i_this) {
    i_this->mPtclCallBack0.remove();
    i_this->mPtclCallBack1.remove();
    dComIfG_resDelete(&i_this->mPhase, "Kantera");
    dKy_plight_cut(&i_this->mPlight);
    return TRUE;
}

/* 00001B30-00001F5C       .text daKantera_CreateHeap__FP10fopAc_ac_c */
static BOOL daKantera_CreateHeap(fopAc_ac_c* a_this) {
    kantera_class* i_this = (kantera_class*)a_this;

    J3DModelData* modelData = static_cast<J3DModelData*>(dComIfG_getObjectRes("Kantera", dRes_INDEX_KANTERA_BMD_MK_KANTERA_e));
    JUT_ASSERT(1014, modelData != NULL);

    i_this->mpModel1 = mDoExt_J3DModel__create(modelData, 0, 0x11020203);
    if (i_this->mpModel1 == NULL) {
        return FALSE;
    }

    J3DAnmTevRegKey* anm_res_brk = static_cast<J3DAnmTevRegKey*>(dComIfG_getObjectRes("Kantera", dRes_INDEX_KANTERA_BRK_MK_KANTERA_e));
    JUT_ASSERT(1036, anm_res_brk != NULL);

    i_this->mpBrkAnm1 = new mDoExt_brkAnm();
    if (i_this->mpBrkAnm1 == NULL) {
        return FALSE;
    }

    if (!i_this->mpBrkAnm1->init(modelData, anm_res_brk, true, J3DFrameCtrl::EMode_LOOP)) {
        return FALSE;
    }

    modelData = static_cast<J3DModelData*>(dComIfG_getObjectRes("Kantera", dRes_INDEX_KANTERA_BMD_LF_e));
    JUT_ASSERT(1048, modelData != NULL);

    i_this->mpModel2 = mDoExt_J3DModel__create(modelData, 0, 0x11020203);
    if (i_this->mpModel2 == NULL) {
        return FALSE;
    }

    anm_res_brk = static_cast<J3DAnmTevRegKey*>(dComIfG_getObjectRes("Kantera", dRes_INDEX_KANTERA_BRK_LF_e));
    JUT_ASSERT(1058, anm_res_brk != NULL);

    i_this->mpBrkAnm2 = new mDoExt_brkAnm();
    if (i_this->mpBrkAnm2 == NULL) {
        return FALSE;
    }

    if (!i_this->mpBrkAnm2->init(modelData, anm_res_brk, true, J3DFrameCtrl::EMode_LOOP)) {
        return FALSE;
    }

    modelData = static_cast<J3DModelData*>(dComIfG_getObjectRes("Kantera", dRes_INDEX_KANTERA_BMD_GA_e));
    JUT_ASSERT(1125, modelData != NULL);

    for (s32 i = 0; i < ARRAY_SSIZE(i_this->mGa); i++) {
        i_this->mGa[i].mpModel = mDoExt_J3DModel__create(modelData, 0, 0x11020203);
        if (i_this->mGa[i].mpModel == NULL) {
            return FALSE;
        }

        if (cM_rndF(1.0) < 0.5f) {
            i_this->mGa[i].m2E = 1;
            i_this->mGa[i].mPos = i_this->actor.current.pos;
            i_this->mGa[i].mScale = cM_rndF(0.3f) + 0.3f;
            i_this->mGa[i].m2C = cM_rndF(30000.0f);
        }
    }
    return TRUE;
}

/* 00001FA4-00002304       .text daKantera_Create__FP10fopAc_ac_c */
static cPhs_State daKantera_Create(fopAc_ac_c* a_this) {
    static dCcD_SrcSph at_sph_src = {
        // dCcD_SrcGObjInf
        {
            /* Flags             */ 0,
            /* SrcObjAt  Type    */ AT_TYPE_FIRE,
            /* SrcObjAt  Atp     */ 1,
            /* SrcObjAt  SPrm    */ cCcD_AtSPrm_Set_e | cCcD_AtSPrm_VsPlayer_e,
            /* SrcObjTg  Type    */ 0,
            /* SrcObjTg  SPrm    */ 0,
            /* SrcObjCo  SPrm    */ cCcD_CoSPrm_Set_e | cCcD_CoSPrm_IsPlayer_e | cCcD_CoSPrm_VsGrpAll_e,
            /* SrcGObjAt Se      */ 0,
            /* SrcGObjAt HitMark */ dCcG_AtHitMark_None_e,
            /* SrcGObjAt Spl     */ dCcG_At_Spl_UNK8,
            /* SrcGObjAt Mtrl    */ 0,
            /* SrcGObjAt SPrm    */ 0,
            /* SrcGObjTg Se      */ 0,
            /* SrcGObjTg HitMark */ 0,
            /* SrcGObjTg Spl     */ dCcG_Tg_Spl_UNK0,
            /* SrcGObjTg Mtrl    */ 0,
            /* SrcGObjTg SPrm    */ 0,
            /* SrcGObjCo SPrm    */ 0,
        },
        // cM3dGSphS
        {{
            /* Center */ {0.0f, 0.0f, 0.0f},
            /* Radius */ 40.0f,
        }},
    };

    kantera_class* i_this = (kantera_class*)a_this;

    fopAcM_ct(a_this, kantera_class);

    i_this->mParam0 = fopAcM_GetParam(a_this);
    i_this->mParam1 = fopAcM_GetParam(a_this) >> 8;
    i_this->mParam2 = fopAcM_GetParam(a_this) >> 0x18;

    cPhs_State PVar1 = dComIfG_resLoad(&i_this->mPhase, "Kantera");
    if (PVar1 == cPhs_COMPLEATE_e) {
        if (!fopAcM_entrySolidHeap(a_this, daKantera_CreateHeap, 0x10000)) {
            return cPhs_ERROR_e;
        }

        J3DModel* model = i_this->mpModel1;
        for (u16 i = 0; i < model->getModelData()->getJointNum(); i++) {
            model->getModelData()->getJointNodePointer(i)->setCallBack(kantera_nodeCallBack);
        }

        fopAcM_OffStatus(a_this, 0x00000000);

        i_this->mpModel2->setBaseScale(a_this->scale);
        if (i_this->mParam2 != 0xff) {
            i_this->mSwitchNo = i_this->mParam2 + 1;
        }

        fopAcM_SetMtx(a_this, i_this->mpModel1->getBaseTRMtx());
        fopAcM_setCullSizeBox(a_this, -60.0f, -100.0f, -60.0f, 60.0f, 50.0f, 60.0f);
        model->setUserArea((u32)a_this);
        i_this->m2B0 = (s16)cM_rndF(100.0f);
        i_this->m2B4 = (s16)cM_rndF(100.0f);
        dKy_plight_set(&i_this->mPlight);
        i_this->mAcch.Set(fopAcM_GetPosition_p(a_this), fopAcM_GetOldPosition_p(a_this), a_this, 1, &i_this->mAcchCir, fopAcM_GetSpeed_p(a_this));
        i_this->mAcchCir.SetWall(0.0f, 30.0f);
        i_this->mStts.Init(0xe6, 0xff, a_this);

        if (i_this->mParam0 == 7) {
            a_this->scale.x = 0.0f;
            a_this->scale.y = 0.0f;
            a_this->scale.z = 0.0f;
            i_this->mParam0 = 1;
        }
        i_this->mSph.Set(at_sph_src);
        i_this->mSph.SetStts(&i_this->mStts);
        daKantera_Execute(i_this);
    }
    return PVar1;
}

static actor_method_class l_daKantera_Method = {
    (process_method_func)daKantera_Create,
    (process_method_func)daKantera_Delete,
    (process_method_func)daKantera_Execute,
    (process_method_func)daKantera_IsDelete,
    (process_method_func)daKantera_Draw,
};

actor_process_profile_definition g_profile_KANTERA = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_KANTERA_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(kantera_class),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_KANTERA_e,
    /* Actor SubMtd */ &l_daKantera_Method,
    /* Status       */ fopAcStts_CULL_e | fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
