//
// Generated by dtk
// Translation Unit: d_a_icelift.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_icelift.h"
#include "d/d_bg_s_func.h"
#include "d/d_bg_s_movebg_actor.h"
#include "d/d_com_inf_game.h"
#include "d/d_lib.h"
#include "d/d_path.h"
#include "res/Object/Yllic.h"
#include "res/Object/Ylsic.h"
#include "m_Do/m_Do_ext.h"
#include "m_Do/m_Do_mtx.h"

const int daIlift_c::m_bmdidx[2] = {4, 4};
const int daIlift_c::m_dzbidx[2] = {7, 7};
const u32 daIlift_c::m_heapsize[2] = {0xAE0, 0x1B80};
const f32 daIlift_c::m_down_param = 4.0f;
const f32 daIlift_c::m_max_speed = 4.0f;

const char* daIlift_c::m_arcname[2] = {
    "Ylsic",
    "Yllic",
};

/* 00000078-000000E0       .text _delete__9daIlift_cFv */
bool daIlift_c::_delete() {
#if VERSION > VERSION_DEMO
    if (heap)
#endif
    {
        dComIfG_Bgsp()->Release(mpBgW);
    }
    dComIfG_resDelete(&mPhs, m_arcname[mType]);
    return TRUE;
}

/* 000000E0-00000100       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c* i_this) {
    return ((daIlift_c*)i_this)->CreateHeap();
}

static void rideCallBack(dBgW*, fopAc_ac_c*, fopAc_ac_c*);

/* 00000100-00000284       .text CreateHeap__9daIlift_cFv */
BOOL daIlift_c::CreateHeap() {
    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectRes(m_arcname[mType], m_bmdidx[mType]);
    JUT_ASSERT(DEMO_SELECT(233, 235), modelData != NULL);

    mpModel = mDoExt_J3DModel__create(modelData, 0x80000, 0x11000022);
    if (!mpModel) {
        return FALSE;
    }

    mpBgW = new dBgW();
    if (mpBgW) {
        cBgD_t* dzb = (cBgD_t*)dComIfG_getObjectRes(m_arcname[mType], m_dzbidx[mType]);
        if (mpBgW->Set(dzb, cBgW::MOVE_BG_e, &mBgMtx) == 1) {
            return FALSE;
        }
        mpBgW->SetCrrFunc(dBgS_MoveBGProc_TypicalRotY);
        mpBgW->SetRideCallback(rideCallBack);
    } else {
        return FALSE;
    }
    return TRUE;
}

static void rideCallBack(dBgW*, fopAc_ac_c*, fopAc_ac_c*);

/* 00000284-00000480       .text rideCallBack__FP4dBgWP10fopAc_ac_cP10fopAc_ac_c */
void rideCallBack(dBgW*, fopAc_ac_c* i_act, fopAc_ac_c* i_other) {
    /* Nonmatching */
    daIlift_c* i_this = (daIlift_c*)i_act;
    f32 tiltFactor;

    cXyz posOffset = i_other->current.pos - i_this->current.pos;
    i_this->mDiff = posOffset;
    if (fopAcM_GetName(i_other) == fpcNm_PLAYER_e) {
        i_this->mOnRide = TRUE;
        i_this->m510 = 0;
        cXyz up(0.0f, 1.0f, 0.0f);
        posOffset = posOffset.outprod(up);
        f32 offsetMagnitude = posOffset.abs();
        i_this->mDist = offsetMagnitude;
        if (posOffset.normalizeRS()) {
            i_this->mTiltAngleTarget = (s16)(-i_this->mDist * 4.0f);
            cLib_addCalcAngleS2(&i_this->mTiltAngle, i_this->mTiltAngleTarget, 8, 0x200);
            tiltFactor = cM_ssin(i_this->mTiltAngle);
            i_this->mTargetRotation.x = posOffset.x * tiltFactor;
            i_this->mTargetRotation.y = posOffset.y * tiltFactor;
            i_this->mTargetRotation.z = posOffset.z * tiltFactor;
            i_this->mTargetRotation.w = cM_scos(i_this->mTiltAngle);
            i_this->m508 = 10.0f;
        }
    }
}

/* 00000480-00000680       .text CreateInit__9daIlift_cFv */
void daIlift_c::CreateInit() {
    /* Nonmatching */
    fopAcM_SetMtx(this, mpModel->getBaseTRMtx());
    fopAcM_setCullSizeBox(this, -200.0f, -250.0f, -200.0f, 200.0f, 250.0f, 200.0f);
    fopAcM_setCullSizeFar(this, 1.0f);
    mAcchCir.SetWall(30.0f, 30.0f);
    mAcch.Set(&current.pos, &old.pos, this, 1, &mAcchCir, &speed, NULL, NULL);
    mAcch.ClrWaterNone();
    mAcch.ClrRoofNone();
    fopAcM_SetGravity(this, -5.0f);
    mTargetRotation = ZeroQuat;
    mCurrentRotation = mTargetRotation;
    mPathNo = daIlift_prm::getPathId(this);
    if (mPathNo != 0xFF) {
        mPath = dPath_GetRoomPath(mPathNo, fopAcM_GetRoomNo(this));
        if (mPath) {
            mPointDir = 1;
            mPointIdx = 1;
            mNextPnt = mPath->m_points[mPointIdx].m_position;
            mPrevPnt = mNextPnt;
            current.pos = mPath->m_points[0].m_position;
        } else {
            mPathNo = 0xFF;
        }
    }
    mSwNo = daIlift_prm::getSwNo(this);
    dComIfG_Bgsp()->Regist(mpBgW, this);
    set_mtx();
    mpBgW->Move();
}

/* 00000680-00000794       .text _create__9daIlift_cFv */
cPhs_State daIlift_c::_create() {
    int res;
    fopAcM_ct(this, daIlift_c);
    mType = daIlift_prm::getType(this);
    if (mType >= 2) {
        return cPhs_ERROR_e;
    }
    res = dComIfG_resLoad(&mPhs, m_arcname[mType]);
    if (res == cPhs_COMPLEATE_e) {
        if (!fopAcM_entrySolidHeap(this, CheckCreateHeap, m_heapsize[mType])) {
            return cPhs_ERROR_e;
        }
        CreateInit();
    }
    return res;
}

/* 00000804-0000089C       .text set_mtx__9daIlift_cFv */
void daIlift_c::set_mtx() {
    mpModel->setBaseScale(scale);
    mDoMtx_stack_c::transS(current.pos.x, current.pos.y, current.pos.z);
    mDoMtx_stack_c::quatM(&mCurrentRotation);
    mpModel->setBaseTRMtx(mDoMtx_stack_c::get());
    mDoMtx_stack_c::scaleM(scale.x, scale.y, scale.x);
    PSMTXCopy(mDoMtx_stack_c::get(), mBgMtx);
}

/* 0000089C-000009C8       .text _execute__9daIlift_cFv */
bool daIlift_c::_execute() {
    fopAc_ac_c* player = dComIfGp_getPlayer(0);
    mSpeed = m_max_speed;
    mTimer++;
    m510++;
    path_move();
    lift_wave();
    mDoMtx_quatSlerp(&mCurrentRotation, &mTargetRotation, &mCurrentRotation, 0.25f);
    mPrevOnRide = mOnRide;
    mOnRide = 0;
    if (mSwNo != 0xFF) {
        if (!fopAcM_isSwitch(this, mSwNo)) {
            mpBgW->ChangeAttributeCodeByPathPntNo(0x40, 0x15);
            mpBgW->ChangeAttributeCodeByPathPntNo(0x41, 0x9);
        } else {
            mpBgW->ChangeAttributeCodeByPathPntNo(0x40, 0xF);
            mpBgW->ChangeAttributeCodeByPathPntNo(0x41, 0x0);
        }
    }
    set_mtx();
    mpBgW->Move();
    mPlayerPos = player->current.pos;
    return TRUE;
}

/* 000009C8-00000C8C       .text lift_wave__9daIlift_cFv */
void daIlift_c::lift_wave() {
    /* Nonmatching */
    fopAc_ac_c* player = dComIfGp_getPlayer(0);
    cXyz up(0.0f, 1.0f, 0.0f);

    if (mOnRide == 0 && mPrevOnRide != 0) {
        cXyz sp30 = mPlayerPos - player->current.pos;
        cXyz spC(sp30.x, 0.0f, sp30.z);
        f32 dist = spC.abs();
        mTiltAngleTarget = (s16)((dist / 18.0f) * (10.0f * (4.0f * -mDist)));
        mDist = 0.0f;
    }
    if (mOnRide == 0) {
        f32 cosVal = jmaCosTable[((s32)((m510 << 10) & 0xFC00) >> jmaSinShift)];
        cLib_addCalcAngleS(&mTiltAngle, (s16)((f32)mTiltAngleTarget * cosVal / (f32)m510), 4, 0x800, 0x400);
        f32 sinVal = cM_ssin(mTiltAngle);
        cXyz sp24 = mDiff.outprod(up);
        cXyz sp3C = sp24.normZP();
        if (sp3C != cXyz::Zero) {
            mTargetRotation.x = sp3C.x * sinVal;
            mTargetRotation.y = sp3C.y * sinVal;
            mTargetRotation.z = sp3C.z * sinVal;
            mTargetRotation.w = cM_scos(mTiltAngle);
        }
        if (m510 > 0x78) {
            mTiltAngleTarget = 0;
        }
    }
}

/* 00000C8C-00000CB8       .text path_move__9daIlift_cFv */
void daIlift_c::path_move() {
    if (mPathNo != 0xFF) {
        lift_normal_move();
    }
}

/* 00000CB8-00000E5C       .text lift_normal_move__9daIlift_cFv */
void daIlift_c::lift_normal_move() {
    /* Nonmatching */
    switch (mMoveMode) {
    case 0:
        mMoveMode = 1;
        mPointNo = 0;
        set_next_pnt();
        // fallthrough
    case 1:
        mPointNo++;
        if (cLib_addCalc(&m53C, mSpeed, 0.25f, 1.0f, 1.0f) == 0.0f) {
            mMoveMode = 2;
        }
        break;
    case 2:
        mPointNo = 0;
        {
            cXyz spC = current.pos - mNextPnt;
            f32 dist = spC.abs();
            if (dist < 50.0f) {
                mMoveMode = 3;
            }
        }
        break;
    case 3:
        mPointNo++;
        if (cLib_addCalc(&m53C, mSpeed / 2.2f, 0.25f, 1.0f, 1.0f) == 0.0f) {
            mMoveMode = 0;
        }
        break;
    }
    cLib_addCalcPos2(&current.pos, mNextPnt, 1.0f, m53C);
}

/* 00000E5C-00000F58       .text set_next_pnt__9daIlift_cFv */
void daIlift_c::set_next_pnt() {
    /* Nonmatching */
    if (mPathNo != 0xFF) {
        mPointIdx += mPointDir;
        if (dPath_ChkClose(mPath)) {
            if ((s8)mPointIdx > (s8)mPath->m_num - 1) {
                mPointIdx = 0;
            } else if ((s8)mPointIdx < 0) {
                mPointIdx = mPath->m_num - 1;
            }
        } else {
            if ((s8)mPointIdx > (s32)(mPath->m_num - 1)) {
                mPointDir = 0xFF;
                mPointIdx = mPath->m_num - 2;
            } else if ((s8)mPointIdx < 0) {
                mPointDir = 1;
                mPointIdx = 1;
            }
        }
        mPrevPnt = mNextPnt;
        dPnt* pPnt = &mPath->m_points[(s8)mPointIdx];
        mNextPnt = pPnt->m_position;
    }
}

/* 00000F58-00000FF8       .text _draw__9daIlift_cFv */
bool daIlift_c::_draw() {
    g_env_light.settingTevStruct(TEV_TYPE_BG0, &current.pos, &tevStr);
    g_env_light.setLightTevColorType(mpModel, &tevStr);
    dComIfGd_setListBG();
    mDoExt_modelUpdateDL(mpModel);
    dComIfGd_setList();
    return TRUE;
}

/* 00000FF8-00001018       .text daIlift_Create__FPv */
static cPhs_State daIlift_Create(void* i_this) {
    return ((daIlift_c*)i_this)->_create();
}

/* 00001018-0000103C       .text daIlift_Delete__FPv */
static BOOL daIlift_Delete(void* i_this) {
    return ((daIlift_c*)i_this)->_delete();
}

/* 0000103C-00001060       .text daIlift_Draw__FPv */
static BOOL daIlift_Draw(void* i_this) {
    return ((daIlift_c*)i_this)->_draw();
}

/* 00001060-00001084       .text daIlift_Execute__FPv */
static BOOL daIlift_Execute(void* i_this) {
    return ((daIlift_c*)i_this)->_execute();
}

/* 00001084-0000108C       .text daIlift_IsDelete__FPv */
static BOOL daIlift_IsDelete(void*) {
    return TRUE;
}

static actor_method_class daIliftMethodTable = {
    (process_method_func)daIlift_Create,
    (process_method_func)daIlift_Delete,
    (process_method_func)daIlift_Execute,
    (process_method_func)daIlift_IsDelete,
    (process_method_func)daIlift_Draw,
};

actor_process_profile_definition g_profile_ICE_LIFT = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0003,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_ICE_LIFT_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daIlift_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_ICE_LIFT_e,
    /* Actor SubMtd */ &daIliftMethodTable,
    /* Status       */ fopAcStts_CULL_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
