//
// Generated by dtk
// Translation Unit: d_a_obj_light.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_obj_light.h"
#include "res/Object/Skanran.h"
#include "d/d_bg_w.h"
#include "d/d_com_inf_game.h"
#include "m_Do/m_Do_ext.h"
#include "JSystem/JUtility/JUTAssert.h"

const char daObjLight::Act_c::M_arcname[] = "Skanran";

/* 000000EC-00000110       .text solidHeapCB__Q210daObjLight5Act_cFP10fopAc_ac_c */
BOOL daObjLight::Act_c::solidHeapCB(fopAc_ac_c* i_this) {
    return ((Act_c*)i_this)->create_heap();
}

/* 00000110-00000344       .text create_heap__Q210daObjLight5Act_cFv */
bool daObjLight::Act_c::create_heap() {
    J3DModelData* mdl_data_lighthouse = static_cast<J3DModelData*>(dComIfG_getObjectRes(M_arcname, dRes_INDEX_SKANRAN_BDL_STOUDAI_e));
    JUT_ASSERT(267, mdl_data_lighthouse != 0);

    if (mdl_data_lighthouse != NULL) {
        mpModelLighthouse = mDoExt_J3DModel__create(mdl_data_lighthouse, 0, 0x11020203);
    }

    J3DModelData* mdl_data_light = static_cast<J3DModelData*>(dComIfG_getObjectRes(M_arcname, dRes_INDEX_SKANRAN_BDL_SHIKARI_e));
    JUT_ASSERT(274, mdl_data_light != 0);

    if (mdl_data_light != NULL) {
        mpModelLight = mDoExt_J3DModel__create(mdl_data_light, 0, 0x11020203);
        mpModelLight2 = mDoExt_J3DModel__create(mdl_data_light, 0, 0x11020203);
    }

    set_mtx();

    cBgD_t* bgw_data = static_cast<cBgD_t*>(dComIfG_getObjectRes(M_arcname, dRes_INDEX_SKANRAN_DZB_STOUDAI_e));
    JUT_ASSERT(284, bgw_data != 0);

    if (bgw_data != NULL) {
        mpBgW = new dBgW();
        if (mpBgW != NULL) {
            if (mpBgW->Set(bgw_data, cBgW::MOVE_BG_e, &mBgWBaseMtx) == 1) {
                return false;
            }
        }
    }

    return mdl_data_lighthouse != NULL && mpModelLighthouse != NULL && mdl_data_light != NULL && mpModelLight != NULL &&
           mpModelLight2 != NULL && bgw_data != NULL && mpBgW != NULL;
}

/* 00000344-000003C0       .text init_collision__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::init_collision() {
    /* Nonmatching */
}

/* 000003C0-00000468       .text set_collision__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::set_collision() {
    /* Nonmatching */
}

/* 000004A4-0000070C       .text _create__Q210daObjLight5Act_cFv */
cPhs_State daObjLight::Act_c::_create() {
    /* Nonmatching */
}

/* 000008C4-00000964       .text _delete__Q210daObjLight5Act_cFv */
bool daObjLight::Act_c::_delete() {
    /* Nonmatching */
}

/* 00000964-00000A9C       .text set_fire__Q210daObjLight5Act_cFi */
void daObjLight::Act_c::set_fire(int) {
    /* Nonmatching */
}

/* 00000A9C-00000B04       .text draw_fire__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::draw_fire() {
    if (mpModel != NULL) {
        GXColor color;
        color.r = 0xEB;
        color.g = 0x7D;
        color.b = 0;
        color.a = 0;
        dComIfGd_setAlphaModelColor(color);
        dComIfGd_setAlphaModel(dDlst_alphaModel_c::TYPE_TWO_SPHERES, mFireMtx, mFireAlpha);
    }
}

/* 00000B04-00000C28       .text exe_fire__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::exe_fire() {
    /* Nonmatching */
}

/* 00000C28-00000C60       .text delete_fire__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::delete_fire() {
    /* Nonmatching */
}

/* 00000C60-00000C8C       .text now_event__Q210daObjLight5Act_cFs */
bool daObjLight::Act_c::now_event(s16 i_event) {
    bool ret = false;
    if (mEventActive != 0 && mEventId == i_event) {
        ret = true;
    }
    return ret;
}

/* 00000C8C-00000CB4       .text set_event__Q210daObjLight5Act_cFs */
bool daObjLight::Act_c::set_event(s16 i_event) {
    if (mEventActive == 0) {
        mEventId = i_event;
        mEventActive = 1;
        return true;
    }
    return false;
}

/* 00000CB4-00000D84       .text exe_event__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::exe_event() {
    /* Nonmatching */
}

/* 00000D84-00001084       .text set_mtx__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::set_mtx() {
    /* Nonmatching */
}

/* 00001084-000011C4       .text renew_angle__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::renew_angle() {
    /* Nonmatching */
}

/* 000011C4-00001330       .text control_light__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::control_light() {
    /* Nonmatching */
}

/* 00001330-00001398       .text control_treasure__Q210daObjLight5Act_cFv */
void daObjLight::Act_c::control_treasure() {
    /* Nonmatching */
}

/* 00001398-00001400       .text _execute__Q210daObjLight5Act_cFv */
bool daObjLight::Act_c::_execute() {
    /* Nonmatching */
}

/* 00001400-00001528       .text _draw__Q210daObjLight5Act_cFv */
bool daObjLight::Act_c::_draw() {
    /* Nonmatching */
}

namespace daObjLight {
namespace {
/* 00001528-00001548       .text Mthd_Create__Q210daObjLight27@unnamed@d_a_obj_light_cpp@FPv */
cPhs_State Mthd_Create(void* i_this) {
    return ((daObjLight::Act_c*)i_this)->_create();
}

/* 00001548-0000156C       .text Mthd_Delete__Q210daObjLight27@unnamed@d_a_obj_light_cpp@FPv */
BOOL Mthd_Delete(void* i_this) {
    return ((daObjLight::Act_c*)i_this)->_delete();
}

/* 0000156C-00001590       .text Mthd_Execute__Q210daObjLight27@unnamed@d_a_obj_light_cpp@FPv */
BOOL Mthd_Execute(void* i_this) {
    return ((daObjLight::Act_c*)i_this)->_execute();
}

/* 00001590-000015B4       .text Mthd_Draw__Q210daObjLight27@unnamed@d_a_obj_light_cpp@FPv */
BOOL Mthd_Draw(void* i_this) {
    return ((daObjLight::Act_c*)i_this)->_draw();
}

/* 000015B4-000015BC       .text Mthd_IsDelete__Q210daObjLight27@unnamed@d_a_obj_light_cpp@FPv */
BOOL Mthd_IsDelete(void*) {
    return TRUE;
}

static actor_method_class Mthd_Table = {
    (process_method_func)Mthd_Create,
    (process_method_func)Mthd_Delete,
    (process_method_func)Mthd_Execute,
    (process_method_func)Mthd_IsDelete,
    (process_method_func)Mthd_Draw,
};
}; // namespace
}; // namespace daObjLight

actor_process_profile_definition g_profile_Obj_Light = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0003,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_Obj_Light_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daObjLight::Act_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_Obj_Light_e,
    /* Actor SubMtd */ &daObjLight::Mthd_Table,
    /* Status       */ fopAcStts_NOCULLEXEC_e | fopAcStts_CULL_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
