//
// Generated by dtk
// Translation Unit: d_a_obj_mmrr.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_obj_mmrr.h"
#include "d/d_bg_s_lin_chk.h"
#include "d/d_com_inf_game.h"
#include "d/d_detect.h"
#include "d/d_kankyo.h"
#include "d/d_particle.h"
#include "f_op/f_op_actor_mng.h"
#include "m_Do/m_Do_ext.h"
#include "m_Do/m_Do_mtx.h"
#include "SSystem/SComponent/c_lib.h"
#include "SSystem/SComponent/c_math.h"

namespace daObjMmrr {
    namespace {
        struct L_attr_t {
            struct TriSrc {
                /* 0x00 */ Vec mP1;
                /* 0x0C */ Vec mP2;
                /* 0x18 */ Vec mP3;
            };  // 0x24
            /* 0x00 */ TriSrc mTri[5];
            /* 0xB4 */ f32 mFB4;
            /* 0xB8 */ f32 mFB8;
            /* 0xBC */ s16 mRotY;
            /* 0xBE */ s16 mBE;
            /* 0xC0 */ f32 mFC0;
            /* 0xC4 */ f32 mFC4;
            /* 0xC8 */ f32 mFC8;
            /* 0xCC */ f32 mFCC;
            /* 0xD0 */ f32 mCullSize;
        };

        const L_attr_t L_attr = {
            /* mTri */ {
                {{0.0f, 0.0f, 0.0f}, {-50.0f, -230.0f, 0.0f}, {50.0f, -230.0f, 0.0f}},
                {{0.0f, 0.0f, 0.0f}, {-60.0f, -20.0f, 0.0f}, {-90.0f, -80.0f, 0.0f}},
                {{0.0f, 0.0f, 0.0f}, {90.0f, -80.0f, 0.0f}, {60.0f, -20.0f, 0.0f}},
                {{0.0f, 0.0f, 0.0f}, {-90.0f, -80.0f, 0.0f}, {-50.0f, -230.0f, 0.0f}},
                {{0.0f, 0.0f, 0.0f}, {50.0f, -230.0f, 0.0f}, {90.0f, -80.0f, 0.0f}},
            },
            /* mFB4 */ 445.0f,
            /* mFB8 */ 0.0f,
            /* mRotY */ -2000,
            /* mBE */ 0,
            /* mFC0 */ 0.0f,
            /* mFC4 */ 320.0f,
            /* mFC8 */ 40.0f,
            /* mFCC */ 120.0f,
            /* mCullSize */ 10000.0f,
        };
    };

    const char Act_c::M_arcname[8] = "Mmirror";

    const dCcD_SrcTri Act_c::M_tri_src = {
        // dCcD_SrcGObjInf
        {
            // cCcD_SrcObj
            {
                /* Flags             */ 0,
                /* mObjAt Type       */ 0,
                /* mObjAt Atp        */ 0,
                /* mObjAt SPrm       */ 0,
                /* mObjTg Type       */ 0x00800000,
                /* mObjTg SPrm       */ 0x9,
                /* mObjCo SPrm       */ 0,
            },
            // dCcD_SrcGObjAt
            {
                /* mSe      */ 0,
                /* mHitMark */ 0,
                /* mSpl     */ 0,
                /* mMtrl    */ 0,
                /* mSPrm    */ 0,
            },
            // dCcD_SrcGObjTg
            {
                /* mSe      */ 0,
                /* mHitMark */ 0,
                /* mSpl     */ 0,
                /* mMtrl    */ 0,
                /* mSPrm    */ 0,
            },
            // dCcD_SrcGObjCo
            {
                /* mSPrm    */ 0,
            },
        },
        // cCcD_SrcTriAttr
        {
            {{0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}},
        },
    };

    const dCcD_SrcCps Act_c::M_cps_src = {
        // dCcD_SrcGObjInf
        {
            // cCcD_SrcObj
            {
                /* Flags             */ 0,
                /* mObjAt Type       */ 0x00800000,
                /* mObjAt Atp        */ 0,
                /* mObjAt SPrm       */ 0xF,
                /* mObjTg Type       */ 0,
                /* mObjTg SPrm       */ 0,
                /* mObjCo SPrm       */ 0,
            },
            // dCcD_SrcGObjAt
            {
                /* mSe      */ 0,
                /* mHitMark */ 0,
                /* mSpl     */ 0,
                /* mMtrl    */ 0,
                /* mSPrm    */ 0,
            },
            // dCcD_SrcGObjTg
            {
                /* mSe      */ 0,
                /* mHitMark */ 0,
                /* mSpl     */ 0,
                /* mMtrl    */ 0,
                /* mSPrm    */ 0,
            },
            // dCcD_SrcGObjCo
            {
                /* mSPrm    */ 0,
            },
        },
        // cCcD_SrcCpsAttr
        {{{0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}, 50.0f}},
    };

}; // namespace daObjMmrr

/* 00000078-000000AC       .text end__Q29daObjMmrr5Eff_cFv */
void daObjMmrr::Eff_c::end() {
    if (mpEmitter != NULL) {
        mpEmitter->mGlobalPrmColor.a = 0;
    }
    dPa_followEcallBack::end();
}

/* 000000AC-000000EC       .text remove__Q29daObjMmrr5Eff_cFv */
void daObjMmrr::Eff_c::remove() {
    if (mpEmitter != NULL) {
        mpEmitter->mGlobalPrmColor.a = 0;
    }
    dPa_followEcallBack::remove();
}

/* 000000EC-00000110       .text solidHeapCB__Q29daObjMmrr5Act_cFP10fopAc_ac_c */
int daObjMmrr::Act_c::solidHeapCB(fopAc_ac_c* i_this) {
    return (u8)((Act_c*)i_this)->create_heap();
}

/* 00000110-00000360       .text create_heap__Q29daObjMmrr5Act_cFv */
    /* Nonmatching */
bool daObjMmrr::Act_c::create_heap() {
    J3DModelData* bdl_Mmrr = (J3DModelData*)dComIfG_getObjectRes(M_arcname, 0x9);
    JUT_ASSERT(488, bdl_Mmrr != 0);

    mpModel = mDoExt_J3DModel__create(bdl_Mmrr, 0x80000, 0x11000222);

    J3DModelData* bdl_Yssmr00 = (J3DModelData*)dComIfG_getObjectRes(M_arcname, 0xB);
    JUT_ASSERT(497, bdl_Yssmr00 != 0);

    mpModel2 = mDoExt_J3DModel__create(bdl_Yssmr00, 0x80000, 0x11000222);

    J3DAnmTextureSRTKey* btk_Mmrr = (J3DAnmTextureSRTKey*)dComIfG_getObjectRes(M_arcname, 0xE);
    JUT_ASSERT(508, btk_Mmrr != 0);

    BOOL btkOk = mpBtkAnm.init(bdl_Mmrr, btk_Mmrr, 1, 2, 1.0f, 0, -1, 0, 0);

    J3DAnmTextureSRTKey* btk_Yssmr00 = (J3DAnmTextureSRTKey*)dComIfG_getObjectRes(M_arcname, 0x10);
    JUT_ASSERT(515, btk_Yssmr00 != 0);

    BOOL btkOk2 = mpBtkAnm2.init(bdl_Yssmr00, btk_Yssmr00, 1, 2, 1.0f, 0, -1, 0, 0);

    return mpModel && mpModel2 && btkOk && btkOk2;
}

/* 00000360-00000434       .text init_cc__Q29daObjMmrr5Act_cFv */

void daObjMmrr::Act_c::init_cc() {
    for (int i = 0; i < 5; i++) {
        mStts[i].Init(0xFF, 0xFF, this);
        mTri[i].Set(M_tri_src);
        mTri[i].SetStts(&mStts[i]);
        mTri[i].OnTgNoHitMark();
        mStts2.Init(0xFF, 0xFF, this);
        mCps.Set(M_cps_src);
        mCps.SetStts(&mStts2);
    }
    set_cc_rec_pos();
    set_cc_trans_pos();
}

/* 00000434-000005DC       .text set_cc_rec_pos__Q29daObjMmrr5Act_cFv */
void daObjMmrr::Act_c::set_cc_rec_pos() {
    mDoMtx_stack_c::transS(current.pos);
    mDoMtx_stack_c::ZXYrotM(shape_angle.x, shape_angle.y, shape_angle.z);
    mDoMtx_stack_c::transM(0.0f, L_attr.mFB4, L_attr.mFB8);
    mDoMtx_stack_c::XrotM(L_attr.mRotY);
    for (int i = 0; i < 5; i++) {
        cXyz a;
        cXyz pa, pb, pc;
        a.set(L_attr.mTri[i].mP1);
        PSMTXMultVec(mDoMtx_stack_c::now, &a, &pa);
        a.set(L_attr.mTri[i].mP2);
        PSMTXMultVec(mDoMtx_stack_c::now, &a, &pb);
        a.set(L_attr.mTri[i].mP3);
        PSMTXMultVec(mDoMtx_stack_c::now, &a, &pc);
        mTri[i].setPos(&pa, &pb, &pc);
    }
}

/* 000005DC-000009FC       .text set_cc_trans_pos__Q29daObjMmrr5Act_cFv */
    /* Nonmatching */
void daObjMmrr::Act_c::set_cc_trans_pos() {
    cXyz end(0.0f, 0.0f, L_attr.mCullSize);
    mDoMtx_stack_c::transS(current.pos);
    mDoMtx_stack_c::ZXYrotM(shape_angle.x, shape_angle.y, shape_angle.z);
    mDoMtx_stack_c::transM(L_attr.mFC0, L_attr.mFC4, L_attr.mFC8);

    cXyz start;
    cXyz end2;
    PSMTXMultVec(mDoMtx_stack_c::now, &cXyz::Zero, &start);
    PSMTXMultVec(mDoMtx_stack_c::now, &end, &end2);

    dBgS_MirLightLinChk chk;
    chk.Set(&start, &end2, this);
    if (dComIfG_Bgsp()->LineCross(&chk)) {
        end2 = chk.GetCross();
    }

    mCps.SetStartEnd(start, end2);
    mCps.SetR(L_attr.mFCC);
    mCps.CalcAtVec();
    mCps.GetAtVecP()->normalizeRS();

    mC00 = start.abs(end2) / L_attr.mCullSize;
}

/* 00000F88-0000102C       .text set_cull__Q29daObjMmrr5Act_cFv */
void daObjMmrr::Act_c::set_cull() {
    f32 cullX;
    f32 cullY;
    if (mBF9 != 0) {
        cullX = -L_attr.mCullSize * cM_ssin(L_attr.mRotY);
        cullY = L_attr.mCullSize * cM_scos(L_attr.mRotY);
    } else {
        cullX = 0.0f;
        cullY = 0.0f;
    }
    fopAcM_setCullSizeBox(this, -160.0f, -1.0f, -160.0f, 160.0f, 680.0f + cullX,
                          160.0f + cullY);
}

/* 0000102C-0000122C       .text _create__Q29daObjMmrr5Act_cFv */
cPhs_State daObjMmrr::Act_c::_create() {
    fopAcM_SetupActor(this, daObjMmrr::Act_c);

    cPhs_State phase = dComIfG_resLoad(&mPhs, M_arcname);
    if (phase == cPhs_COMPLEATE_e) {
        if (fopAcM_entrySolidHeap(this, (heapCallbackFunc)solidHeapCB, 0x1A80)) {
            fopAcM_SetMtx(this, mpModel->getBaseTRMtx());
            init_mtx();
            init_cc();
            mBF8 = 0;
            mBFC = 0.0f;
            mBF9 = 0;
            set_cull();
        } else {
            phase = cPhs_ERROR_e;
        }
    }
    return phase;
}

/* 0000122C-0000126C       .text _delete__Q29daObjMmrr5Act_cFv */
bool daObjMmrr::Act_c::_delete() {
    eff_remove();
    dComIfG_resDelete(&mPhs, M_arcname);
    return true;
}

/* 0000126C-0000131C       .text set_mtx__Q29daObjMmrr5Act_cFv */
void daObjMmrr::Act_c::set_mtx() {
    cXyz scale(this->scale.x, this->scale.y, this->scale.z * mC00);

    mpModel2->setBaseScale(scale);
    mDoMtx_stack_c::transS(current.pos);
    mDoMtx_stack_c::ZXYrotM(shape_angle.x, shape_angle.y, shape_angle.z);
    mpModel->setBaseTRMtx(mDoMtx_stack_c::now);
    mpModel2->setBaseTRMtx(mDoMtx_stack_c::now);
}

/* 0000131C-00001358       .text init_mtx__Q29daObjMmrr5Act_cFv */
void daObjMmrr::Act_c::init_mtx() {
    mpModel->setBaseScale(scale);
    set_mtx();
}

/* 00001358-00001418       .text chk_light__Q29daObjMmrr5Act_cFv */
    /* Nonmatching */
bool daObjMmrr::Act_c::chk_light() {
    bool light = false;
    if (dComIfGp_getDetect().chk_light(&eyePos)) {
        light = true;
    } else {
        for (int i = 0; i < 5; i++) {
            dCcD_Tri& tri = mTri[i];
            if (tri.ChkTgHit()) {
                if (tri.GetNP()->inprod(*tri.GetTgRVecP()) < 0.0f) {
                    light = true;
                }
                tri.ClrTgHit();
            }
        }
    }
    return light;
}

/* 00001418-00001480       .text eff_start__Q29daObjMmrr5Act_cFv */

void daObjMmrr::Act_c::eff_start() {
    dComIfGp_particle_set(0x8294, &current.pos, &shape_angle, NULL, 0xFF, &mEff, -1, NULL, NULL, NULL);
}

/* 00001480-000014AC       .text eff_stop__Q29daObjMmrr5Act_cFv */
void daObjMmrr::Act_c::eff_stop() {
    mEff.end();
}

/* 000014AC-000014D0       .text eff_remove__Q29daObjMmrr5Act_cFv */
void daObjMmrr::Act_c::eff_remove() {
    mEff.remove();
}

/* 000014D0-000016E8       .text _execute__Q29daObjMmrr5Act_cFv */
    /* Nonmatching */
bool daObjMmrr::Act_c::_execute() {
    attention_info.position.x = current.pos.x;
    attention_info.position.y = current.pos.y + 260.0f;
    attention_info.position.z = current.pos.z;
    eyePos = attention_info.position;

    if (chk_light()) {
        cLib_chaseF(&mBFC, 1.0f, 0.2f);
    } else {
        cLib_chaseF(&mBFC, 0.0f, 0.2f);
    }
    u8 mbf9 = mBF9;
    mBF9 = mBFC > 0.999f;

    mpBtkAnm.play();
    mpBtkAnm2.play();

    if (mBF8 != 0) {
        set_cc_rec_pos();
    }
    if (mBF8 != 0 || mBF9 != 0) {
        set_cc_trans_pos();
    }
    set_mtx();
    set_cull();

    if (mBF9) {
        if (!mbf9) {
            fopAcM_seStart(this, 0x6961, 0);
            eff_start();
        }
        fopAcM_seStart(this, 0x7028, 0);
    } else if (mbf9) {
        eff_stop();
    }

    for (int i = 0; i < 5; i++) {
        dComIfG_Ccsp()->Set(&mTri[i]);
    }
    if (mBF9 != 0) {
        dComIfG_Ccsp()->Set(&mCps);
    }
    mBF8 = 0;
    return true;
}

/* 000016E8-000017E8       .text _draw__Q29daObjMmrr5Act_cFv */
    /* Nonmatching */
bool daObjMmrr::Act_c::_draw() {
    u8 mbf9 = mBF9;
    g_env_light.settingTevStruct(0, &current.pos, &tevStr);
    g_env_light.setLightTevColorType(mpModel, &tevStr);

    mpBtkAnm.entry(mpModel->getModelData());
    if (mbf9) {
        g_env_light.setLightTevColorType(mpModel2, &tevStr);
        mpBtkAnm2.entry(mpModel2->getModelData());
    }

    dComIfGd_setListBG();
    mDoExt_modelUpdateDL(mpModel);
    dComIfGd_setList();
    if (mbf9) {
        mDoExt_modelUpdateDL(mpModel2);
    }
    return true;
}

namespace daObjMmrr {
    namespace {
        /* 000017E8-00001808       .text Mthd_Create__Q29daObjMmrr26@unnamed@d_a_obj_mmrr_cpp@FPv */
        cPhs_State Mthd_Create(void* i_this) {
            return ((daObjMmrr::Act_c*)i_this)->_create();
        }

        /* 00001808-0000182C       .text Mthd_Delete__Q29daObjMmrr26@unnamed@d_a_obj_mmrr_cpp@FPv */
        BOOL Mthd_Delete(void* i_this) {
            return ((daObjMmrr::Act_c*)i_this)->_delete();
        }

        /* 0000182C-00001850       .text Mthd_Execute__Q29daObjMmrr26@unnamed@d_a_obj_mmrr_cpp@FPv */
        BOOL Mthd_Execute(void* i_this) {
            return ((daObjMmrr::Act_c*)i_this)->_execute();
        }

        /* 00001850-00001874       .text Mthd_Draw__Q29daObjMmrr26@unnamed@d_a_obj_mmrr_cpp@FPv */
        BOOL Mthd_Draw(void* i_this) {
            return ((daObjMmrr::Act_c*)i_this)->_draw();
        }

        /* 00001874-0000187C       .text Mthd_IsDelete__Q29daObjMmrr26@unnamed@d_a_obj_mmrr_cpp@FPv */
        BOOL Mthd_IsDelete(void*) {
            return TRUE;
        }

        static actor_method_class Mthd_Table = {
            (process_method_func)Mthd_Create,
            (process_method_func)Mthd_Delete,
            (process_method_func)Mthd_Execute,
            (process_method_func)Mthd_IsDelete,
            (process_method_func)Mthd_Draw,
        };
    }; // namespace
}; // namespace daObjMmrr

actor_process_profile_definition g_profile_Obj_Mmrr = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_Obj_Mmrr_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daObjMmrr::Act_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_Obj_Mmrr_e,
    /* Actor SubMtd */ &daObjMmrr::Mthd_Table,
    /* Status       */ fopAcStts_CULL_e | fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
