//
// Generated by dtk
// Translation Unit: d_a_waterfall.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_waterfall.h"
#include "SSystem/SComponent/c_math.h"

const char daWfall_c::m_arcname[6] = "Wfall";
const s16 daWfall_c::m_wait_timer = 0x32;
const s16 daWfall_c::m_heapsize[2] = { 0x35A0, 0x4870 };

/* 00000078-000000F0       .text _delete__9daWfall_cFv */
bool daWfall_c::_delete() {
    mFollow1.remove();
    mFollow2.remove();
    dComIfG_resDelete(&mPhs, m_arcname);
    JAIZelBasic::zel_basic->seDeleteObject(&m344);
    return true;
}

/* 000000F0-00000110       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c* i_this) {
    return ((daWfall_c*)i_this)->CreateHeap();
}

/* 00000110-0000048C       .text CreateHeap__9daWfall_cFv */
BOOL daWfall_c::CreateHeap() {
    /* Nonmatching */
}

/* 0000048C-00000708       .text CreateInit__9daWfall_cFv */
void daWfall_c::CreateInit() {
    /* Nonmatching */
}

/* 00000708-00000838       .text _create__9daWfall_cFv */
cPhs_State daWfall_c::_create() {
    fopAcM_SetupActor(this, daWfall_c);

    cPhs_State phase = (cPhs_State)dComIfG_resLoad(&mPhs, m_arcname);
    if (phase == cPhs_COMPLEATE_e) {
        m356 = (fopAcM_GetParam(this) >> 8) & 0xF;
        if (!fopAcM_entrySolidHeap(this, CheckCreateHeap, m_heapsize[m356])) {
            return cPhs_ERROR_e;
        }
        CreateInit();
    }
    return phase;
}

/* 00000938-000009B8       .text set_mtx__9daWfall_cFv */
void daWfall_c::set_mtx() {
    /* Nonmatching */
}

/* 000009B8-00000A1C       .text set_gate_mtx__9daWfall_cFv */
void daWfall_c::set_gate_mtx() {
    mDoMtx_stack_c::transS(m344.x, m344.y, m344.z);
    mDoMtx_YrotM(mDoMtx_stack_c::get(), current.angle.y);
    PSMTXCopy(mDoMtx_stack_c::get(), mpModel2->getBaseTRMtx());
}

/* 00000A1C-00000AD0       .text set_minamo_mtx__9daWfall_cFv */
void daWfall_c::set_minamo_mtx() {
    /* Nonmatching */
}

/* 00000AD0-00000C94       .text _execute__9daWfall_cFv */
bool daWfall_c::_execute() {
    /* Nonmatching */
}

/* 00000C94-00000D20       .text mode_proc_call__9daWfall_cFv */
void daWfall_c::mode_proc_call() {
    typedef void (daWfall_c::*modeProc)();
    static modeProc mode_proc[] = {
        &daWfall_c::mode_wtr_on,
        &daWfall_c::mode_wtr_off,
    };

    (this->*mode_proc[mMode])();
}

/* 00000D20-00000D48       .text mode_wtr_on_init__9daWfall_cFv */
void daWfall_c::mode_wtr_on_init() {
    mMode = 0;
    if (m356 == 1) {
        mBrk.setPlaySpeed(-1.0f);
    }
}

/* 00000E14-00000EE8       .text mode_wtr_off__9daWfall_cFv */
void daWfall_c::mode_wtr_off() {
    cLib_addCalc(&m344.y, current.pos.z, 60.0f, 150.0f, 600.0f);
    f32 scale = getWaterScaleFromGatePos();
    m320 = scale;
    if (scale > 0.0f) {
        mBtk1.setPlaySpeed(1.0f);
        mBtk1.play();
        if (setEmitter00Pos() || setEmitter01Pos()) {
            set_se();
        }
    } else {
        if (mFollow1.getEmitter() != NULL) {
            mFollow1.getEmitter()->setStatus(1);
        }
        if (mFollow2.getEmitter() != NULL) {
            mFollow2.getEmitter()->setStatus(1);
        }
    }
}

/* 00000DEC-00000E14       .text mode_wtr_off_init__9daWfall_cFv */
void daWfall_c::mode_wtr_off_init() {
    mMode = 1;
    if (m356 == 1) {
        mBrk.setPlaySpeed(1.0f);
    }
}

/* 00000EE8-00000FF0       .text setEmitter00Pos__9daWfall_cFv */
BOOL daWfall_c::setEmitter00Pos() {
    BOOL ret = FALSE;

    m314 = current.pos;
    f32 waterHeight = getWaterHeight();
    if (waterHeight > m344.y) {
        if (mFollow1.getEmitter() != NULL) {
            mFollow1.getEmitter()->setStatus(1);
        }
    } else {
        if (mFollow1.getEmitter() != NULL) {
            mFollow1.getEmitter()->clearStatus(1);
        }
        ret = TRUE;
    }
    m314.y = waterHeight;

    f32 t = fabs(waterHeight - current.pos.z) / (m320 * 760.0f);
    if (t > 1.0f) {
        t = 1.0f;
    }
    if (t < 176.0f) {
        t = 176.0f;
    }
    m314.x = m314.x + m320 * 80.0f * (f32)asin(t);
    return ret;
}

/* 00000FF0-00001098       .text setEmitter01Pos__9daWfall_cFv */
BOOL daWfall_c::setEmitter01Pos() {
    BOOL ret = FALSE;

    f32 waterHeight = getWaterHeight();
    if (waterHeight > m344.y) {
        if (mFollow2.getEmitter() != NULL) {
            mFollow2.getEmitter()->setStatus(1);
        }
    } else {
        if (mFollow2.getEmitter() != NULL) {
            mFollow2.getEmitter()->clearStatus(1);
        }
        ret = TRUE;
    }
    m324 = current.pos.z - 760.0f * (1.0f - m320);
    return ret;
}

/* 00001098-000010D8       .text getWaterScaleFromGatePos__9daWfall_cFv */
f32 daWfall_c::getWaterScaleFromGatePos() {
    f32 scale = m344.y - current.pos.z;
    if (scale < 0.0f) {
        scale = 0.0f;
    }
    scale /= 760.0f;
    if (scale > 1.0f) {
        scale = 1.0f;
    }
    return scale;
}

/* 000010D8-0000124C       .text getWaterHeight__9daWfall_cFv */
f32 daWfall_c::getWaterHeight() {
    /* Nonmatching */
}

/* 00001370-000013E0       .text set_se__9daWfall_cFv */
void daWfall_c::set_se() {
    JAIZelBasic::zel_basic->seStart(0x701F, &m344, 0, dComIfGp_getReverb((s8)current.roomNo), 1.0f, 1.0f, -1.0f, -1.0f, 0);
}

/* 000013E0-00001400       .text daWfall_Create__FPv */
static cPhs_State daWfall_Create(void* i_this) {
    return ((daWfall_c*)i_this)->_create();
}

/* 00001400-00001424       .text daWfall_Delete__FPv */
static BOOL daWfall_Delete(void* i_this) {
    return ((daWfall_c*)i_this)->_delete();
}

/* 00001424-00001550       .text daWfall_Draw__FPv */
static BOOL daWfall_Draw(void*) {
    /* Nonmatching */
}

/* 00001550-00001574       .text daWfall_Execute__FPv */
static BOOL daWfall_Execute(void* i_this) {
    return ((daWfall_c*)i_this)->_execute();
}

/* 00001574-0000157C       .text daWfall_IsDelete__FPv */
static BOOL daWfall_IsDelete(void*) {
    return TRUE;
}

static actor_method_class daWfallMethodTable = {
    (process_method_func)daWfall_Create,
    (process_method_func)daWfall_Delete,
    (process_method_func)daWfall_Execute,
    (process_method_func)daWfall_IsDelete,
    (process_method_func)daWfall_Draw,
};

actor_process_profile_definition g_profile_WATERFALL = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_WATERFALL_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daWfall_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_WATERFALL_e,
    /* Actor SubMtd */ &daWfallMethodTable,
    /* Status       */ fopAcStts_CULL_e | fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
