//
// Generated by dtk
// Translation Unit: d_a_npc_auction.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_npc_auction.h"
#include "d/actor/d_a_auction.h"
#include "d/d_com_lib_game.h"
#include "d/d_com_inf_game.h"
#include "d/d_snap.h"
#include "m_Do/m_Do_ext.h"
#include "res/Object/Auc.h"
#include "res/Object/Rs2.h"

// daAuction_c members needed by this actor (d_a_auction.h keeps them private)
struct daAuction_Access_c {
    /* 0x000 */ u8 mPad[0x738];
    /* 0x738 */ fpc_ProcID mNpcID[8];
    /* 0x758 */ u8 mPad2[0x80C - 0x758];
    /* 0x80C */ u8 mNpcNoTbl[8];
    /* 0x814 */ u8 mAucMdlNo[8];
    /* 0x81C */ u8 mPrevNpcNo;
    /* 0x81D */ u8 mPrevNpcNo2;
    /* 0x81E */ u8 m81E;
    /* 0x81F */ u8 m81F;
    /* 0x820 */ u8 mNpcFlag;
    /* 0x821 */ u8 m821;
    /* 0x822 */ u8 m822;
    /* 0x823 */ u8 mCurrAuctionItemIndex;
    /* 0x824 */ u8 m824;
    /* 0x825 */ u8 m825;
    /* 0x826 */ u8 m826;
    /* 0x827 */ u8 m827;
    /* 0x828 */ u8 m828;
    /* 0x829 */ u8 m829;
    /* 0x82A */ u8 m82A;
    /* 0x82B */ u8 m82B;
    /* 0x82C */ u8 m82C;
    /* 0x82D */ u8 mCurLinkAnm;
    /* 0x82E */ u8 m82E;
    /* 0x82F */ u8 m82F;
    /* 0x830 */ u8 m830;
    /* 0x831 */ u8 m831;
    /* 0x832 */ u8 m832;
    /* 0x833 */ u8 mFace;
    /* 0x834 */ u8 m834;
};

#define AUC ((daAuction_Access_c*)(auction))

/* 00000000-00000004       .rodata m_arcname__14daNpcAuction_c */
const char daNpcAuction_c::m_arcname[] = "Auc";

/* 00000004-00000034       .rodata l_bmd_ix_tbl */
static const int l_bmd_ix_tbl[] = {
    dRes_ID_AUC_BDL_UM_e,
    dRes_ID_AUC_BDL_UW_e,
    dRes_ID_AUC_BDL_UO_e,
    dRes_ID_AUC_BDL_UO_e,
    dRes_ID_AUC_BDL_UO_e,
    dRes_ID_AUC_BDL_UB_e,
    dRes_ID_AUC_BDL_UB_e,
    dRes_ID_AUC_BDL_UB_e,
    dRes_ID_AUC_BDL_UB_e,
    dRes_ID_AUC_BDL_SA_e,
    dRes_ID_RS2_BDL_RS_e,
    dRes_ID_RS2_BDL_RS_e,
};

/* 00000034-00000064       .rodata l_head_bmd_ix_tbl */
static const int l_head_bmd_ix_tbl[] = {
    dRes_ID_AUC_BDL_UM01_HEAD_e,
    dRes_ID_AUC_BDL_UW02_HEAD_e,
    dRes_ID_AUC_BDL_UO01_HEAD_e,
    dRes_ID_AUC_BDL_UO02_HEAD_e,
    dRes_ID_AUC_BDL_UO03_HEAD_e,
    dRes_ID_AUC_BDL_UB01_HEAD_e,
    dRes_ID_AUC_BDL_UB02_HEAD_e,
    dRes_ID_AUC_BDL_UB03_HEAD_e,
    dRes_ID_AUC_BDL_UB04_HEAD_e,
    dRes_ID_AUC_BDL_SA02_HEAD_e,
    -1,
    -1,
};

/* 00000064-00000070       .rodata l_photo_no */
static const char l_photo_no[12] = {'d', 'g', 'h', 'i', 'j', 'k', 'k', 'l', 'm', 'n', '_', '_'};

/* 00000070-00000250       .rodata l_bck_ix_tbl */
static const int l_bck_ix_tbl[][10] = {
    {
        dRes_ID_AUC_BCK_UM_WAIT01_e,
        dRes_ID_AUC_BCK_UM_TALK01_e,
        dRes_ID_AUC_BCK_UM_NEWSATU_e,
        dRes_ID_AUC_BCK_UM_DOUSHO_e,
        dRes_ID_AUC_BCK_UM_KUYASI_e,
        dRes_ID_AUC_BCK_UM_GET_e,
        dRes_ID_AUC_BCK_UM_WAIT01_e,
        dRes_ID_AUC_BCK_UM_WAIT01_e,
        dRes_ID_AUC_BCK_UM_HAPPY_e,
        dRes_ID_AUC_BCK_UM_WAIT01_e,
    },
    {
        dRes_ID_AUC_BCK_UW_WAIT02_e,
        dRes_ID_AUC_BCK_UW_TALK02_e,
        dRes_ID_AUC_BCK_UW_NEWSATU_e,
        dRes_ID_AUC_BCK_UW_DOUSHO_e,
        dRes_ID_AUC_BCK_UW_KUYASI_e,
        dRes_ID_AUC_BCK_UW_GET_e,
        dRes_ID_AUC_BCK_UW_WAIT02_e,
        dRes_ID_AUC_BCK_UW_WAIT02_e,
        dRes_ID_AUC_BCK_UW_HAPPY_e,
        dRes_ID_AUC_BCK_UW_02HOKAN_e,
    },
    {
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_TALK01_e,
        dRes_ID_AUC_BCK_UO_NEWSATU_e,
        dRes_ID_AUC_BCK_UO_DOUSHO_e,
        dRes_ID_AUC_BCK_UO_KUYASI_e,
        dRes_ID_AUC_BCK_UO_GET_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_TALK01_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
    },
    {
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_TALK01_e,
        dRes_ID_AUC_BCK_UO_NEWSATU_e,
        dRes_ID_AUC_BCK_UO_DOUSHO_e,
        dRes_ID_AUC_BCK_UO_KUYASI_e,
        dRes_ID_AUC_BCK_UO_GET_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_TALK01_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
    },
    {
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_TALK01_e,
        dRes_ID_AUC_BCK_UO_NEWSATU_e,
        dRes_ID_AUC_BCK_UO_DOUSHO_e,
        dRes_ID_AUC_BCK_UO_KUYASI_e,
        dRes_ID_AUC_BCK_UO_GET_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
        dRes_ID_AUC_BCK_UO_TALK01_e,
        dRes_ID_AUC_BCK_UO_WAIT01_e,
    },
    {
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_TALK01_e,
        dRes_ID_AUC_BCK_UB_NEWSATU_e,
        dRes_ID_AUC_BCK_UB_DOUSHO_e,
        dRes_ID_AUC_BCK_UB_KUYASI_e,
        dRes_ID_AUC_BCK_UB_GET_e,
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_TALK01_e,
        dRes_ID_AUC_BCK_UB_YADA_e,
    },
    {
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_TALK01_e,
        dRes_ID_AUC_BCK_UB_NEWSATU_e,
        dRes_ID_AUC_BCK_UB_DOUSHO_e,
        dRes_ID_AUC_BCK_UB_KUYASI_e,
        dRes_ID_AUC_BCK_UB_GET_e,
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_TALK01_e,
        dRes_ID_AUC_BCK_UB_YADA_e,
    },
    {
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_TALK01_e,
        dRes_ID_AUC_BCK_UB_NEWSATU_e,
        dRes_ID_AUC_BCK_UB_DOUSHO_e,
        dRes_ID_AUC_BCK_UB_KUYASI_e,
        dRes_ID_AUC_BCK_UB_GET_e,
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_TALK01_e,
        dRes_ID_AUC_BCK_UB_YADA_e,
    },
    {
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_TALK01_e,
        dRes_ID_AUC_BCK_UB_NEWSATU_e,
        dRes_ID_AUC_BCK_UB_DOUSHO_e,
        dRes_ID_AUC_BCK_UB_KUYASI_e,
        dRes_ID_AUC_BCK_UB_GET_e,
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_WAIT01_e,
        dRes_ID_AUC_BCK_UB_TALK01_e,
        dRes_ID_AUC_BCK_UB_YADA_e,
    },
    {
        dRes_ID_AUC_BCK_SA_WAIT01_e,
        dRes_ID_AUC_BCK_SA_TALK01_e,
        dRes_ID_AUC_BCK_SA_NEWSATU_e,
        dRes_ID_AUC_BCK_SA_DOUSHO_e,
        dRes_ID_AUC_BCK_SA_KUYASI_e,
        dRes_ID_AUC_BCK_SA_GET_e,
        dRes_ID_AUC_BCK_SA_WAIT01_e,
        dRes_ID_AUC_BCK_SA_WAIT01_e,
        dRes_ID_AUC_BCK_SA_TALK01_e,
        dRes_ID_AUC_BCK_SA_WAIT01_e,
    },
    {
        dRes_ID_RS2_BCK_RS_WAIT01_e,
        dRes_ID_RS2_BCK_RS_TALK01_e,
        dRes_ID_RS2_BCK_RS_TALK02_e,
        dRes_ID_RS2_BCK_RS_TALK03_e,
        dRes_ID_RS2_BCK_RS_SWING_e,
        dRes_ID_RS2_BCK_RS_TAME_e,
        dRes_ID_RS2_BCK_RS_JAMP_e,
        dRes_ID_RS2_BCK_RS_WAIT01_e,
        dRes_ID_RS2_BCK_RS_WAIT01_e,
        dRes_ID_RS2_BCK_RS_JAMP_e,
    },
    {
        dRes_ID_RS2_BCK_RS_WAIT02_e,
        dRes_ID_RS2_BCK_RS_TALK01_e,
        dRes_ID_RS2_BCK_RS_TALK02_e,
        dRes_ID_RS2_BCK_RS_TALK03_e,
        dRes_ID_RS2_BCK_RS_SWING_e,
        dRes_ID_RS2_BCK_RS_TAME_e,
        dRes_ID_RS2_BCK_RS_JAMP_e,
        dRes_ID_RS2_BCK_RS_WAIT02_e,
        dRes_ID_RS2_BCK_RS_WAIT02_e,
        dRes_ID_RS2_BCK_RS_JAMP_e,
    },
};

/* 00000250-00000280       .rodata l_btp_ix_tbl */
static const int l_btp_ix_tbl[] = {
    dRes_ID_AUC_BTP_UM01_MABA_e,
    dRes_ID_AUC_BTP_UW02_MABA_e,
    dRes_ID_AUC_BTP_UO01_MABA_e,
    dRes_ID_AUC_BTP_UO02_MABA_e,
    dRes_ID_AUC_BTP_UO03_MABA_e,
    dRes_ID_AUC_BTP_UB01_MABA_e,
    dRes_ID_AUC_BTP_UB02_MABA_e,
    dRes_ID_AUC_BTP_UB03_MABA_e,
    dRes_ID_AUC_BTP_UB04_MABA_e,
    dRes_ID_AUC_BTP_SA02_MABA_e,
    dRes_ID_RS2_BTP_RS_MABA01_e,
    dRes_ID_RS2_BTP_RS_MABA01_e,
};

/* 00000280-000002B0       .rodata l_bmt_ix_tbl */
static const int l_bmt_ix_tbl[] = {
    -1,
    dRes_ID_AUC_BMT_UW02_e,
    -1,
    dRes_ID_AUC_BMT_UO02_e,
    dRes_ID_AUC_BMT_UO03_e,
    -1,
    dRes_ID_AUC_BMT_UB02_e,
    dRes_ID_AUC_BMT_UB03_e,
    dRes_ID_AUC_BMT_UB04_e,
    dRes_ID_AUC_BMT_SA02_e,
    -1,
    -1,
};

/* 000002B0-000002E0       .rodata l_diff_flag_tbl */
static const u32 l_diff_flag_tbl[] = {
    0x11000002,
    0x15021222,
    0x11000002,
    0x15021222,
    0x15021222,
    0x11000002,
    0x15021222,
    0x15021222,
    0x15021222,
    0x15021222,
    0x11020022,
    0x11020022,
};

/* 000002E0-00000320       .rodata l_kind_max */
static const int l_kind_max[][2] = {
    { 0x0A, 0x0A },
    { 0x00, 0x01 },
    { 0x02, 0x04 },
    { 0x02, 0x04 },
    { 0x05, 0x08 },
    { 0x05, 0x08 },
    { 0x09, 0x09 },
    { 0x0B, 0x0B },
};

/* 00000030-00000060       .data l_arcname_tbl */
static char* l_arcname_tbl[] = {
    "Auc",
    "Auc",
    "Auc",
    "Auc",
    "Auc",
    "Auc",
    "Auc",
    "Auc",
    "Auc",
    "Auc",
    "Rs2",
    "Rs2",
};

/* 00000060-00000064       .data l_npc_anm_0 */
static sAnmDat l_npc_anm_0[] = {
    { 0x00, 0x08, 0xFF },
};

/* 00000064-00000068       .data l_npc_anm_2 */
static sAnmDat l_npc_anm_2[] = {
    { 0x01, 0x08, 0xFF },
};

/* 00000068-0000006C       .data l_npc_anm_3 */
static sAnmDat l_npc_anm_3[] = {
    { 0x02, 0x08, 0xFF },
};

/* 0000006C-00000074       .data l_npc_anm_4 */
static sAnmDat l_npc_anm_4[] = {
    { 0x02, 0x08, 0x02 },
    { 0x00, 0x08, 0xFF },
};

/* 00000074-00000078       .data l_npc_anm_5 */
static sAnmDat l_npc_anm_5[] = {
    { 0x03, 0x08, 0xFF },
};

/* 00000078-00000084       .data l_npc_anm_6 */
static sAnmDat l_npc_anm_6[] = {
    { 0x05, 0x08, 0x05 },
    { 0x06, 0x08, 0x01 },
    { 0x00, 0x08, 0xFF },
};

/* 00000084-00000088       .data l_npc_anm_7 */
static sAnmDat l_npc_anm_7[] = {
    { 0x04, 0x08, 0xFF },
};

/* 00000088-0000008C       .data l_npc_anm_wait */
static sAnmDat l_npc_anm_wait[] = {
    { 0x00, 0x08, 0xFF },
};

/* 0000008C-00000090       .data l_npc_anm_talk */
static sAnmDat l_npc_anm_talk[] = {
    { 0x01, 0x08, 0xFF },
};

/* 00000090-00000098       .data l_npc_anm_talk2 */
static sAnmDat l_npc_anm_talk2[] = {
    { 0x09, 0x08, 0x01 },
    { 0x01, 0x08, 0xFF },
};

/* 00000098-0000009C       .data l_npc_anm_kuyasi */
static sAnmDat l_npc_anm_kuyasi[] = {
    { 0x04, 0x08, 0xFF },
};

/* 0000009C-000000A0       .data l_npc_anm_happy */
static sAnmDat l_npc_anm_happy[] = {
    { 0x08, 0x08, 0xFF },
};

/* 000000A0-000000A4       .data l_npc_anm_dousho */
static sAnmDat l_npc_anm_dousho[] = {
    { 0x03, 0x08, 0xFF },
};

/* 000000A4-00000134       .data l_npc_msg_id */
static u32 l_npc_msg_id[12][3] = {
    { 0x1D26, 0x1D27, 0x1D28 },
    { 0x1D29, 0x1D2A, 0x1D2B },
    { 0x1D2C, 0x1D2D, 0x1D2E },
    { 0x1D2F, 0x1D30, 0x1D31 },
    { 0x1D32, 0x1D33, 0x1D34 },
    { 0x3391, 0x3392, 0x3393 },
    { 0x3394, 0x3395, 0x3396 },
    { 0x3397, 0x3398, 0x3399 },
    { 0x339A, 0x339B, 0x339C },
    { 0x1D38, 0x1D39, 0x1D39 },
    { 0, 0, 0 },
    { 0, 0, 0 },
};

/* 00000134-00000154       .data l_npc_staff_id */
static char* l_npc_staff_id[] = {
    "Auc7",
    "Auc1",
    "Auc2",
    "Auc3",
    "Auc4",
    "Auc5",
    "Auc6",
    "Auc0",
};

static BOOL daNpc_Auction_nodeCallBack1(J3DNode*, int);
static BOOL daNpc_Auction_nodeCallBack2(J3DNode*, int);
static cPhs_State phase_1(daNpcAuction_c*);
static cPhs_State phase_2(daNpcAuction_c*);

/* 00000154-00000174       .data l_node_call_back_tbl */
static J3DNodeCallBack l_node_call_back_tbl[] = {
    daNpc_Auction_nodeCallBack1,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack1,
};

/* 000000DC-0000034C       .bss l_npc_dat */
static daNpc_Auction2_HIO_c l_npc_dat[] = {
    daNpc_Auction2_HIO_c(0.0f, 0x0FA0, 0x0000, 0x1F40, 0x1F40, -0x0E74, 0x0000, -0x1F40, -0x1F40,
                         0x05DC, 0x06A4, 195.0f, 0x7FFF, 0, 0.0f, 160.0f, 10.0f, 185.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x0FA0, 0x0000, 0x0FA0, 0x1B58, -0x0FA0, 0x0000, -0x1B58, -0x1F40,
                         0x03E8, 0x05DC, 180.0f, 0x7FFF, 0, 0.0f, 150.0f, 5.0f, 180.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x0FA0, 0x0000, 0x1F40, 0x1F40, -0x1B58, 0x0000, -0x1F40, -0x1F40,
                         0x03E8, 0x0514, 175.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 175.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x0FA0, 0x0000, 0x1388, 0x1F40, -0x0DAC, 0x0000, -0x1388, -0x1F40,
                         0x03E8, 0x05DC, 170.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 170.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x0FA0, 0x0000, 0x2328, 0x1388, -0x1388, 0x0000, -0x2328, -0x1388,
                         0x07D0, 0x05DC, 175.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 175.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x09C4, 0x0000, 0x1B58, 0x1B58, -0x03E8, 0x0000, -0x1B58, -0x1B58,
                         0x02BC, 0x0514, 190.0f, 0x7FFF, 0, 0.0f, 150.0f, 15.0f, 190.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x09C4, 0x0000, 0x1B58, 0x1B58, -0x03E8, 0x0000, -0x1B58, -0x1B58,
                         0x02BC, 0x0514, 165.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 165.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x0FA0, 0x0000, 0x2328, 0x1770, -0x03E8, 0x0000, -0x2328, -0x1770,
                         0x07D0, 0x05DC, 175.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 175.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x0FA0, 0x0000, 0x1F40, 0x1388, -0x0FA0, 0x0000, -0x1F40, -0x1388,
                         0x07D0, 0x09C4, 180.0f, 0x7FFF, 0, 0.0f, 150.0f, 10.0f, 180.0f),
    daNpc_Auction2_HIO_c(0.0f, 0x09C4, 0x07D0, 0x1770, 0x1F40, -0x01F4, -0x07D0, -0x1770, -0x1F40,
                         0x03E8, 0x05DC, 210.0f, 0x7FFF, 0, 0.0f, 180.0f, 0.0f, 210.0f),
    daNpc_Auction2_HIO_c(-20.0f, 0x0200, 0x1388, 0x0200, 0x1770, -0x0200, -0x1388, -0x0200,
                         -0x1770, 0x1000, 0x0800, 165.0f, 0x7FFF, 0, 400.0f, 80.0f, 0.0f, 120.0f),
    daNpc_Auction2_HIO_c(-20.0f, 0x0200, 0x1388, 0x0200, 0x1770, -0x0200, -0x1388, -0x0200,
                         -0x1770, 0x1000, 0x0800, 140.0f, 0x7FFF, 0, 0.0f, 80.0f, 0.0f, 120.0f),
};

/* 000000EC-00000268       .text __ct__14daNpcAuction_cFv */
daNpcAuction_c::daNpcAuction_c() {
    m745 = 0;
    mEmitter = NULL;
    *(u32*)&m704[0] = 0;
    m747 = 0;
    mpAnmDat = NULL;
    mAnmNo = 0;
    m744 = 1;
    mSoundTimer = 0;
}

/* 00000618-00000730       .text daNpc_Auction_nodeCallBack1__FP7J3DNodei */
static BOOL daNpc_Auction_nodeCallBack1(J3DNode* node, int calcTiming) {
    if (calcTiming == 0) {
        J3DModel* model = j3dSys.getModel();
        daNpcAuction_c* i_this = (daNpcAuction_c*)model->getUserArea();
        J3DJoint* joint = (J3DJoint*)node;
        s32 jntNo = joint->getJntNo();

        MTXCopy(model->getAnmMtx(jntNo), *calc_mtx);

        if (jntNo == i_this->m_jnt.getHeadJntNum()) {
            mDoMtx_YrotM(*calc_mtx, (s16)-i_this->m_jnt.getHead_y());
            mDoMtx_ZrotM(*calc_mtx, (s16)-i_this->m_jnt.getHead_x());
        }
        if (jntNo == i_this->m_jnt.getBackboneJntNum()) {
            mDoMtx_XrotM(*calc_mtx, (s16)i_this->m_jnt.getBackbone_y());
            mDoMtx_ZrotM(*calc_mtx, (s16)i_this->m_jnt.getBackbone_x());
        }

        model->setAnmMtx(jntNo, *calc_mtx);
        MTXCopy(*calc_mtx, J3DSys::mCurrentMtx);
    }
    return TRUE;
}

/* 00000730-00000848       .text daNpc_Auction_nodeCallBack2__FP7J3DNodei */
static BOOL daNpc_Auction_nodeCallBack2(J3DNode* node, int calcTiming) {
    if (calcTiming == 0) {
        J3DModel* model = j3dSys.getModel();
        daNpcAuction_c* i_this = (daNpcAuction_c*)model->getUserArea();
        J3DJoint* joint = (J3DJoint*)node;
        s32 jntNo = joint->getJntNo();

        MTXCopy(model->getAnmMtx(jntNo), *calc_mtx);

        if (jntNo == i_this->m_jnt.getHeadJntNum()) {
            mDoMtx_XrotM(*calc_mtx, (s16)i_this->m_jnt.getHead_y());
            mDoMtx_ZrotM(*calc_mtx, (s16)-i_this->m_jnt.getHead_x());
        }
        if (jntNo == i_this->m_jnt.getBackboneJntNum()) {
            mDoMtx_XrotM(*calc_mtx, (s16)i_this->m_jnt.getBackbone_y());
            mDoMtx_ZrotM(*calc_mtx, (s16)-i_this->m_jnt.getBackbone_x());
        }

        model->setAnmMtx(jntNo, *calc_mtx);
        MTXCopy(*calc_mtx, J3DSys::mCurrentMtx);
    }
    return TRUE;
}

/* 00000848-00000868       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c* i_this) {
    return static_cast<daNpcAuction_c*>(i_this)->createHeap();
}

/* 00000868-00000ACC       .text phase_1__FP14daNpcAuction_c */
/* Nonmatching */
static cPhs_State phase_1(daNpcAuction_c* i_this) {
    fopAc_ac_c* auction;
    u8 npc_no;
    u8 kind;

    if (!(i_this->actor_condition & 8)) {
        new (i_this) daNpcAuction_c();
        i_this->actor_condition |= 8;
    }
    if (fopAcM_SearchByName(fpcNm_AUCTION_e, &auction) == 0) {
        return cPhs_INIT_e;
    }
    if (auction == NULL) {
        return cPhs_INIT_e;
    }
    npc_no = AUC->mNpcNoTbl[i_this->getPrmNpcNo()];
    i_this->mNpcNo = npc_no;
    s32 procID = fopAcM_GetID(i_this);
    BOOL id_free;
    if (AUC->mNpcID[npc_no] == -1) {
        AUC->mNpcID[npc_no] = procID;
        id_free = TRUE;
    } else {
        id_free = FALSE;
    }
    if (!id_free) {
        return cPhs_INIT_e;
    }
    kind = l_kind_max[npc_no][0];
    u8 max = l_kind_max[npc_no][1];
    if (npc_no == 2 || npc_no == 3) {
        if (AUC->mPrevNpcNo == 0xFF) {
            kind = kind + i_this->getRand((max - kind) + 1);
            AUC->mPrevNpcNo = kind;
        } else {
            kind = kind + i_this->getRand((max - kind) + 1);
            if (kind == AUC->mPrevNpcNo) {
                if (kind == max) {
                    kind -= 1;
                } else {
                    kind += 1;
                }
            }
        }
    } else if (npc_no == 4 || npc_no == 5) {
        if (AUC->mPrevNpcNo2 == 0xFF) {
            kind = kind + i_this->getRand((max - kind) + 1);
            AUC->mPrevNpcNo2 = kind;
        } else {
            kind = kind + i_this->getRand((max - kind) + 1);
            if (kind == AUC->mPrevNpcNo2) {
                if (kind == max) {
                    kind -= 1;
                } else {
                    kind += 1;
                }
            }
        }
    } else {
        kind = kind + i_this->getRand((max - kind) + 1);
    }
    i_this->mDataNo = kind;
    AUC->mAucMdlNo[npc_no] = kind;
    i_this->mBtpNo = l_btp_ix_tbl[kind];
    i_this->mBmtNo = l_bmt_ix_tbl[kind];
    return cPhs_NEXT_e;
}

/* 00000ACC-00000B4C       .text phase_2__FP14daNpcAuction_c */
static cPhs_State phase_2(daNpcAuction_c* i_this) {
    cPhs_State state = dComIfG_resLoad(&i_this->mPhsArcname, l_arcname_tbl[i_this->mDataNo]);
    if (state == cPhs_COMPLEATE_e) {
        if (fopAcM_entrySolidHeap(i_this, CheckCreateHeap, 0x10000)) {
            return i_this->createInit();
        }
        i_this->mpMorf = NULL;
        state = cPhs_ERROR_e;
    }
    return state;
}

/* 00000B4C-00000E74       .text createHeap__14daNpcAuction_cFv */
BOOL daNpcAuction_c::createHeap() {
    J3DModelData* bmd = (J3DModelData*)dComIfG_getObjectIDRes(
        l_arcname_tbl[mDataNo], (u16)l_bmd_ix_tbl[mDataNo]);
    mDoExt_McaMorf* morf = new mDoExt_McaMorf(
        bmd, NULL, NULL,
        (J3DAnmTransform*)dComIfG_getObjectIDRes(
            l_arcname_tbl[mDataNo], (u16)l_bck_ix_tbl[mDataNo][mAnmNo]),
        J3DFrameCtrl::EMode_LOOP, 1.0f, 0, -1, 1, NULL, 0x80000, l_diff_flag_tbl[mDataNo]);
    mpMorf = morf;
    if (mpMorf == NULL || mpMorf->getModel() == NULL) {
        return FALSE;
    }
    if (l_head_bmd_ix_tbl[mDataNo] >= 0) {
        mHeadModel = mDoExt_J3DModel__create(
            (J3DModelData*)dComIfG_getObjectIDRes(
                l_arcname_tbl[mDataNo], (u16)l_head_bmd_ix_tbl[mDataNo]),
            0x80000, 0x15020022);
        if (mHeadModel == NULL) {
            return FALSE;
        }
    }
    m_jnt.setHeadJntNum(bmd->getJointName()->getIndex("head"));
    JUT_ASSERT(1116, m_jnt.getHeadJntNum() >= 0);
    m_jnt.setBackboneJntNum(bmd->getJointName()->getIndex("backbone"));
    JUT_ASSERT(1120, m_jnt.getBackboneJntNum() >= 0);
    if (!initTexPatternAnm(false)) {
        return FALSE;
    }
    for (u16 i = 0; i < bmd->getJointNum(); i++) {
        if (i == m_jnt.getHeadJntNum() || i == m_jnt.getBackboneJntNum()) {
            bmd->getJointNodePointer(i)->setCallBack(l_node_call_back_tbl[mNpcNo]);
        }
    }
    mpMorf->getModel()->setUserArea((u32)this);
    mAcchCir.SetWall(30.0f, 30.0f);
    mObjAcch.Set(&current.pos, &old.pos, this, 1, &mAcchCir, &speed, &old.angle, &shape_angle);
    return TRUE;
}

/* 00000E74-00000E94       .text daNpcAuction_XyCheckCB__FPvi */
static s16 daNpcAuction_XyCheckCB(void* i_this, int i_itemBtn) {
    return ((daNpcAuction_c*)i_this)->XyCheckCB(i_itemBtn);
}

/* 00000E94-00000EB4       .text daNpcAuction_XyEventCB__FPvi */
static s16 daNpcAuction_XyEventCB(void* i_this, int i_itemBtn) {
    return ((daNpcAuction_c*)i_this)->XyEventCB(i_itemBtn);
}

/* 00000EB4-00001038       .text createInit__14daNpcAuction_cFv */
cPhs_State daNpcAuction_c::createInit() {
    gravity = -9.0f;
    mEventCut.setActorInfo2(l_npc_staff_id[mNpcNo], this);
    mAngleY = 0;
    m73C = 0;
    m73D = 0;
    cullMtx = mpMorf->getModel()->getBaseTRMtx();
    wait_action_init();
    if (mNpcNo == 0) {
        attention_info.distances[1] = 173;
        attention_info.distances[3] = 173;
    } else {
        attention_info.distances[1] = 169;
        attention_info.distances[3] = 169;
    }
    attention_info.flags = 0xA;
    mEventIdx = dComIfGp_evmng_getEventIdx("AUCTION_TALK", 0xFF);
    eventInfo.setEventName("AUCTION_TALK_XY");
    eventInfo.setXyCheckCB(daNpcAuction_XyCheckCB);
    eventInfo.setXyEventCB(daNpcAuction_XyEventCB);
    m720 = l_npc_dat[mDataNo].mMaxAttnDistXZ;
    setMtx();
    mpMorf->getModel()->calc();
    mStts.Init(0xFF, 0xFF, this);
    mCyl.Set(dNpc_cyl_src);
    mCyl.SetStts(&mStts);
    setCollision(60.0f, 150.0f);
    return cPhs_COMPLEATE_e;
}

/* 00001038-0000105C       .text wait_action_init__14daNpcAuction_cFv */
void daNpcAuction_c::wait_action_init() {
    setAction(&daNpcAuction_c::wait_action);
}

/* 0000105C-00001194       .text wait_action__14daNpcAuction_cFv */
void daNpcAuction_c::wait_action() {
    if (m73D != 0) {
        m73E = 1;
    } else {
        m73E = 0;
    }
    if (m73C == 1) {
        if (talk(1) == fopMsgStts_BOX_CLOSED_e) {
            m73C = 0;
            setAnm2(7, 2, 8.0f);
            if (m745 == 0) {
                dComIfGp_event_onEventFlag(8);
            } else if (mNpcNo == 0) {
                daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
                if (auction != NULL) {
                    if (m745 == 1) {
                        AUC->m821 = 1;
                    } else if (m745 == 2) {
                        AUC->m821 = 2;
                        AUC->mCurrAuctionItemIndex = m743;
                    }
                }
            }
        }
        setAnmFromMsgTag();
    }
    if (mAnmNo == 0) {
        setAnm2(7, 2, 8.0f);
    }
}

/* 00001194-000011EC       .text checkOrder__14daNpcAuction_cFv */
void daNpcAuction_c::checkOrder() {
    u16 talkState = eventInfo.getCommand();
    if (talkState == 2) {
        m73E = 0;
        return;
    }
    if (talkState == 1) {
        if ((m73E == 2 || m73E == 1) && m73C == 0 && m745 == 0) {
            m73C = 1;
        }
    }
}

/* 000011EC-00001270       .text eventOrder__14daNpcAuction_cFv */
void daNpcAuction_c::eventOrder() {
    if (m73E == 2 || m73E == 1) {
        eventInfo.onCondition(dEvtCnd_CANTALK_e);
        if (dComIfGs_isEventBit(dSv_event_flag_c::UNK_1404)) {
            eventInfo.onCondition(0x20);
        }
        if (m73E == 2) {
            fopAcM_orderSpeakEvent(this);
        }
    }
}

/* 00001270-000013FC       .text eventMove__14daNpcAuction_cFv */
/* Nonmatching */
void daNpcAuction_c::eventMove() {
    dEvent_manager_c* evm = dComIfGp_getPEvtManager();
    if (evm->endCheckOld("AUCTION_END2") || evm->endCheckOld("AUCTION_NO_ITEM") ||
        evm->endCheckOld("AUCTION_GET_ITEM")) {
        m720 = 200.0f;
        return;
    }
    if (evm->endCheckOld("AUCTION_TALK")) {
        if (m745 == 0) {
            dComIfGp_event_onEventFlag(8);
        } else if (mNpcNo == 0) {
            daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
            if (auction != NULL) {
                if (m745 == 1) {
                    AUC->m821 = 1;
                } else if (m745 == 2) {
                    AUC->m821 = 2;
                    AUC->mCurrAuctionItemIndex = m743;
                }
            }
        }
        m744 = 1;
        m73C = 0;
        return;
    }
    bool cutIdx = mEventCut.getAttnFlag();
    if (mEventCut.cutProc()) {
        if (!mEventCut.getAttnFlag()) {
            mEventCut.setAttnFlag(cutIdx);
        }
    } else {
        privateCut();
        if (mNpcNo == 7) {
            setAnmFromMsgTag();
        }
    }
}

/* 000013FC-00001548       .text privateCut__14daNpcAuction_cFv */
/* Nonmatching */
void daNpcAuction_c::privateCut() {
    static char* cut_name_tbl[] = {
        "MAIN",
        "MES_SET",
    };
    dEvent_manager_c* evm = dComIfGp_getPEvtManager();
    s32 staffId = evm->getMyStaffId(l_npc_staff_id[mNpcNo], NULL, 0);
    if (staffId != -1) {
        mActIdx = evm->getMyActIdx(staffId, cut_name_tbl, 2, 1, 0);
        if ((s8)mActIdx == -1) {
            evm->cutEnd(staffId);
            return;
        }
        if (evm->getIsAddvance(staffId)) {
            switch ((s8)mActIdx) {
            case 0:
                eventMainInit();
                break;
            case 1:
                eventMesSetInit(staffId);
                break;
            }
        }
        int ret;
        switch ((s8)mActIdx) {
        case 0:
            ret = eventMain();
            break;
        case 1:
            ret = eventMesSet();
            break;
        default:
            ret = 1;
            break;
        }
        if ((u8)ret != 0) {
            evm->cutEnd(staffId);
        }
    }
}

/* 00001548-00001554       .text eventMainInit__14daNpcAuction_cFv */
void daNpcAuction_c::eventMainInit() {
    m749 = 1;
}

/* 00001554-00001888       .text eventMain__14daNpcAuction_cFv */
/* Nonmatching */
int daNpcAuction_c::eventMain() {
    daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
    u32 flags = AUC->m834;
    if (flags & 4) {
        if (!(m747 & 8)) {
            setAnm2(3, 2, 8.0f);
            m747 |= 8;
        }
    } else if (mNpcNo == AUC->m829) {
        if (flags & 1) {
            if (!(m747 & 4)) {
                setAnm2(2, 2, 8.0f);
                m747 |= 4;
            }
        } else if (flags & 8) {
            if (!(m747 & 0x10)) {
                setAnm2(4, 2, 8.0f);
                m747 |= 0x10;
            }
        } else if (flags & 0x20) {
            if (!(m747 & 0x40)) {
                setAnm2(6, 2, 8.0f);
                m747 |= 0x40;
            }
        } else if (flags & 0x10) {
            if (!(m747 & 0x20)) {
                setAnm2(5, 2, 8.0f);
                m747 |= 0x20;
            }
            m749 = 0;
        } else {
            m747 = 0;
            m749 = 0;
            if (mAnmNo != 0) {
                setAnm2(0, 2, 8.0f);
            }
        }
    } else {
        m747 = 0;
        m749 = 0;
        if (mAnmNo != 0) {
            setAnm2(0, 2, 8.0f);
        }
    }
    if (AUC->m834 & 4) {
        if (mEmitter == NULL) {
            mEmitter = dComIfGp_particle_set(0x819D, &current.pos, NULL, NULL, 0xFF, NULL, -1,
                                             NULL, NULL, NULL);
            if (mEmitter != NULL) {
                mEmitter->setStatus(0x40);
            }
        }
        if (mEmitter != NULL) {
            MTXCopy(mpMorf->getModel()->getAnmMtx(m_jnt.getHeadJntNum()), *calc_mtx);
            mDoMtx_ZrotM(*calc_mtx, -0x4000);
            PSMTXTrans(mDoMtx_stack_c::now, 0.0f, l_npc_dat[mDataNo].m2C, 0.0f);
            PSMTXConcat(*calc_mtx, mDoMtx_stack_c::now, *calc_mtx);
            JPASetRMtxTVecfromMtx(*calc_mtx, mEmitter->mGlobalRotation, mEmitter->mGlobalTranslation);
        }
    } else {
        clrEmitter();
    }
    return 0;
}

/* 00001888-000018FC       .text eventMesSetInit__14daNpcAuction_cFi */
void daNpcAuction_c::eventMesSetInit(int staffId) {
    s32* substance = (s32*)dComIfGp_getPEvtManager()->getMySubstanceP(staffId, "MsgNo", 3);
    if (substance != NULL) {
        mCurrMsgNo = *substance;
        return;
    }
    mCurrMsgNo = getMsg();
}

/* 000018FC-00001930       .text eventMesSet__14daNpcAuction_cFv */
int daNpcAuction_c::eventMesSet() {
    return talk(0) == fopMsgStts_BOX_CLOSED_e ? 1 : 0;
}

/* 00001930-00001938       .text XyCheckCB__14daNpcAuction_cFi */
s16 daNpcAuction_c::XyCheckCB(int) {
    return 0;
}

/* 00001938-000019F8       .text XyEventCB__14daNpcAuction_cFi */
s16 daNpcAuction_c::XyEventCB(int i_itemBtn) {
    s16 eventIdx = dComIfGp_evmng_getEventIdx("DEFAULT_TALK_XY", 0xFF);
    u8 button = dComIfGp_getSelectItem(i_itemBtn);
    if (button == 0x96) {
        if (!dComIfGs_isEventBit(dSv_event_flag_c::UNK_1008)) {
            eventIdx = mEventIdx;
            m744 = 0;
        }
    } else if (button == 0x97 && !dComIfGs_isEventBit(dSv_event_flag_c::UNK_1004)) {
        eventIdx = mEventIdx;
        m744 = 0;
    }
    return eventIdx;
}

/* 000019F8-00001CD4       .text next_msgStatus__14daNpcAuction_cFPUl */
u16 daNpcAuction_c::next_msgStatus(u32* i_msg_no) {
    daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
    u16 status = 0xF;
    switch (*i_msg_no) {
    case 0x27DA:
        *i_msg_no = 0x27DC;
        break;
    case 0x27DB:
        *i_msg_no = 0x27DF;
        break;
    case 0x27DC:
        *i_msg_no = 0x27DD;
        break;
    case 0x27DD:
        *i_msg_no = 0x27DE;
        break;
    case 0x27DE:
        *i_msg_no = 0x27DF;
        break;
    case 0x27DF:
        if (mpCurrMsg->mSelectNum == 0) {
            *i_msg_no = 0x27E1;
            dComIfGs_onEventBit(dSv_event_flag_c::UNK_1408);
        } else {
            *i_msg_no = 0x27E0;
        }
        break;
    case 0x27E1:
        *i_msg_no = 0x27E2;
        break;
    case 0x27E2:
        if (mpCurrMsg->mSelectNum == 0) {
            *i_msg_no = 0x27E3;
        } else {
            *i_msg_no = 0x27E4;
        }
        break;
    case 0x27E3:
        *i_msg_no = 0x27E9;
        break;
    case 0x27E4:
        *i_msg_no = 0x27E5;
        break;
    case 0x27E5:
        *i_msg_no = 0x27E6;
        break;
    case 0x27E6:
        *i_msg_no = 0x27E7;
        break;
    case 0x27E7:
        if (mpCurrMsg->mSelectNum == 0) {
            *i_msg_no = 0x27E9;
        } else {
            *i_msg_no = 0x27E8;
        }
        break;
    case 0x27E8:
        *i_msg_no = 0x27E5;
        break;
    case 0x27E9:
        m745 = 1;
        status = 0x10;
        break;
    case 0x27EB:
        status = 0x10;
        break;
    case 0x27EC:
        if (mpCurrMsg->mSelectNum == 0) {
            *i_msg_no = 0x27EE;
            dComIfGs_setReserveItemEmpty();
        } else {
            *i_msg_no = 0x27ED;
        }
        break;
    case 0x27EE:
        *i_msg_no = 0x27EF;
        break;
    case 0x27EF:
        m745 = 2;
        status = 0x10;
        break;
    case 0x1D35:
        *i_msg_no = 0x1D36;
        break;
    case 0x1D36:
        *i_msg_no = 0x1D37;
        break;
    case 0x1D37:
        if (AUC->m824 == 0) {
            *i_msg_no = 0x1D38;
        } else {
            *i_msg_no = 0x1D39;
        }
        break;
    default:
        status = 0x10;
        break;
    }
    return status;
}

/* 00001CD4-00001F04       .text getMsg__14daNpcAuction_cFv */
/* Nonmatching */
u32 daNpcAuction_c::getMsg() {
    if (mNpcNo == 0) {
        u8 state = dComIfGp_event_getTalkXYBtn();
        u8 is_xy_btn = 0;
        switch (state) {
        case 1:
        case 2:
        case 3:
            is_xy_btn = 1;
            break;
        }
        if (is_xy_btn) {
            if (dComIfGp_event_getPreItemNo() == 0x96) {
                if (!dComIfGs_isEventBit(dSv_event_flag_c::UNK_1008)) {
                    m743 = 0;
                    return 0x27EB;
                }
                return 0x27F7;
            } else if (dComIfGp_event_getPreItemNo() == 0x97) {
                if (!dComIfGs_isEventBit(dSv_event_flag_c::UNK_1004)) {
                    m743 = 1;
                    return 0x27EB;
                }
                return 0x27F7;
            }
            return 0x27EA;
        } else {
            if (dComIfGs_isEventBit(dSv_event_flag_c::ENDLESS_NIGHT) && !dComIfGs_checkGetItem(0x69)) {
                return 0x27F8;
            }
            if (dComIfGs_isEventBit(dSv_event_flag_c::UNK_1002)) {
                if (dComIfGs_isEventBit(dSv_event_flag_c::UNK_0F01) &&
                    dComIfGs_isEventBit(dSv_event_flag_c::UNK_1080) &&
                    dComIfGs_isEventBit(dSv_event_flag_c::UNK_1040) &&
                    dComIfGs_isEventBit(dSv_event_flag_c::UNK_1020)) {
                    return 0x27F0;
                }
                return 0x27DB;
            }
            dComIfGs_onEventBit(dSv_event_flag_c::UNK_1002);
            return 0x27DA;
        }
    }
    if (mNpcNo == 6) {
        return 0x1D35;
    }
    daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
    u8 npcNo = AUC->m824;
    if (npcNo == 0) {
        return l_npc_msg_id[mDataNo][0];
    }
    if (npcNo == mNpcNo) {
        return l_npc_msg_id[mDataNo][1];
    }
    return l_npc_msg_id[mDataNo][2];
}

/* 00001F04-00002070       .text setAnmFromMsgTag__14daNpcAuction_cFv */
/* Nonmatching */
void daNpcAuction_c::setAnmFromMsgTag() {
    u8 itemBtn = dComIfGp_getMesgAnimeAttrInfo();
    if (mNpcNo == 0 || mNpcNo == 7) {
        if (itemBtn <= 7) {
            switch (itemBtn) {
            case 0:
                setAnmTbl(l_npc_anm_0);
                break;
            case 1:
                setAnmTbl(l_npc_anm_2);
                break;
            case 2:
                setAnmTbl(l_npc_anm_3);
                break;
            case 3:
                setAnmTbl(l_npc_anm_4);
                break;
            case 4:
                setAnmTbl(l_npc_anm_5);
                break;
            case 5:
                setAnmTbl(l_npc_anm_6);
                m728 = 0x8DD;
                mSoundTimer = 0x64;
                break;
            case 6:
                setAnmTbl(l_npc_anm_7);
                break;
            case 7:
                break;
            }
        }
    } else if (itemBtn <= 7) {
        switch (itemBtn) {
        case 0:
            setAnmTbl(l_npc_anm_0);
            break;
        case 1:
            setAnmTbl(l_npc_anm_talk);
            break;
        case 2:
            setAnmTbl(l_npc_anm_kuyasi);
            break;
        case 3:
            setAnmTbl(l_npc_anm_happy);
            break;
        case 4:
            setAnmTbl(l_npc_anm_talk2);
            break;
        case 5:
            setAnmTbl(l_npc_anm_talk2);
            break;
        case 6:
        case 7:
            break;
        }
    }
    dComIfGp_clearMesgAnimeAttrInfo();
}

/* 000001D4-00000204       .data l_mdl_status */
static u32 l_mdl_status[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000027,
    0x00000027,
};

/* 00002070-00002090       .text getPrmNpcNo__14daNpcAuction_cFv */
u8 daNpcAuction_c::getPrmNpcNo() {
    s8 prm = argument;
    if (prm < 0 || prm >= 8) {
        return 0;
    }
    return (u8)prm;
}

/* 00002090-00002118       .text setMtx__14daNpcAuction_cFv */
void daNpcAuction_c::setMtx() {
    mpMorf->getModel()->setBaseScale(scale);
    PSMTXTrans(mDoMtx_stack_c::now, current.pos.x, current.pos.y, current.pos.z);
    mDoMtx_YrotM(mDoMtx_stack_c::now, current.angle.y);
    mpMorf->getModel()->setBaseTRMtx(mDoMtx_stack_c::now);
}

/* 00002118-00002488       .text lookBack__14daNpcAuction_cFv */
/* Nonmatching */
void daNpcAuction_c::lookBack() {
    f32 attnDist = l_npc_dat[mDataNo].mAttnYOffset;
    s16 angle = l_npc_dat[mDataNo].mMaxHeadTurnVel;
    s16 targetY = current.angle.y;
    cXyz* lookPos = NULL;
    bool lookMode = true;

    if (m749 != 0) {
        daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
        if (auction != NULL &&
            (eyePos.x != auction->eyePos.x || eyePos.y != auction->eyePos.y ||
             eyePos.z != auction->eyePos.z)) {
            cXyz pos = auction->eyePos;
            lookPos = &pos;
        }
    } else if (mEventCut.getAttnFlag()) {
        m_jnt.setTrn();
        cXyz pos = mEventCut.getAttnPos();
        lookPos = &pos;
        lookMode = false;
        if (m73D == 0) {
            m73D = 1;
        }
    } else {
        f32 dist = m720;
        int distAngle = l_npc_dat[mDataNo].mMaxAttnAngleY;
        int limitAngle = 0x4000;
        f32 d;
        s16 a;
        dNpc_calc_DisXZ_AngY(current.pos, g_dComIfG_gameInfo.play.getPlayerPtr(0)->current.pos, &d, &a);
        if (m73D != 0) {
            dist += 40.0f;
            limitAngle = 0x471C;
            distAngle += 0x71C;
        }
        a -= current.angle.y;
        if (dist > d && limitAngle > abs(a)) {
            cXyz eyePos2 = dNpc_playerEyePos(attnDist);
            lookPos = &eyePos2;
            lookMode = true;
            if (m73D == 0) {
                m73D = 1;
            }
        } else if (dist > d && distAngle > abs(a)) {
            if (m73C != 0) {
                cXyz eyePos2 = dNpc_playerEyePos(attnDist);
                lookPos = &eyePos2;
                lookMode = false;
                m_jnt.setTrn();
            }
            if (m73D == 0) {
                m73D = 1;
            }
        } else {
            m73D = 0;
            if (mNpcNo == 0) {
                targetY = shape_angle.y;
                lookMode = false;
                m_jnt.setTrn();
            }
        }
    }
    if (m73C != 0) {
        lookMode = false;
        m_jnt.setTrn();
    }
    if (m_jnt.trnChk()) {
        if (mEventCut.getTurnSpeed() != 0) {
            angle = mEventCut.getTurnSpeed();
        }
        cLib_addCalcAngleS2(&mAngleY, angle, 4, 0x800);
    } else {
        mAngleY = 0;
    }
    m_jnt.lookAtTarget(&current.angle.y, lookPos, eyePos, targetY, mAngleY, lookMode);
    shape_angle = old.angle;
}

/* 00002488-000025AC       .text initTexPatternAnm__14daNpcAuction_cFb */
BOOL daNpcAuction_c::initTexPatternAnm(bool i_anm_play) {
    J3DModelData* modelData;
    if (mHeadModel != NULL) {
        modelData = mHeadModel->getModelData();
    } else {
        modelData = mpMorf->getModel()->getModelData();
    }
    m_head_tex_pattern = (J3DAnmTexPattern*)dComIfG_getObjectIDRes(l_arcname_tbl[mDataNo], (u16)mBtpNo);
    JUT_ASSERT(2203, m_head_tex_pattern != 0);
    if (!mBtpAnm.init(modelData, m_head_tex_pattern, 1, 2, 1.0f, 0, -1, i_anm_play, false)) {
        return FALSE;
    }
    m73F = 0;
    m734 = 0;
    return TRUE;
}

/* 000025AC-00002624       .text playTexPatternAnm__14daNpcAuction_cFv */
/* Nonmatching */
void daNpcAuction_c::playTexPatternAnm() {
    if (cLib_calcTimer<s16>(&m734) == 0) {
        s16 frameMax = m_head_tex_pattern->getFrameMax();
        if (m73F >= frameMax) {
            m73F = m73F - frameMax;
            m734 = getRand(0x3C) + 0x3C;
            return;
        }
        m73F = m73F + 1;
    }
}

/* 00002624-000026CC       .text playAnm__14daNpcAuction_cFv */
void daNpcAuction_c::playAnm() {
    if (mpMorf->play(NULL, 0, 0) && mpAnmDat != NULL && (s8)m748 > 0) {
        m748 = m748 - 1;
        if ((s8)m748 == 0) {
            mpAnmDat = &mpAnmDat[1];
            setAnmTbl(mpAnmDat);
            return;
        }
        setAnm(mpAnmDat->mAnmNo, 0, 0.0f);
    }
}

/* 000026CC-0000278C       .text setAnm__14daNpcAuction_cFUcif */
void daNpcAuction_c::setAnm(u8 i_anm_no, int i_attr, f32 i_morf) {
    mpMorf->setAnm((J3DAnmTransform*)dComIfG_getObjectIDRes(
                       l_arcname_tbl[mDataNo], (u16)l_bck_ix_tbl[mDataNo][i_anm_no]),
                   i_attr, i_morf, 1.0f, -1.0f, 0.0f, NULL);
    mAnmNo = i_anm_no;
}

/* 0000278C-000027DC       .text setAnm2__14daNpcAuction_cFUcif */
void daNpcAuction_c::setAnm2(u8 i_anm_no, int i_attr, f32 i_morf) {
    if (mAnmNo != i_anm_no || i_attr == 0) {
        setAnm(i_anm_no, i_attr, i_morf);
        mpAnmDat = NULL;
    }
}

/* 000027DC-00002874       .text setAnmTbl__14daNpcAuction_cFP7sAnmDat */
void daNpcAuction_c::setAnmTbl(sAnmDat* i_anm) {
    if (i_anm->mAnmNo == 0xFF) {
        mpAnmDat = NULL;
        return;
    }
    mpAnmDat = i_anm;
    m748 = mpAnmDat->mCount;
    int attr = 2;
    if ((s8)m748 > 0) {
        attr = 0;
    }
    if (mAnmNo != mpAnmDat->mAnmNo || attr == 0) {
        setAnm(mpAnmDat->mAnmNo, attr, (f32)mpAnmDat->mMorf);
    }
}

/* 00002874-00002928       .text isExecute__14daNpcAuction_cFv */
BOOL daNpcAuction_c::isExecute() {
    actor_status = actor_status & ~l_mdl_status[mDataNo];
    daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
    if (auction == NULL) {
        return FALSE;
    }
    if (!(AUC->mNpcFlag & (1 << mNpcNo))) {
        return FALSE;
    }
    actor_status |= l_mdl_status[mDataNo];
    return TRUE;
}

/* 00002928-0000298C       .text getRand__14daNpcAuction_cFi */
int daNpcAuction_c::getRand(int i_max) {
    int rnd = (int)cM_rndF((f32)i_max);
    if (rnd == i_max) {
        rnd = 0;
    }
    return rnd;
}

/* 0000298C-000029DC       .text clrEmitter__14daNpcAuction_cFv */
void daNpcAuction_c::clrEmitter() {
    JPABaseEmitter* emitter = mEmitter;
    if (emitter != NULL) {
        emitter->mMaxFrame = -1;
        emitter->setStatus(1);
        for (JSULink<JPABaseParticle>* link = emitter->mActiveParticles.getFirst(); link != NULL;
             link = link->getNext()) {
            link->getObject()->setStatus(JPAPtclStts_Delete);
        }
        mEmitter = NULL;
    }
}

inline cPhs_State daNpcAuction_c::create() {
    static cPhs__Handler l_method[] = {
        (cPhs__Handler)&phase_1,
        (cPhs__Handler)&phase_2,
        NULL,
    };
    return dComLbG_PhaseHandler(&mPhs, l_method, this);
}

/* 000029DC-00002A0C       .text daNpc_AuctionCreate__FPv */
static cPhs_State daNpc_AuctionCreate(void* i_this) {
    return ((daNpcAuction_c*)i_this)->create();
}

/* 00002A0C-00002A70       .text daNpc_AuctionDelete__FPv */
static BOOL daNpc_AuctionDelete(void* i_this) {
    daNpcAuction_c* actor = (daNpcAuction_c*)i_this;
    dComIfG_resDelete(&actor->mPhsArcname, l_arcname_tbl[actor->mDataNo]);
    if (actor->heap != NULL && actor->mpMorf != NULL) {
        actor->mpMorf->stopZelAnime();
    }
    return TRUE;
}

/* 00002A70-00002C70       .text daNpc_AuctionExecute__FPv */
/* Nonmatching */
static BOOL daNpc_AuctionExecute(void* i_this) {
    daNpcAuction_c* actor = (daNpcAuction_c*)i_this;
    dBgS* bgsp = dComIfG_Bgsp();
    if (actor->isExecute()) {
        actor->m_jnt.setParam(l_npc_dat[actor->mDataNo].mMaxBackboneX,
                              l_npc_dat[actor->mDataNo].mMaxBackboneY,
                              l_npc_dat[actor->mDataNo].mMinBackboneX,
                              l_npc_dat[actor->mDataNo].mMinBackboneY,
                              l_npc_dat[actor->mDataNo].mMaxHeadX,
                              l_npc_dat[actor->mDataNo].mMaxHeadY,
                              l_npc_dat[actor->mDataNo].mMinHeadX,
                              l_npc_dat[actor->mDataNo].mMinHeadY,
                              l_npc_dat[actor->mDataNo].mMaxTurnStep);
        actor->checkOrder();
        if (dComIfGp_event_runCheck() == 0 || (actor->eventInfo.checkCommandTalk() && actor->m744 != 0)) {
            actor->m749 = 0;
            (actor->*actor->mAction)();
        } else {
            actor->eventMove();
        }
        actor->eventOrder();
        actor->playTexPatternAnm();
        actor->playAnm();
        actor->mObjAcch.CrrPos(*bgsp);
        actor->setCollision(60.0f, 150.0f);
        actor->attention_info.position.set(actor->current.pos.x,
                                           actor->current.pos.y + l_npc_dat[actor->mDataNo].mAttnYOffset,
                                           actor->current.pos.z);
        actor->eyePos.set(actor->current.pos.x, actor->current.pos.y + l_npc_dat[actor->mDataNo].m28,
                          actor->current.pos.z);
        actor->lookBack();
        actor->setMtx();
        if (actor->mSoundTimer != 0) {
            actor->mSoundTimer--;
            if (actor->mSoundTimer == 0) {
                JAIZelBasic::getInterface()->seStart(actor->m728, NULL, 0, 0, 1.0f, 1.0f, -1.0f,
                                                     -1.0f, 0);
            }
        }
        actor->mPiconOfsY = l_npc_dat[actor->mDataNo].m30;
    }
    return FALSE;
}

/* 00002C70-00002EB8       .text daNpc_AuctionDraw__FPv */
/* Nonmatching */
static BOOL daNpc_AuctionDraw(void* i_this) {
    daNpcAuction_c* actor = (daNpcAuction_c*)i_this;
    if (actor->isExecute()) {
    J3DModel* model = actor->mpMorf->getModel();
    J3DModelData* modelData = model->getModelData();
    if (actor->mHeadModel != NULL) {
        J3DModelData* headModelData = actor->mHeadModel->getModelData();
        g_env_light.settingTevStruct(TEV_TYPE_ACTOR, &actor->current.pos, &actor->tevStr);
        g_env_light.setLightTevColorType(actor->mpMorf->getModel(), &actor->tevStr);
        g_env_light.setLightTevColorType(actor->mHeadModel, &actor->tevStr);
        actor->mBtpAnm.entry(headModelData, actor->m73F);
        if (actor->mBmtNo >= 0) {
            actor->mpMorf->updateDL((J3DMaterialTable*)dComIfG_getObjectIDRes(
                l_arcname_tbl[actor->mDataNo], (u16)actor->mBmtNo));
        } else {
            actor->mpMorf->updateDL();
        }
        MtxP src_mtx = model->getAnmMtx(actor->m_jnt.getHeadJntNum());
        MtxP dst_mtx = actor->mHeadModel->getBaseTRMtx();
        MTXCopy(src_mtx, dst_mtx);
        mDoExt_modelUpdateDL(actor->mHeadModel);
        headModelData->getMaterialTable().removeTexNoAnimator(actor->mBtpAnm.getBtpAnm());
    } else {
        g_env_light.settingTevStruct(TEV_TYPE_ACTOR, &actor->current.pos, &actor->tevStr);
        g_env_light.setLightTevColorType(actor->mpMorf->getModel(), &actor->tevStr);
        actor->mBtpAnm.entry(modelData, actor->m73F);
        actor->mpMorf->updateDL();
        modelData->getMaterialTable().removeTexNoAnimator(actor->mBtpAnm.getBtpAnm());
    }
    cXyz pos(actor->current.pos.x, actor->current.pos.y + 150.0f, actor->current.pos.z);
    actor->mShadowID = dComIfGd_setShadow(actor->mShadowID, 1, actor->mpMorf->getModel(), &pos,
                                          800.0f, 20.0f, actor->current.pos.y,
                                          actor->mObjAcch.GetGroundH(), actor->mObjAcch.m_gnd,
                                          &actor->tevStr, 0, 1.0f,
                                          dDlst_shadowControl_c::getSimpleTex());
    if (actor->mShadowID != 0 && actor->mHeadModel != NULL) {
        dComIfGd_addRealShadow(actor->mShadowID, actor->mHeadModel);
    }
    dSnap_RegistFig(l_photo_no[actor->mDataNo], actor, 1.0f, 1.0f, 1.0f);
    }
    return TRUE;
}

/* 00002EB8-00002EC0       .text daNpc_AuctionIsDelete__FPv */
static BOOL daNpc_AuctionIsDelete(void*) {
    return TRUE;
}

static actor_method_class daNpc_AuctionMethodTable = {
    (process_method_func)daNpc_AuctionCreate,
    (process_method_func)daNpc_AuctionDelete,
    (process_method_func)daNpc_AuctionExecute,
    (process_method_func)daNpc_AuctionIsDelete,
    (process_method_func)daNpc_AuctionDraw,
};

actor_process_profile_definition g_profile_NPC_AUCTION = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_NPC_AUCTION_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daNpcAuction_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_NPC_AUCTION_e,
    /* Actor SubMtd */ &daNpc_AuctionMethodTable,
    /* Status       */ fopAcStts_NOCULLEXEC_e | fopAcStts_CULL_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_0_e,
};
